### ISSUE TITLE
Sync settings and rules

### ISSUE THREAD

**Issue by salarcode** [salarcode/SmartProxy#1]
Syncing should be implemented and available as an option.

**Comment by EMLVIRUS** [comment]
Just a little question: Firefox sync or other personal cloud storage like OneDrive, Dropbox,etc.?
I prefer the latter.

**Comment by salarcode** [comment]
At first it will be Firefox/Chrome default sync API, later on I will see if there is any demand for more functionality and implement them.

**Comment by yfdyh000** [comment]
just FYI:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync 
> You can store up to 100KB of data using this API. If you try to store more than this, the call will fail with an error message. The API is provided without any guarantees about uptime or performance.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/local
> Chrome limits the extension to 5MB of data using this API unless it has the "unlimitedStorage" permission.

**Comment by salarcode** [comment]
I'm aware of that and I think that's enough. With 100KB it is possible to store around 5500 rules.

**Comment by yfdyh000** [comment]
https://github.com/gfwlist/gfwlist/blob/master/gfwlist.txt is 111KB, 6769 rules.

**Comment by salarcode** [comment]
Yes that list seems causes problems, let me see what can I do.

**Comment by yfdyh000** [comment]
perhaps: gzip / diff / more while storage.
