### ISSUE TITLE
Suscription list is not updating

### ISSUE THREAD

**Issue by hawkfx** [salarcode/SmartProxy#104]
Hello

I've a subscription link, it returns the url as JSON formatting:

{"name":"Proxy1","protocol":"http","username":"proxy2","password":"lu2","ip":"proxy.com","port":2222} 

I have this settings:

Refresh Rate: 1 min / Enabled option

![image](https://user-images.githubusercontent.com/16154108/59210096-65aed500-8b72-11e9-9c78-f25b409a15aa.png)

I click on test it gets the proxy and then save and save changes..

Then I go to "Proxy servers" and I've enabled.

![image](https://user-images.githubusercontent.com/16154108/59210153-837c3a00-8b72-11e9-8cb1-41c0c5e0f98d.png)

This works good, the problem is that when the link gets updated like this:

{"name":"Proxy1","protocol":"http","username":"proxy2","password":"lu2","ip":"proxy2.com","port":2222} 

The name remains the same, but all the rest data changes it doesn't load the changes, even if I've auto Enabled Auto Refresh.

I've to click on 'test' and 'save' to refresh the proxy data.

**Comment by hawkfx** [comment]
I think that error may be that to get the list it uses the current proxy, but if the proxy is dead can't update.

**Comment by salarcode** [comment]
That can be the case, the subscription updater applied the current proxy from either SmartMode or Always enabled mode and send the request.
If the proxy is dead the request will fail.
I need to check this, probably an option in UI to ignore the active proxy will be needed.

**Comment by salarcode** [comment]
The fix is airborn you can check it
