### ISSUE TITLE
www. subdomain differentiation ?

### ISSUE THREAD

**Issue by rezad1393** [salarcode/SmartProxy#106]
can you make it so that www is treated like other subdomains? at least an option for that?

many big websites are using different IPs for www and other subdomains and using the main domin will proxy those too which in this case is undesired.

I am from Iran (you too?) and right now the 104.xxx.xxx.xxx IPs (cloudflare I think) are getting https hangs and I want to add those but not others.

for example www.openssl.com is affected but wiki.openssl.com is not.
so when I want to add the www I only can do that with whole domain.

maybe put an option to treat www like other subdomains?

thanks.

**Comment by salarcode** [comment]
Sorry for late reply, yes I am from Iran too but lets keep this conversations in English :)
The rule created by default is applied to www as well as the one with no subdomain.
If you don't want this, edit the rule to this: www.openssl.org/*
This will only apply to www.openssl.org, if you want rule only for openssl.org the rule should be openssl.org/*

**Comment by rezad1393** [comment]
I understand the reason behind the www omission and I understand the part about using the advanced part.
but I am asking about treating www like every other subdomains so that it is listed in the menu as a separate item.

this doesn't complicate things and actually simplifies your code (www is no longer specially treated).
and I can just click on it and select it.

**Comment by salarcode** [comment]
www is special case and always will be unless otherwise is used.
Except for small number of sites that have two versions for with and without www (which is a really weird thing to do) I don't see a real use case. For those use cases, the advanced options should do the trick.

**Comment by rezad1393** [comment]
www is not that special anymore.
we are literally typing on a website that has no www (github.com) and many other site do this.
but again this issue is at your discretion.

**Comment by salarcode** [comment]
www.github.com redirects to github.com, same for most of the sites, the www being special has never changed.

**Comment by rezad1393** [comment]
btw I have tried the www.openssl.org/* but it doesnt work.

**Comment by salarcode** [comment]
Sorry the correct rules would look like these:
https://www.openssl.org/*
https://openssl.org/*

More info: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns

**Comment by rezad1393** [comment]
that doesnt work with ur addon either.

**Comment by salarcode** [comment]
Have you selected correct Rule Type?
Upload your rules backup and I will check it.

**Comment by rezad1393** [comment]
what rule type i should check?
i use host wildcard.

**Comment by salarcode** [comment]
For the rules I gave you use Url wildcard
