### ISSUE TITLE
Proxyable resources not showing the correct proxy being used

### ISSUE THREAD

**Issue by lovesyk** [salarcode/SmartProxy#108]
The "proxyable resources" window is not very reliable and was confusing me quite a bit when setting up SmartProxy. It would be great if it actually displayed which resource is being loaded by which proxy (not sure if possible API-wise) instead of parsing the rule list.

**Issue 1** (see also original issue description at the bottom):
1. Enable "Enable proxy per tab/origin"
2. Add a new rule for any page
3. Open that page
4. Open "Proxyable resources"

_Expected result_: All request URLs should be marked as proxied since the rule matches the tab URL.
_Actual result_: Only those request URLs are marked as proxied which exactly match the proxy rule.

**Issue 2**:
1. Create two overlapping rules for any page
2. Open that page
3. Open "Proxyable resources" and see that the rule that was entered first is being used
4. Create a full backup
5. Edit the backup and change the order of the two rules
6. Import the edited backup
7. Press on "Reload" in "Proxyable resources"

_Expected result_: The same rule should be displayed as in step 3 (as apparently a new tab has to be used for changes like this to become active)
_Actual result_: The rule that was moved to the top in step 5 is now displayed although it's not being used.

__________________________________________________________________________________________________
**Original issue description, not relevant anymore**

While trying out this extension, I saw the proxy-per-origin feature which seemed very useful. Unfortunately, I couldn't get it to work.

Firefox 67.0.4 / 66.0.2
SmartProxy 0.8.7

Steps:
1. Install Firefox with a fresh profile
2. Install SmartProxy
3. Make sure "Enable proxy per tab/origin" is enabled
4. Add a new SOCKS5 proxy
5. Add a new host wildcard rule for "google.com"
6. Open "google.com"
7. Open "Proxyable resources"

Expected result: All request URLs to be marked as proxied since the rule matches the tab URL.
Actual result: Only those request URLs are marked as proxied which exactly match the proxy rule.

![proxy-per-origin](https://user-images.githubusercontent.com/9806747/60758445-f912e300-a016-11e9-93d8-d03d64c851c2.png)

Am I misunderstanding something about how this feature works or is this actually a bug?

**Comment by salarcode** [comment]
Thanks for the report, currently proxyable resources page doesn't use the same engine used by the proxy engine, this is a known issues and the issue you are facing could be because of that.
This mean that proxy-per-origin is working, just doesn't display correctly in proxyable resources list.
I will have a look
