### ISSUE TITLE
Ugly rule names because of rule source domain validation

### ISSUE THREAD

**Issue by lovesyk** [salarcode/SmartProxy#109]
When setting up SmartProxy I noticed you cannot just enter any name in "Rule Source Domain" although it seems to only be used as a name to reference the rule and to generate a pattern if requested.
This creates a problem if you need more generic rules than simply for a single domain.

For example I needed a rule that'd match `http://[anyIp]:[anyPort]/h/[hash]-`.
I selected "Url regex" and entered `http://.*?/h/[0-9a-f]{40}-` but now of course I needed a matching rule source domain.
This apparently is not possible with a protocol at the front so I removed that: `.*?/h/[0-9a-f]{40}-` and was able to enter the rule source domain: `foo/h/deadbeefdeadbeefdeadbeefdeadbeefdeadbeef-`.
This rule definitely works but doesn't look very nice.

Would it be possible to disable this validation? I noticed you can export the preferences and import them back with any rule names you want but obviously cannot edit them afterwards in the browser then.

**Comment by salarcode** [comment]
Rule Source Domain is not just a name, it is used while detecting domain name failure and adding them as well as creating/updating the sugected "Enable Proxy On" list.

I may add a new type of rules called "General Rules" in the future which requires all the places it is used to be updated.

**Comment by salarcode** [comment]
This is fixed in v0.9.8

> `Rule Source Domain` on proxy rules is no longer mandatory
