### ISSUE TITLE
Doesn't work with SOCKS5 in Firefox

### ISSUE THREAD

**Issue by shmerl** [salarcode/SmartProxy#110]
Just tried the smart proxy with SOCKS5, and unlike the stock proxy settings in Firefox, it doesn't work.

**Comment by shmerl** [comment]
Oh, actually something was just misconfigured and it didn't save my changes. One has to press save twice, so that makes it a bit confusing.

**Comment by shmerl** [comment]
It's actually is broken, sorry for the noise. Simply doesn't work, unlike stock proxy Firefox settings.

**Comment by salarcode** [comment]
Can provide this information:
Are you sure your proxy is Sock5?
Proxy Mode:
Screenshot of proxy server details window:
Proxy DNS enabled?

**Comment by shmerl** [comment]
Yep, socks5, proxy DNS enabled. I'll post a screenshot a bit later.

**Comment by salarcode** [comment]
Try with proxy DNS disabled

**Comment by ettavolt** [comment]
Same problem, doesn't proxy even in 'Always Enable' mode independently of 'DNS through SOCKS5'.

Attached are [FullBackup of my settings](https://github.com/salarcode/SmartProxy/files/3416258/SmartProxy-FullBackup.TXT)

**Comment by salarcode** [comment]
@ettavolt You also try with proxy DNS disabled

**Comment by ettavolt** [comment]
Yes, I've tried
Smart mode + DNS through SOCKS5,
Smart mode + regular DNS,
Always On mode + DNS through SOCKS5.

**Comment by salarcode** [comment]
Sorry But I cannot reproduce your issue, working fine for me.
What is your proxy server?

**Comment by shmerl** [comment]
Forwarded ssh connection with SOCKS5:

```ssh -N -D 1080 <server>```

**Comment by ettavolt** [comment]
> Sorry But I cannot reproduce your issue, working fine for me.
> What is your proxy server?

Are you sure that it goes through proxy and not over regular connection? For me it's clearly not working, because regular connection is blocking the site. :)

**Comment by salarcode** [comment]
> 
> 
> Forwarded ssh connection with SOCKS5:
> 
> `ssh -N -D <port> <server>`
> 
> Then connect to `localhost:<port>` as SOCKS5 proxy.

I don't have a server to ssh into. Will find a way.


> > Sorry But I cannot reproduce your issue, working fine for me.
> > What is your proxy server?
> 
> Are you sure that it goes through proxy and not over regular connection? For me it's clearly not working, because regular connection is blocking the site. :)

I'm aware you have issue and this ticket is for that, But I need to reproduce it first to find the problem, given details are not enough to that unfortunately.

**Comment by salarcode** [comment]
Can you guys try this sock5 proxy?  `109.236.81.228` : `54321`
It is a public proxy working at the moment, located in Netherlands
Check https://what-is.net/my-country

**Comment by ettavolt** [comment]
Exactly the same: native settings yield "Netherlands" instead of my country, but doesn't work when configured through addon.

**Comment by salarcode** [comment]
The "\ui\js\datatables.min.js" file is missing? Maybe there is something wrong with your installation.
Try these:
*-  Uninstall the extension, then remove its data if not removed already from `%appdata%\Roaming\Mozilla\Firefox\Profiles\**YOUR-PROFILE**\browser-extension-data\smartproxy@salarcode.com`
Then install again and try.
*- Create a new profile with command "firefox -profilemanager" and switch to it and try the extension there. You can switch back to your original profile at anytime.

**Comment by ettavolt** [comment]
The distributed extension is OK. Two last paragraphs are my findings from meddling with sources in this repository.

**Comment by salarcode** [comment]
Can you still test in a fresh profile

**Comment by ettavolt** [comment]
It's working in new profile. Actually, no surprise.
Now to find what prevents it from working in main profile.
I've tried launching with main profile with every addon but SP disabled. No way. Interestingly, FF doesn't say now that 'Proxy settings are controlled by Addon'.

Any suggestion where in addon can I set a breakpoint to see if WebExt API returns success code on switching to Always Proxy mode?

**Comment by ettavolt** [comment]
I found it! The difference is in storage-sync.sqlite. In fresh profile it's longer. In both cases I can't decompress it.

**Comment by klauskiwi** [comment]
I'm also unable to make it work with a SOCKS5 ssh server on Firefox 70, win32 - has this ever been fixed, or has workarounds?

**Comment by ettavolt** [comment]
The problem is most likely caused by 'addon setting sync'. Shutdown your FF, make backup of profile, open sqlite database, and run the query, as in my previous comment.

**Comment by salarcode** [comment]
@klauskiwi it is most likly is because of corrupted/migrated extension data.
Can you please send the corrupted profile data located here:
%appdata%\Mozilla\Firefox\Profiles\[YOUR-PROFILE-Name]\browser-extension-data\smartproxy@salarcode.com

**Comment by TrueMilli** [comment]
I'm having the same problem, but the folder %appdata%\Mozilla\Firefox\Profiles[YOUR-PROFILE-Name]\browser-extension-data\smartproxy@salarcode.com doesn't exist.

**Comment by KrasnayaPloshchad** [comment]
What happened with Psiphone?

**Comment by mischu0729** [comment]
It still doesn't work with SOCK5 in firefox.

**Comment by salarcode** [comment]
Tested again with WinGate, Socks5 works fine with and without authentication

**Comment by salarcode** [comment]
Everybody here please enable Proxy DNS checkbox, this must be your issue which we found in #184
