### ISSUE TITLE
跳过列表无效？

### ISSUE THREAD

**Issue by tulip33** [salarcode/SmartProxy#111]
请问跳过列表主机列表要怎样写？
`*.weibo.com/*`
这样写在总是启用模式中无效，weibo.com还是会走代理
也勾选了 为总是启用模式启用

**Comment by salarcode** [comment]
Can you write in English please?

**Comment by salarcode** [comment]
Using translator it seems you are asking the way to disable proxy for some Urls.
Use `Bypass List` to disable proxy for certain hosts.
![image](https://user-images.githubusercontent.com/1272095/62511072-49b76f00-b855-11e9-8c41-ab96d088e309.png)

**Comment by srdfjy** [comment]
Hi，How Bypass List uses wildcards to match domain names？

**Comment by salarcode** [comment]
Bypass List doesn't have whildcard support, just plain domain names.
It is supported in new version 1.0 which is not released yet
