### ISSUE TITLE
Manifest file is missing or unreadable.

### ISSUE THREAD

**Issue by mbp56789** [salarcode/SmartProxy#113]
I tired to upload extension manually(load unpacked) on chrome but at the time of upload it throws manifest.json file is missing or unreadable but its on scr folder named manifest-chrome.json. How to solve this issue. Please help.
<img width="410" alt="fffff" src="https://user-images.githubusercontent.com/49287048/65293608-875d2680-db7b-11e9-86ee-1c3ff8c994cd.PNG">

**Comment by salarcode** [comment]
For chrome you need to rename manifest-chrome.json to manifest.json , same goes for other browsers.
