### ISSUE TITLE
Firefox: Failed to read settings

### ISSUE THREAD

**Issue by artemmolotov** [salarcode/SmartProxy#114]
SmartProxy v0.8.7 has stopped working on Firefox Quantum 69.0.1 (64-bit).

1) When entering the extension settings:
> [Failed to read the configurations. Please close the settings page and try again.](https://habrastorage.org/webt/iy/ew/nu/iyewnuv1z4y0gr7kp_1smi2s6ao.png)

> [No servers! Before anything you have to define proxy servers.](https://habrastorage.org/webt/iy/ew/nu/iyewnuv1z4y0gr7kp_1smi2s6ao.png)

2) When trying to restore a backup (from the same version of the extension):
> [There was an error in restoring the backup](https://habrastorage.org/webt/mx/aw/z_/mxawz_rbq3a8srfsmdexrh78kno.png)

3) Error from the Console:
> [Error: Could not establish connection. Receiving end does not exist.](https://habrastorage.org/webt/_v/ov/nc/_vovncqg17gbpynpw4koi7qb55c.png) settingsPage.js:2528:88

**Comment by artemmolotov** [comment]
1. Uninstall extension;
2. Install extension;
3. Restore a backup;
4. Backup is successfully restored;
5. The error is still present...

**Comment by salarcode** [comment]
Closing as this is probably a version migration issue
