### ISSUE TITLE
How can smartproxy support txt list of GFWlist?

### ISSUE THREAD

**Issue by Yamazaki-wu** [salarcode/SmartProxy#115]
I have been using Proxy SwitchyOmega before, and one of them is very good. Just import gfwlist.txt and you can automatically split it according to the rules of this file. How can I achieve similar functions in smartproxy?

**Comment by salarcode** [comment]
Duplicate of #34 
I was waiting for Firefox to implement required APIs.
I will start working on this for v0.9

**Comment by smsihe** [comment]
> 
> 
> Duplicate of #34
> I was waiting for Firefox to implement required APIs.
> I will start working on this for v0.9

Expecting new version！Thank you in advance ！
