### ISSUE TITLE
Chrome sync pause

### ISSUE THREAD

**Issue by ghost** [salarcode/SmartProxy#117]
Chrome sync pause with smart proxy always enables On. solution please

**Comment by salarcode** [comment]
For anyone having this issues, please add the following domains to Whitelist and save. Please let me know if it works for you.
```
accounts.google.com
www.googleapis.com
oauthaccountmanager.googleapis.com
clients1.google.com
clients2.google.com
clients3.google.com
clients4.google.com
clients5.google.com
```
