### ISSUE TITLE
Set Proxy Port

### ISSUE THREAD

**Issue by everythingincludingthekitchensink** [salarcode/SmartProxy#118]
I want to auto detect url and use certain proxy ports example

URL = 127.0.0.1:1234/home,
HTTP = 7777 
HTTPS = 8888

can this be done, This is what I've tried 

# proxy rules
URL WILDCARD 127.0.0.1:1234/home
MATCHING PATTERN 127.0.0.1:1234/home

# proxy server section

SERVER NAME HTTP
SERVER ADDRESS 127.0.0.1:1234/home
PORT 7777

SERVER NAME HTTPS
SERVER ADDRESS 127.0.0.1:1234/home
PORT 8888

It cant seem to set the ports , or is it that smart proxy is only able to use proxy urls or lists

**Comment by salarcode** [comment]
You need to use "Url regex" rule type. That type requires you to provide the RegEx for matching the url which you can create that using the help of https://regex101.com/

**Comment by salarcode** [comment]
Or you can use "Url wildcard" type with this pattern
*://127.0.0.1:1234/home/*
