### ISSUE TITLE
Firefox - proxy being triggered on sites not configured

### ISSUE THREAD

**Issue by chadcf** [salarcode/SmartProxy#121]
Today I went to memrise.com and was surprised to get an SSL error about an invalid certificate. I was suspicious of this so I killed the ssh proxy I have set up to use with this extension and found that on reloading the page I now got a "proxy not available" error. So for some reason, memrise was trying to go through the proxy. I only have a work domain configured for the proxy rules, matching *.companydomain.com/*. Further while on memrise.com clicking the SmartProxy extension in the menubar showed no domains as having the proxy enabled. Disabling the proxy rule did not fix this. Setting SmartProxy to Direct (no proxy) instead of Smart Proxy did make the site work again. 

In other browsing I have not found any other websites where this has happened and I'm not sure what is special about memrise...

**Comment by chadcf** [comment]
So after restarting my browser this seems to no longer happen... Not sure what to make of that.

**Comment by salarcode** [comment]
Thanks for the update. Is this happening often, that was the only time ever?

**Comment by chadcf** [comment]
Hi, I thought it was just the once, but now today it's happening for amazon.com.

I think I have figured out the issue though... It seems like it's not properly disabling when I leave a proxyable domain. For example if I visit domain.mycompany.com in a tab, it goes through the proxy and loads properly. If I then in that same tab go to amazon.com, it also goes through the proxy. But if I open a new tab and go to amazon.com, it does not go through the proxy. 

<img width="1207" alt="Screen Shot 2019-11-18 at 12 00 41 PM" src="https://user-images.githubusercontent.com/23989/69086171-17dca980-09fb-11ea-957e-7cd52343987c.png">

**Comment by salarcode** [comment]
I finally got time to look into this, it seems that the issue is caused by "Enable proxy per tab/origin" option. If you disable this, the problem should not happen again.
Will fix it in next release.
