### ISSUE TITLE
Change toolbar icon if the current site has proxy applied

### ISSUE THREAD

**Issue by salarcode** [salarcode/SmartProxy#127]
Change toolbar icon if the current site has proxy applied for at least one of its resources.
Either change icon color or glow icon if proxy is applied

**Comment by byzod** [comment]
Please separate the `proxy mode` and `if any rule/proxy applied` area, thus the icon can provide two information at the same time, similar to switchyproxy

If possible, provide UI DOM element indicator for different proxy mode or if-rule-applied (for example class name or custom attribute), it's useful for customize with `userChrome.css`

**Comment by salarcode** [comment]
My guess is there is no UI DOM for extention icons. They are set with `[setIcon](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setIcon)` API.
Let me know if this is possible and how, thanks.

**Comment by spphinslove** [comment]
Maybe this source code can help you,It's can do you want.
https://github.com/FelisCatus/SwitchyOmega

**Comment by spphinslove** [comment]
> Maybe this source code can help you,It's can do you want. https://github.com/FelisCatus/SwitchyOmega

Is this problem difficult to solve? This extension has this function

**Comment by laterdayi** [comment]
Thanks for the work of the author, may I ask when the icon function of adding different modes can be released

**Comment by Littleweisheit** [comment]
> Thanks for the work of the author, may I ask when the icon function of adding different modes can be released

Three years have passed.😢

**Comment by salarcode** [comment]
This is implemented for Firefox as of version 1.4

**Comment by islercn** [comment]
Why not make the toolbar icon as distinguishable as the icons in the menu?
Even if it's just using different color schemes, it's okay.

**Comment by islercn** [comment]
Now it's almost like the street signals have turned green, blue and blue-green while having a frosted effect to further narrow the color gap

.

**Comment by laterdayi** [comment]
@salarcode   chrome still can't tell the difference

**Comment by salarcode** [comment]
> Why not make the toolbar icon as distinguishable as the icons in the menu? Even if it's just using different color schemes, it's okay.

They serve a different purpose


> Now it's almost like the street signals have turned green, blue and blue-green while having a frosted effect to further narrow the color gap.

Icons should have consistency and branding. Also this was the cleanest and easiest to me.

This is a open source project, happy to accept any new designed icons. If they're any good I'll consider them :)


> @salarcode chrome still can't tell the difference

Chrome has limited flexibility like a retard and it will have limited icons. It has not updated with these designs yet. It will come in next week or so.

**Comment by islercn** [comment]
I mean, the icon remains the same, but the colors use different color schemes.
For example, system proxy = blue, always on = orange, it's definitely more distinguishable than now.
Just change the color, no need to redesign the icon.

**Comment by salarcode** [comment]
> I mean, the icon remains the same, but the colors use different color schemes. For example, system proxy = blue, always on = orange, it's definitely more distinguishable than now. Just change the color, no need to redesign the icon.

I have tried different color variations and it doesn't look good at the end

**Comment by islercn** [comment]
"blue vs orange" should be better than "blue vs green"? different color schemes should be more distinguishable

**Comment by salarcode** [comment]
> "blue vs orange" should be better than "blue vs green"? different color schemes should be more distinguishable

Maybe, maybe not, also not sure which icon you're talking about as there are couple with different colors.

I don't have more time to put into this, the icons are in SVG and open located here, feel free to edit. It would be interesting to see a different take on them:
https://github.com/salarcode/SmartProxy/tree/master/src/icons
