### ISSUE TITLE
Why a subscription like gfw-list don't work?

### ISSUE THREAD

**Issue by loicaplay** [salarcode/SmartProxy#128]
Here are my settings:

Proxy servers: 
    SOCKS5, 127.0.0.1, 1080]

Proxy Server Subscriptions:
    Url: https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
    Refresh: Rate:86400, Enabled
    Protocol: HTTPS
    Obfuscation: Base64
    Format: Plan Text
    Pass through proxy: Current Proxy
    Username: none
    Password: none
The test result on this setting: "Test was successful. The list returned 1 proxies."

It doesn't work when I'm in SmartProxy mode, and it works when I'm using SystemProxy, but I want my subscription to work in SmartProxy mode, although it's fine when I'm using SystemProxy. In addition, if I wanted to implement the Proxy in SmartProxy mode, I would have to check the "Enable Proxy on" option for the specified link under the extension button. All of which means that the list I subscribed to doesn't work.
Is there something wrong with my setup, or does the extension not yet implement the list I want to subscribe to?

**Comment by salarcode** [comment]
gfw-list is set of rules, "Proxy Server Subscriptions" is for proxy servers, these are totally different things.
You can track the process of rules subscription in here: #34

**Comment by loicaplay** [comment]
Thank you for being so quick to explain my misunderstanding, so I'm looking forward to future 0.9 releases
