### ISSUE TITLE
Can't change proxy configuration

### ISSUE THREAD

**Issue by ChrisDodd** [salarcode/SmartProxy#129]
It seems that changes to the proxy config are not reflected in the behavior of the proxy.

For example, if you have a proxy configured on port 2050, and go to the settings to change it to port 2051, save the settings, and access a URL via the proxy, firefox continues to use the old port (you can see this by tracking the network connections made by firefox), even though it shows the new port in the config screen.  Even if you kill and restart firefox, it continues to use the old port (even though the new port appears in the config).

**Comment by salarcode** [comment]
Uninstall the addon and remove the settings from here
`%appdata%\Roaming\Mozilla\Firefox\Profiles\**YOUR-PROFILE**\browser-extension-data\smartproxy@salarcode.com`
then install again and try

**Comment by ChrisDodd** [comment]
Not a very practical suggestion.

**Comment by salarcode** [comment]
If that fixes your issue then the problem is the corrupted file data. I've got couple of complaints with same context. Try it and if it doesn't fixes your issue then we can try another solution.

**Comment by ChrisDodd** [comment]
It doesn't -- I tried removing all files and keys containing 'smartproxy' or 'salarcode', but it the broken config still persists.

**Comment by salarcode** [comment]
- Do you happen to have any other Proxy/VPN addon installed?
- Can you upload your full-backup here?
