### ISSUE TITLE
Freeze Firefox on Mac

### ISSUE THREAD

**Issue by wbgt** [salarcode/SmartProxy#134]
I found Smartproxy froze FF frequently on my mac in recent days. When it occurs, it lasts several minutes before FF works normally. The version of FF is 74.0 and SmartProxy was installed from addons.mozilla.org. I have turn on/off smartproxy many times to confirm it.

**Comment by salarcode** [comment]
How many rules you have?

Can you attach your backup here?

**Comment by wbgt** [comment]
Thank you.
The rules were mostly imported from autoproxy long time ago. There are 5000+ of them. I added a few casually.

[SmartProxy-FullBackup.json.zip](https://github.com/salarcode/SmartProxy/files/4413987/SmartProxy-FullBackup.json.zip)

**Comment by salarcode** [comment]
Thank you, need to check the rules to see which one is causing delay; this will take time to look into.
You said recent days, you mean after updating to version 0.9?

**Comment by wbgt** [comment]
I am not sure about the exact date, because I might not care of the occasional failures in the beginning. But it has become more frequent for the past (maybe two?) weeks, so I decided to check the addons.
Besides, it happens on my Mac with newest OSX system, but seems never happen on another mac with an older system. I have not clue what action or website may trigger the error. It occurs just randomly.

**Comment by salarcode** [comment]
Does it occur on any specific websites?

**Comment by wbgt** [comment]
I have no idea about that. It occurs even when the browser is idle (I go away and find FF frozen wheh I am back), or when the website does not need proxy.

**Comment by salarcode** [comment]
Verions 0.9.4 is release with some performance fixes. Could you please try it as if it makes any changes?
