### ISSUE TITLE
Does not work after subscribing to gfwlist on vivaldi

### ISSUE THREAD

**Issue by u2333** [salarcode/SmartProxy#136]
SmartProxy v0.9 does not working after subscribing to gfwlist on vivaldi 2.11.1811.49 (64-bit). 
remove gfwlist and adding rules manually，it works

**Comment by salarcode** [comment]
What is not working exactly? Rules not applying? Form not saving?

**Comment by u2333** [comment]
Rules not applying

**Comment by salarcode** [comment]
Can you try with same backups in Chrome as well and check if rules are applying?

**Comment by u2333** [comment]
I only use firefox and vivaldi ,but someone has same question on chrome  #135

**Comment by u2333** [comment]
he use chinese to describe his issue

**Comment by f1ume** [comment]
I have another problem. after add whitelist proxy rule, rules not applying too. all requests not proxy, I'm using chrome

**Comment by salarcode** [comment]
The problem is fixed now in 0.9.1. The fix is in chrome store review process.
Meanwhile don't use rule subscriptions until new version is published.
