### ISSUE TITLE
gfwlist not working correctly

### ISSUE THREAD

**Issue by recgo** [salarcode/SmartProxy#137]
A rule  `.t.co` from gfwlist, matching `www.st.com` and `mnfst.com` , but in the AutoProxy or proxy switchyomega it only matching `*.t.co` . Similar to #72 .

**Comment by salarcode** [comment]
What browser you are using? which version of SmartProxy?

**Comment by recgo** [comment]
Firefox 74.0 and SmartProxy 0.9.2

**Comment by salarcode** [comment]
The fix released with 0.9.3. This hopefully fixes the issue

**Comment by recgo** [comment]
Thank you.
`.888.com` matching `16888.com` , `.138.com` matching `ip138.com` .
haha😂😭😓

**Comment by salarcode** [comment]
@recgo thanks for the update. A fix in 0.9.4 is released.
Please report if any other issues you've encounter. Thanks
