### ISSUE TITLE
FF proxy from subscription list is not appear in menu and not working :(

### ISSUE THREAD

**Issue by elfl0rd** [salarcode/SmartProxy#138]
![изображение](https://user-images.githubusercontent.com/4980243/80435957-9d4b7a80-8906-11ea-9a15-db2b8eebfb94.png)
![изображение](https://user-images.githubusercontent.com/4980243/80435980-accac380-8906-11ea-877a-8edfd4f9f2b9.png)

(proxy is public, no private data there)

**Comment by salarcode** [comment]
I confirm this, a fix will come soon

**Comment by elfl0rd** [comment]
it is strange, but nothing changed after update...

**Comment by salarcode** [comment]
Try remove the subscription, save restart browser and add it again. Let me know if this helps.

**Comment by elfl0rd** [comment]
Nothing, same behavior with first message.
Proxies appear in settings - proxy, but not enables and extension acon meny not have it.

ext v 0.9.4 FF v 76.0.1 x64

**Comment by elfl0rd** [comment]
it worked on the third attempt.

**Comment by elfl0rd** [comment]
Lol. found an issue.
If "refresh freq" in proxy list not = 0, proxies is not appear in extension menu.
![изображение](https://user-images.githubusercontent.com/4980243/81786862-e4da2500-9508-11ea-9621-d57bfc40e5ac.png)

**Comment by kiryanov** [comment]
Hi,
I'm experiencing the same issue with the latest version. Proxy server list from subscriptions only appears inside the extension settings and you can change the active proxy from there, but it's super inconvenient. Still no usual drop-down list in the icon menu.
I've tried to remove and re-add the extension and subscription lists but to no avail. Please reopen the issue as it is not fixed.

**Comment by kiryanov** [comment]
Update: proposed workaround (remove and re-add the subscription) only works if a sync is disabled in extension settings. As soon as you enable the sync, the drop-down list of proxies disappears from the icon menu.

**Comment by salarcode** [comment]
The issue is fixed now.
How subscription works: the addon reads the proxy list from subscription on browser start then make it available for selection. If it fails to read the proxy then will try later according to the refresh rate. If refresh rate is zero then it won't try again.

**Comment by elfl0rd** [comment]
Uh...

Changing proxy is no more available from extension icon meny? :((
