### ISSUE TITLE
Proxyable Resources Page Freezes

### ISSUE THREAD

**Issue by RebelliousWhiz** [salarcode/SmartProxy#139]
**System:** Windows 10 2004 with Ryzen 3700X and 8G Memory
**Browser:** Chromium Edge 83.0.478.44 (Official build) (64-bit)
**Smart Proxy Version:** Edge Store Official Version 0.9.3

**Action**
I go to the [Playstation Website](https://store.playstation.com/zh-hans-hk/checkout/buy-now/IP9103-NPIA90007_01-PSPLUS12MPROMO01-H001?emcid=pa-st-238899&utm_campaign=&utm_content=Always_On&utm_medium=Paid_Search&utm_source=&utm_term=pa-st-238899), and try to find what address I need to proxy in the Proxyable Resources page.

**Expectation**
I can scroll down and enable URLs with no problem.

**Observation**
As the list grows, the Proxy Resources page freezes, and no response when clicking on the enable button. And if this page freezes, no response also if clicked on the extension button. These also happen to any web page with many URLs.

**Comment**
I love this extension. Since the Chinese-well-known SwitchyOmega stopped development, I have been looking for something like SmartProxy. I finally found it and I loved it! It supports the sync in Chromium Edge makes me love it even more!

Please let me know if there's a way I can buy you a coffee to support your development!

**Comment by RebelliousWhiz** [comment]
Just to provide more information, if all the proxy-able URLs are enabled, the Proxyable Resources page can scroll down pretty nicely.

And I also need to mention I live in China with the Great-Forking Firewall. 😐

**Comment by salarcode** [comment]
Issues is fixed and will be released with 0.9.6
