### ISSUE TITLE
feature request: choose which proxy to use when add current page's domain to the rule via toolbar quick setting menu

### ISSUE THREAD

**Issue by megaslx** [salarcode/SmartProxy#141]
the easiest way to add current page to the rule list is clicking the toobar icon and check the domain on the quick setting menu.
but I can't choose which proxy to use this way. Is it possible to add a sub menu to quickly choose which proxy to use on the domain?

**Comment by salarcode** [comment]
This defeats the purpose and simplicity of the popup menu. Popup menu is meant to be simple and easy to use. The added complexity could be confusing.
I'm going to not accept this.
