### ISSUE TITLE
gfwlist Subscription is still buggy

### ISSUE THREAD

**Issue by bitest** [salarcode/SmartProxy#145]
gfwlist is working well when subscription refresh rate is set to 0 as default. but when i change it to 1440 or 720 as i prefer, gfwlist wouldn't work any more.

chromium edge store ver 0.9.3

**Comment by salarcode** [comment]
The subscriptions has been updated to version 0.9.5 in chrome. Edge is missed apparently. Another update is coming to subscriptions and Edge will be updated as well.

**Comment by salarcode** [comment]
0.9.6 is pushed
