### ISSUE TITLE
new update sees have regression

### ISSUE THREAD

**Issue by rezad1393** [salarcode/SmartProxy#147]
after installing the new update Version 0.9.7, it seems that it uses alot of cpu and firefox UI becomes slow, specially when opening some tabs that are added to the proxy list.
how can I test this or be sure it is your addon?
when Firefox UI became slow I disable this addon and firefox got normal (fast) again.

BTW thanks for the adding of ignore form error list but it seem to not work for base domains so if I select googletagmanager.com that has a www.googletagmanager.com error it just adds googletagmanager.com, and  the www.googletagmanager.com errors still appear in error menu.
maybe make it like the add to proxy list that when googletagmanager.com gets added to ignore list all the subdomains also get added too.

**Comment by salarcode** [comment]
How many rules you have? Can you provide a full backup please?
Also you notice slow down when visiting specific website?

As for Ignore feature, you had the other ticket to add support to rule wildcard format selection, I will implement it eventually :)

**Comment by rezad1393** [comment]
it is a somewhat reproducible bug.
I think if I use always enable and have many tabs , it may show it self. but it doesn't always does that.
I just notice it sometimes but the first time I noticed the slow tab switching (which is a sign of slow process in firefox) I noticed that the MainThread process (main firefox process) in process manager (on linux) had high consistent cpu usage.
and I remember that after I disabled this addon the issue was gone, as in immediately fixed.
so I am almost sure the issue is this addon but I cant reproduce it at will.

**Comment by rezad1393** [comment]
and last night I saw it with always enable so I dont think it is rules related.

**Comment by salarcode** [comment]
You can check the state of performance of addons by visiting "about:performance" page.
You can also check "about:memory" and press "measure and save..." and upload the file here for investigation.

I need to have a reproducible scenario to be able to fix any issues, until then I'm closing this ticket. Feel free to add comments and I'll open it again.
