### ISSUE TITLE
Bundle proxies/ Integrated proxy list

### ISSUE THREAD

**Issue by rayman89** [salarcode/SmartProxy#15]
If you could add some proxies that come with the addon or add a section in the preferences where it shows proxies from a realiable proxy list web with a button to quickly add the proxy to the addon's proxy list, it would be perfect.

Thank you.

**Comment by yfdyh000** [comment]
based on or a dupe of #3.

**Comment by salarcode** [comment]
Yes, this is a duplicate of #3.
But this addon will not provide any proxy list, you will be able to subscribe or import them.
