### ISSUE TITLE
SmartProxy do not work on new version firefox Android

### ISSUE THREAD

**Issue by osv-carbonsoft** [salarcode/SmartProxy#150]

**Comment by salarcode** [comment]
This is by Mozilla that doesn't support addons and nothing to do with this addon.

**Comment by KrasnayaPloshchad** [comment]
See the recent blog post
https://blog.mozilla.org/addons/2020/09/02/update-on-extension-support-in-the-new-firefox-for-android/

**Comment by KrasnayaPloshchad** [comment]
It’s now possible to install it on Firefox for Android Nightly
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by salarcode** [comment]
I have successfully have it installed. What is the reason it fails for you?

**Comment by salarcode** [comment]
Verified working
