### ISSUE TITLE
feature request: Option for TOR/Onion

### ISSUE THREAD

**Issue by dagaz** [salarcode/SmartProxy#154]
It seems it is not possible to use the TOR proxy as a rule for "*://*.onion/*", because it says that it is not a valid host.

It would be really nice if you can add a TOR/Onion-routing option, so that for onion-domains always use a specified Proxy.  (Which has to been set up previously, of course.)

**Comment by sn260591** [comment]
To do this, you can define host regex `.+\.onion$`

**Comment by dagaz** [comment]
OK, that was accepted. Thank you!

It is just not working (.onion domains are not found) - but I assume, that this is a problem with my tor-proxy configuration.

**Comment by dagaz** [comment]
Well - at least I solved my original problem - but it seems that SmartProxy might have an issue with the standard tor socks5 proxy:

I configured Firefox according to this article: 
http://blog.neutrino.es/2013/how-to-connect-to-onion-tor-domains-with-standard-firefox-on-linux/
Also it is necessary to set "network.dns.blockDotOnion" in about:config to "false"

That means I created a .pac-file for an automatic proxy configuration with this content:

```
function FindProxyForURL(url, host) {
    isp = "PROXY ip_address:port; DIRECT";
    tor = "SOCKS 127.0.0.1:9050";
    if (shExpMatch(host,"*.onion")) {
        return tor;
    }
    return "DIRECT";
}
```

If I import that pac-file, it imports it as http-proxy. If i change it to socks5, it does work, but it wont resolve .onion sites.

With "direct" (no proxy) setting, the auto-config with firefox works fine.
When I am honest, I do not really understand the configuration for the pac-file. But I assume that 

```
return "DIRECT";
```

might be the key part. But I am not sure if this is solvable with SmartProxy with **reasonable** effort. 
It might be nice for others if the workaround could be added to the readme-file.

As I solved my problem, you can close this issue. As I am not sure if this is a bug, it leave it open for you to decide.

Thanks again for your help.

**Comment by salarcode** [comment]
After consideration I've decided that SmartProxy will not support .onion domains.
