### ISSUE TITLE
Is there a plan to change the icon? 

### ISSUE THREAD

**Issue by mbhyaaa** [salarcode/SmartProxy#156]
The icons now don’t look modern enough.I hope the icons can be flat and concise.

**Comment by salarcode** [comment]
If anyone willing to design a new one, why not 😄

**Comment by salarcode** [comment]
New icons are applied and will be release with next version:
https://github.com/salarcode/SmartProxy/commit/feac32de6d1b061196b1b25e4a80785f504168d2

Duplicate of #127
