### ISSUE TITLE
Can Add a new ProxyModeType like ClearProxy or other name

### ISSUE THREAD

**Issue by Wirili** [salarcode/SmartProxy#158]
can give the control back to other apps or system settings
![X0J{IJYUZ% {R8BAINU` TV](https://user-images.githubusercontent.com/16308800/102005149-8fd9e800-3d51-11eb-8b10-69060ee3474b.png)

**Comment by salarcode** [comment]
System mode is for that. No other option is required.

**Comment by Wirili** [comment]
Now the System mode only can use IE proxy. can not give the control back to other apps

**Comment by salarcode** [comment]
It is not IE proxy, it is Windows proxy which is applied to all applications.

**Comment by Wirili** [comment]
Yes,but if i have some other chrome extension ,like best vpn、ghelper, use system mode can not work.

**Comment by salarcode** [comment]
That is a different issue caused by other extensions.
What do you want is a way to bypass other extensions.

**Comment by Wirili** [comment]
Yes，Can use other extensions by modifying the mode，no extensions use windows proxy

**Comment by Wirili** [comment]
I tried "chrome.proxy.settings.clear" to achieve this function
