### ISSUE TITLE
Allow to specify proxy server for each rule

### ISSUE THREAD

**Issue by olifre** [salarcode/SmartProxy#16]
It would be nice to be able to specify which proxy to use for which pattern, instead of always being forced to use one single proxy. 

For instance, I have one SOCKS proxy "A" to access network at work, and another proxy "B" to access network at another working place. 
With FoxyProxy, I was able to match the URL pattern and use proxy "A" for all URLs in that network, and proxy "B" for URLs in the other network. 

That seems to be the only feature missing in comparison to FoxyProxy I believe, and the FoxyProxy 5 rewrite is currently cracking up... 
Likely, handling that is also necessary to allow import from FoxyProxy. 

Maybe the easiest to embed that in the GUI would be to have rules use the "global" proxy by default, but allow to select a dedicated proxy optionally specific for the rule.

**Comment by salarcode** [comment]
That's good idea 👍

**Comment by salarcode** [comment]
There will be a column to specify a proxy server for each rule.
The default value will be [General] which is the current active proxy.

**Comment by olifre** [comment]
Sounds good!
Certainly looking forward to it, FoxyProxy appears to have gone bad (cloud sync stuff integratd, but most features lost, e.g. all rules gone - really unusable interface in the new version, no config migration etc.). So this extension here is the only really useful WebExtension proxy plugin for FireFox as of now 🥇 .

**Comment by salarcode** [comment]
This is released with version 0.4 in Chrome WebStore and is in queue to be approved in AMO

**Comment by sparkle32817** [comment]
But this is allow proxy servers don't have authentication in Chrome.
like (Servers with authentication are not supported in Chrome)..

We can't use that function on Chrome?

**Comment by salarcode** [comment]
@sparkle32817 because of how proxies are implemented on Chrome this is not possible to have authentications
