### ISSUE TITLE
Proxy mode is synced even if "Enable syncing proxy-mode" is unchecked

### ISSUE THREAD

**Issue by ameaninglessname** [salarcode/SmartProxy#161]
I encountered this problem when I have two devices, one of them need "Direct" mode and the other need "Smart Proxy" mode.

And it just synced to each other every day.😅
![图片](https://user-images.githubusercontent.com/20263103/106775685-4c7b6600-667e-11eb-8749-0e047deeaf25.png)

My syncing setting👇
![图片](https://user-images.githubusercontent.com/20263103/106775742-58672800-667e-11eb-8dbe-cf3834dc0509.png)

Browser:

Firefox desktop version 85.0 64bit
(Same problem in last few versions)

By the way, this extension is really useful, thanks!

**Comment by salarcode** [comment]
Thank you for the report, I need to check this.

**Comment by ameaninglessname** [comment]
Thanks for the latest release, by the way, there is a typo in release note😂

> Rule Source Domain on proxy rules is no loner mandatory

should be:

> Rule Source Domain on proxy rules is no lon**g**er mandatory
