### ISSUE TITLE
smartproxy will cause firefox http requests to be blocked for too long time

### ISSUE THREAD

**Issue by wuliaotc** [salarcode/SmartProxy#162]
Browser rversion :`firefox developer edtion 86.0b9 for archlinux`

Browser config:
 - network.http.max-persistent-connections-per-proxy : 500
 - network.http.max-persistent-connections-per-server : 25
 
addons config:
  - proxy rules [gfw mirror]( https://pagure.io/gfwlist/raw/master/f/gfwlist.txt),but not use.
  - use local proxy `socks5:://127.0.0.1:1080` with enable **remote dns** support.
  - proxy mode : always enable

appearance:
  - when I visit some site like google and github,  the http request will be blocked for 10+ seconds

**Comment by salarcode** [comment]
sooo, you resolved the issue?

**Comment by wuliaotc** [comment]
> 如此，您解决了这个问题？
not yet.
I now think this might be a problem of firefox.
