### ISSUE TITLE
Random proxy?

### ISSUE THREAD

**Issue by mazbron** [salarcode/SmartProxy#166]
Any plan to add Random proxy from proxy list?

**Comment by salarcode** [comment]
What will be the use-case scenario for this feature?

**Comment by mazbron** [comment]
> What will be the use-case scenario for this feature?

IDK, that's why I ask about this lol

**Comment by salarcode** [comment]
I don't see any use for this feature, so no, there is not plan to add this.

**Comment by mazbron** [comment]
> I don't see any use for this feature, so no, there is no plan to add this.

this feature is good for bot I think.

**Comment by salarcode** [comment]
I'm sill not convinced about usefulness of this feature. Closing for now; feel free to add more comments.
