### ISSUE TITLE
Track language messages changes

### ISSUE THREAD

**Issue by salarcode** [salarcode/SmartProxy#17]
If anyone want to get updates of language file changes, subscribe to this issue.
This includes addition/removal/update of the messages.

**Comment by Rictusempra** [comment]
@salarcode Why not use online service like transfex or babelzilla

**Comment by salarcode** [comment]
@Rictusempra Transifex is not free and none of them support WebExtensions AFAIK.

**Comment by salarcode** [comment]
Translations are available through https://crowdin.com/project/smartproxy now

**Comment by Rictusempra** [comment]
@salarcode Can I still give PR(s) here?
I really hate registering another account.

**Comment by yfdyh000** [comment]
@Rictusempra you can login that website using github.

**Comment by salarcode** [comment]
Crowdin is very comfortable to use. It makes everyone's life easier :-)
And it has different login methods.

**Comment by salarcode** [comment]
@yfdyh000 you maybe interested in this: https://bugzilla.mozilla.org/show_bug.cgi?id=1401506

**Comment by yfdyh000** [comment]
@salarcode I don't understand its necessity.

**Comment by salarcode** [comment]
@yfdyh000 in my country almost everyone use English version of browsers, but meantime they like to see some parts in their own language. Like this addon for example.
That's where an Api to do this becomes useful.

**Comment by yfdyh000** [comment]
As a workaround, these users can modify the `general.useragent.locale` to their preference with English version.
