### ISSUE TITLE
[Suggestion] Reload on enable

### ISSUE THREAD

**Issue by belg1o** [salarcode/SmartProxy#170]
Hello,

I was wondering if it would be possible to enable hard reloading (Ctrl+R) automatically when selecting a new proxy server or changing the proxy server. 
Would be a nice QoL setting to have as a toggle.

Thanks for reading.

**Comment by salarcode** [comment]
This might get implemented in future
![image](https://user-images.githubusercontent.com/1272095/120041858-60434180-c04c-11eb-9992-92f8a2045e4e.png)

**Comment by salarcode** [comment]
Good for contributors to pickup this one

**Comment by lengthmin** [comment]
I'm trying to implement this.

**Comment by salarcode** [comment]
Just be aware SmartProxy is going under a big change under this branch. The Master branch is in maintenance mode for now.
https://github.com/salarcode/SmartProxy/tree/SmartProfiles

**Comment by lengthmin** [comment]
> Just be aware SmartProxy is going under a big change under this branch. The Master branch is in maintenance mode for now. [`SmartProfiles`](https://github.com/salarcode/SmartProxy/tree/SmartProfiles?rgh-link-date=2021-11-14T08%3A59%3A14Z)

I'll wait until it merged.

**Comment by salarcode** [comment]
FYI SmartProfiles are merged in main branch and ticked is tracked in #213
