### ISSUE TITLE
Failed Requests shouldn't bypass proxy & load on naked IP

### ISSUE THREAD

**Issue by Tiffys** [salarcode/SmartProxy#171]
If you're using a proxy program and a site blocks your proxy the page shouldn't then bypass the proxy and load using your naked actual IP, that defeats the entire purpose of using a proxy. So I think the Failed Requests List thing should refuse to load any site that fails requests rather than just letting it bypass the proxy.

**Comment by salarcode** [comment]
'Failed Requests List ' displays the list of request that are actually failed. 
It does not bypass the proxy at all. 
You may need to define more rules or check 'Proxyable Resources' to see what other rules you need to define on that certain site.
