### ISSUE TITLE
Translate to Chinese

### ISSUE THREAD

**Issue by anye1998** [salarcode/SmartProxy#173]
SmartProxy brings a handful of features to users from beginner one to advanced one which some is listed here: 
不管是初学者还是高级用户，SmartProxy都为其提供了一系列功能，此处列出了其中一些：

Just enable proxy for one site on a tab and everything there will have proxy enabled automatically. This feature is called proxy-per-tab
只要在一个标签上对一个网址启用代理，那这个标签页的所有的网址都会自动启用代理。这个功能叫做 “标签页代理”

Automatically detect when to enable or disable proxy to certain websites based on rule patterns
根据代理规则自动判断何时启用或禁用某些网站的代理

Easily switch between many proxy servers as your active proxy server setting
在多个激活的代理服务器之间轻松切换

Switch on proxy for current site you are on it with one click
对于当前网站一键打开代理

View current website items and requests and decide whether to enable proxy for them with one click
查看当前的网站项目和请求，并决定是否一键启用代理

Easily switch between proxy modes or enable proxy for all domains
轻松地切换代理模式或启用所有域的代理

Backup/Restore settings and rules
备份/恢复设置和规则

Please note that:
请注意：

SmartProxy does not provide any type of proxy servers.
SmartProxy不提供任何类型的代理服务器。

SmartProxy does not track you in any way.
SmartProxy不会以任何方式跟踪你。

SmartProxy is completely ad free in any way.
SmartProxy完全无广告。

Your feedback is important
您的反馈很重要

If you ❤ SmartProxy please rate it in Firefox Add-ons page.
如果您❤SmartProxy，请在Firefox Add-ons页面上给它评分。

If you have questions or problems please head to issues page and open a ticket. Report Issues. 
如果您有任何疑问或问题，请转到问题页面并打开故障单。Report Issues。 

![屏幕截图 2021-05-07 184858](https://user-images.githubusercontent.com/43033792/117442161-fbbf2600-af68-11eb-8800-795f3c55e2c7.png)

**Comment by StrollStars** [comment]
感谢翻译，其实直接fork一个，然后翻译好了以后提交效率更高。

**Comment by tuwulin365** [comment]
> 感谢翻译，其实直接fork一个，然后翻译好了以后提交效率更高。

作者是国人吗？

**Comment by StrollStars** [comment]
@tuwulin365 从[这个链接](https://github.com/salarcode/SmartProxy/issues/315#issuecomment-1687269453)看，估计不是吧。

**Comment by salarcode** [comment]
Hi all, it is possible to translate the about page now.
Please use Crowdin to do the translation:
https://crowdin.com/editor/smartproxy/146/en-zhcn
