### ISSUE TITLE
Translate to Chinese

### ISSUE THREAD

**Issue by anye1998** [salarcode/SmartProxy#174]
SmartProxy is a smart automatic proxy switcher that will automatically enable/disable proxy for the sites you visit, based on customizable rules.
SmartProxy是一个智能的自动代理切换器，根据可自定义的规则自动为您访问的站点启用/禁用代理。 

What is SmartProxy
什么是SmartProxy

Using proxies cannot be easier with SmartProxy. Think of it as configure once and forget solution. With SmartProxy you don't need to change your proxy manually or turn it on and off. All you have to do is to tell SmartProxy that you want to enable proxy for your desired website with just one click. After that, when you visit that specific website, SmartProxy will act and all you data for that website will be transferred though the proxy, without you doing anything.
有了SmartProxy，使用代理就再简单不过了。把它看作是配置一次就可以忘记的解决方案。有了SmartProxy，你不需要手动改变你的代理，或打开和关闭它。你所要做的只需点击一下告诉SmartProxy，你想为你想要的网站启用代理。之后，当您访问该网站时，SmartProxy将采取行动，该网站的所有数据将通过代理传输，无需您做任何事情。

Please note that:
🚫 SmartProxy does not provide any type of proxy servers.
👀 SmartProxy does not track you in any way.
⭐️ SmartProxy is completely ad free in any way.
请注意：
🚫 SmartProxy不提供任何类型的代理服务器。
👀 SmartProxy不会以任何方式跟踪你。
⭐️ SmartProxy完全无广告。

SmartProxy
It uses patterns to automatically define rules to proxify your web experience. With SmartProxy, you don't need to change your proxy manually and turn it on and off. You can add your desired website to the proxy rules list with just one click. After that, when you visit that specific website, SmartProxy will act and all you data for that website will be transferred though the proxy, without you doing anything.
SmartProxy
它使用模式来自动定义规则以代理您的网站。 使用SmartProxy，您无需手动打开/关闭代理。 您只需单击一下，就可以将所需的网站添加到代理规则列表中。 之后，当您访问该特定网站时，SmartProxy将起作用，并且该网站的所有数据将通过代理进行传输，而无需您进行任何操作。 

What's more, SmartProxy is inspired by AutoProxy and AutoProxy-ng and that are now considered legacy. SmartProxy is completely written from ground up using WebExtensions and provides more functionality than those proxies.
此外，SmartProxy受现已停止更新的AutoProxy和AutoProxy-ng的启发。 SmartProxy是完全使用WebExtensions从头开始编写的，并且比这些代理提供更多的功能。

Highlights
亮点

Automatically detect when to enable or disable proxy to certain websites based on rule patterns
根据代理规则自动判断何时启用或禁用某些网站的代理

Easily switch between many proxy servers as your active proxy server setting
在多个激活的代理服务器之间轻松切换

Easily with one click add current site to your proxy list
一键轻松将当前站点添加到您的代理列表中

View current website items and requests and decide whether to proxify them with one click
查看当前的网站项目和请求，并决定是否一键启用代理

Easily switch between proxy modes and enable proxy for all domains
轻松地切换代理模式或启用所有域的代理

Proxy API is supported through subscriptions
通过订阅支持代理API

Backup/Restore settings and rules
备份/恢复设置和规则

Supporting GFWList, learn how here
支持GFWList，在此了解如何支持

Permissions explained
权限说明

Disclaimer: This addon is solely created to spread freedom by easing the access to blocked contents. Any misuse like gaining access to harmful or graphic content and etc. is discouraged.
免责声明：本插件的创建完全是为了通过放宽对被屏蔽内容的访问来传播自由。我们不鼓励任何滥用行为，如获取有害或图形内容等。

To report bugs or ask questions please refer to this url:
https://github.com/salarcode/SmartProxy/issues
报告错误或提出问题，请点击此网址：
https://github.com/salarcode/SmartProxy/issues

![Screenshot 2021-05-07 at 20-03-33 SmartProxy – 下载 🦊 Firefox 扩展（zh-CN）](https://user-images.githubusercontent.com/43033792/117447931-adae2080-af70-11eb-85ff-54a8beab0d8a.png)

**Comment by salarcode** [comment]
Thank you, info is updated

![image](https://user-images.githubusercontent.com/1272095/124375093-988d0e00-dce3-11eb-8d1a-711e74ad942e.png)
