### ISSUE TITLE
Support Switchy format in Proxy Rules Subscriptions

### ISSUE THREAD

**Issue by Daymond** [salarcode/SmartProxy#175]
Hello, I'm a user from Proxy SwitchyOmega. 
I'm using a Switcht format rule list and which performs much better for me compared to GFWlist. I also find many rule lists are in PAC format which is not supported by SmartProxy. 

Could these two features be added?

**Comment by salarcode** [comment]
Can you mention what type of rules are not supported here?
Link to documents would be nice.

**Comment by Daymond** [comment]
I'm sorry, I could just provide two lists.
This one is in PAC format:
https://github.com/breakwa11/gfw_whitelist

This one is in Switchy format:
https://github.com/pluwen/china-domain-allowlist

**Comment by salarcode** [comment]
I will support Switchy format but not PAC format

**Comment by salarcode** [comment]
This partially fixes #2

**Comment by Daymond** [comment]
> 
> 
> I will support Switchy format but not PAC format

Thanks a lot.

**Comment by salarcode** [comment]
Hey @Daymond do know more rules in Switchy format?

**Comment by salarcode** [comment]
Switchy Support is added in Version 0.9.9

**Comment by Daymond** [comment]
> 
> 
> Switchy Support is added in Version 0.9.9

Wow, thanks.

**Comment by omnjpa27516** [comment]
Please support clash format, these rules are under active maintenance
https://github.com/Loyalsoldier/clash-rules

@salarcode
