### ISSUE TITLE
Seems to be a bug 

### ISSUE THREAD

**Issue by xiaozixun** [salarcode/SmartProxy#177]
Browser： 
firefox 88.0.1 for win10

URL：
https://www.acfun.cn  

appearance:：
Can't watch the video，the video can only play for a few seconds 。

In addition, smartproxy will slow down the display of web pages。

**Comment by salarcode** [comment]
1- Can you please link a specific page?
2- Also be specific about your issue? how many  rules you have defined? do you have rules subscription?

**Comment by xiaozixun** [comment]
> 
> 
> 1- Can you please link a specific page?
> 2- Also be specific about your issue? how many rules you have defined? do you have rules subscription?
It seems that it may be a firefox bug, I can't reproduce it。
Similar situation （?）：
https://bugzilla.mozilla.org/show_bug.cgi?id=1719046
https://bugzilla.mozilla.org/show_bug.cgi?id=1703232

my defined rules：
DomainSubdomain   cool18.com|namethatporn.com|pximg.net  true

my rules subscription：
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by salarcode** [comment]
Thanks for the links, seems to be a Firefox issue.
Can you try the same in Chrome aswell?

**Comment by salarcode** [comment]
There is a related fix one day ago
https://bugzilla.mozilla.org/show_bug.cgi?id=1720079

**Comment by xiaozixun** [comment]
> 
> 
> Thanks for the links, seems to be a Firefox issue.
> Can you try the same in Chrome aswell?

I don’t have chrome, only edge，no problem with edge


> 
> 
> There is a related fix one day ago
> https://bugzilla.mozilla.org/show_bug.cgi?id=1720079

Currently there is only the problem of slow web page loading

**Comment by salarcode** [comment]
Firefox 90 is released with the fix, please verify if this is still the case.

**Comment by xiaozixun** [comment]
> 
> 
> Firefox 90 is released with the fix, please verify if this is still the case.

Currently there is only the problem of slow web page loading

**Comment by xiaozixun** [comment]
> Firefox 90 已发布修复程序，请验证是否仍然如此。

The current version seems to be free of problems（Firefox 95.0.2）
Maybe it really is a Firefox problem

**Comment by salarcode** [comment]
Thanks for confirming @
