### ISSUE TITLE
how to untick/(don't use proxy) when the website conform to the subscribed proxy rules.

### ISSUE THREAD

**Issue by shinji-ikari** [salarcode/SmartProxy#180]
tried use the keyword `subsribed / subscribe` to check is there already an issue here, and it seems not. if already exist same issue please point out, thank u.

here is the thing, when i set one website in proxy rule by myself, i can `untick` it to access the website directly,
but when it also conform to the `subsribed proxy rules` it can't. i can only accept it always use proxy.

so how do i make it don't use proxy when it's in the `subsribed proxy rules`?

for example: 
subscribed proxy rules  :  https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
open the google.com, 
it will always use proxy to access google.com.

**if change the mode from `smart proxy(智能判断)` into `no proxy(直接连接 无代理)` that's very inconvenient.

![图片](https://user-images.githubusercontent.com/12407493/123471861-ff962d00-d628-11eb-960e-e8fdc010a63a.png)

> google.com
(from the subscription)

**Comment by ameaninglessname** [comment]
Sounds like you need a rules list whose priority is greater than others.
I am not sure if "user rules" can do that.

**Comment by shinji-ikari** [comment]
![图片](https://user-images.githubusercontent.com/12407493/123509599-fba9ef80-d6a8-11eb-8f73-040bf44ea679.png)
![图片](https://user-images.githubusercontent.com/12407493/123509623-1bd9ae80-d6a9-11eb-83ab-33851805b625.png)

is the `user rules` means this?  

hmmm.....how to say.
now it's , if the subcribed proxy rules like : gfwlist, already contain the google.com, than i can't choose to stop it use proxy. unless i stop use the gfwlist. it's not editable.
and i do need gfwlist for most time....so it's really becoming an issue for me. 
so i wonder is there a way for smartproxy to achieve this kind of funtion? if don't , i'll try if there other ways to do that.



![图片](https://user-images.githubusercontent.com/12407493/123509808-437d4680-d6aa-11eb-8918-b157cc37278c.png)
![图片](https://user-images.githubusercontent.com/12407493/123509826-509a3580-d6aa-11eb-94b1-03ed17f21e84.png)


i just try the white list.  should it be a bug or what? i put in white list, and it only show `from subscribed proxy rules`.
doesn't tell u it's in white list....

**Comment by salarcode** [comment]
Sorry I don't understand Chinese so the pictures doesn't mean much.

But to bypass subscription you can create whitelist rule as you did later there:
![image](https://user-images.githubusercontent.com/1272095/126710767-481865f3-1bdd-4fed-be41-432b1a43ed18.png)


Also I agree this is a kind of an unconvincing UI that it still shows rules are applied from subscription which in fact they are whitelisted.

I may replace check with a hand (✋) to indicate the whitelist.

**Comment by salarcode** [comment]
Done, will be released with 0.9.10
