### ISSUE TITLE
SOCKS5 with authentication on MS Edge does not work

### ISSUE THREAD

**Issue by 26dx** [salarcode/SmartProxy#181]
Hello.
SOCKS5 with authentication did not work in the version for Edge. Tried the same setup in Firefox and anything worked perfect.
Using: 
Edge 91.0.864.64
SmartProxy 0.9.8.1
SS5 3.8.9

Error from the proxy side:
"" "" ISERROR - - - (-:- -- -:-) (Socks method unknown or bad request)

**Comment by salarcode** [comment]
Authentication for socks5 is not implemented in chromium based browsers which includes Edge
https://bugs.chromium.org/p/chromium/issues/detail?id=256785

You can use FireFox for this.


I might disable the authentication UI for Chrome to not confuse users

**Comment by DawnElixir** [comment]
May I know if we can do authentication for HTTPS protocol? Since HTTPS auth should not be disabled for chromium based browsers

**Comment by salarcode** [comment]
I might be possible with Manifest 3 changes, this needs further R&D

**Comment by andreask1** [comment]
@salarcode Is this theoretically working already for HTTPS? The new onAuthRequired webRequest event (requiring permission webRequestAuthProvider) should be available now: https://bugs.chromium.org/p/chromium/issues/detail?id=1135492#c94
