### ISSUE TITLE
Exact Url rule is not working in Chrome

### ISSUE THREAD

**Issue by beshoo** [salarcode/SmartProxy#182]
![image](https://user-images.githubusercontent.com/4635115/125360856-2799c600-e375-11eb-8c65-e6a1f12e88f0.png)
and when i open the URL 
https://beshoo.com/mongo/
it shows me my current IP not the proxy
the only thing is working is 
![image](https://user-images.githubusercontent.com/4635115/125361070-78a9ba00-e375-11eb-9da4-e0feae148d52.png)

but I need the proxy on an exact url

**Comment by beshoo** [comment]
![image](https://user-images.githubusercontent.com/4635115/125361354-de964180-e375-11eb-93f7-ae3380ffd572.png)

**Comment by salarcode** [comment]
Hi, what is your browser?

**Comment by salarcode** [comment]
Thanks for reporting. My guess is your browser is chrome right?
This only happens in chrome browser.

**Comment by beshoo** [comment]
Yes it is chrome.

**Comment by salarcode** [comment]
You will get the fix with next relase
