### ISSUE TITLE
Not working with Socks 5 in Firefox

### ISSUE THREAD

**Issue by byzod** [salarcode/SmartProxy#184]
FDE 91.0b7
win10 pro 20h2
clash v0.16.2

Exact same proxy settings (127.0.0.1, socks5), both "always active" mode, trying to connect google.com

# SwitchyOmega
> ![1a](https://user-images.githubusercontent.com/848607/127462483-6a3c65ae-d790-4112-9cd3-e68404ec5e5e.png)
> 
> ![1b](https://user-images.githubusercontent.com/848607/127462494-1a78d3ca-47c9-4618-b65e-897f639b9a79.png)

# Smartproxy
> ![2a](https://user-images.githubusercontent.com/848607/127462580-ebcd393c-fa87-4a5e-9150-8c1ac6828320.png)
> 
> ![2b](https://user-images.githubusercontent.com/848607/127462586-797a55a1-3893-46ac-8429-897af242b5d1.png)

**Comment by salarcode** [comment]
Did you have both extensions installed at the same time by any chance?

**Comment by byzod** [comment]
No, test them one at a time

**Comment by salarcode** [comment]
Tested with Clash 2021.07.03 windows with Socks5 and it works just fine.

Can I have a copy of your backup for smartproxy?

**Comment by byzod** [comment]
When I install it again and test, it works, for few seconds, partially

* Google.com loaded and can search, for about 15 seconds then failed to response
* twitter.com failed to load all the time
* https://www.pixiv.net/ returns error `SSL_ERROR_BAD_CERT_DOMAIN`

All of them are just fine when I switch back to switchyomega

I suppose your addon is messing with a lot of things or I won't encounter the cert warning, which is suspicious...

[SmartProxy-FullBackup.zip](https://github.com/salarcode/SmartProxy/files/6911401/SmartProxy-FullBackup.zip)

**Comment by salarcode** [comment]
Thanks for the backup, everything seems normal.
Addons don't control certs. Smartproxy tells browser to use which proxy and that is all they do.

Everything works in my end, I need to reproduce this in order find the issue and fix it.

Can you test in other browsers as well please? Chrome and Edge? the proxy engine is different in chromium browsers and need to make sure this is firefox only problem or not.

**Comment by byzod** [comment]
It works fine on chrome (chromium, specifically)

Tested google/twitter/pixiv, all of them are fine. Worthing noting that there‘s no cert warning on pixiv

smartproxy: 0.9.9 (jogcnplbkgkfdakgdenhlpcfhjioidoj)

Chromium: 86.0.4240.111 (release) (64 bit)

**Comment by salarcode** [comment]
Checking switchyomega code, it is setting ProxyDNS on by default, this could be the reason your DNS queries fail and display as Cert issue.

Can you enable `Proxy DNS when using SOCKS 5` and try again?
![image](https://user-images.githubusercontent.com/1272095/128013040-a050d780-3b0a-4bed-8dbe-21e4fa81c6db.png)

**Comment by byzod** [comment]
It's working, on every site I've tested so far, no cert warning!

Thanks dude, this is really helpful <3 <3 <3 <3 🥇 

btw I like your one-hotkey-to-switch-proxy-mode, it's been years that I have to drop this behavior since autoproxy 👍

**Comment by salarcode** [comment]
Happy that fix is simple, I will make Proxy DNS as default option.

**Comment by salarcode** [comment]
0.9.10 is published
