### ISSUE TITLE
Doesn't bypass list support wildcard?

### ISSUE THREAD

**Issue by ShadowEmbrace** [salarcode/SmartProxy#185]
With "Enable for 'Always Enable' mode" checked, I tried
\*.com
\*.//\*..com/\*
\*..com/\*
nothing worked.
dict.com does work though.
So bypass list only works with complete domain names?
__________________________________
Amazing addon by the way. I love it!

**Comment by salarcode** [comment]
Thanks,
That's right, the bypass list works only on domain names.
