### ISSUE TITLE
Proxy is not applied when launch firefox from external links

### ISSUE THREAD

**Issue by byzod** [salarcode/SmartProxy#186]
When firefox is not running, click on external links would launch firefox (if you set to default browser) and open said links

Links opened in this way failed to route through proxy by smartproxy

p.s. links opened in this way were proxied by switchyomega correctly

### Reproduce (on Windows):
1. Set firefox as default browser, install smartproxy, setup a valid proxy server with [clash](https://github.com/Fndroid/clash_for_windows_pkg/releases/) (or any other proxy program), click smartproxy icon, set to `always active` mode
2. Close firefox.exe process
3. Open any external link that you can't access without proxy. For example, press `win+R` then paste `http://www.google.com` then press `enter` key
  3.1 If you have trouble finding a link you can't access without proxy, please check `Connections` tab of clash, any incoming connections will be displayed here since we set proxy mode to `always active`

### Expected result:
* Firefox startup then open `http://www.google.com` with set proxy 
* New google.com connections show up in clash's `connections` tab

### Actual result:
* Firefox startup but failed to open `http://www.google.com` (if you can't access it without a proxy)
* There's no connections through clash, nothing shows in clash's `connections` tab

**Comment by salarcode** [comment]
Thanks for the detailed report, I can guess this is because of a delay in loading synced configurations.
You may try this with sync disabled and it might work (I haven't tested).

This can be fixed by prioritizing local config first.

**Comment by salarcode** [comment]
Fixed in v1.0 by #213
