### ISSUE TITLE
[New Feature] Show which rule is matched?

### ISSUE THREAD

**Issue by yjqiang** [salarcode/SmartProxy#187]
![image](https://user-images.githubusercontent.com/8900942/129463190-7a81c3b1-31ff-4c19-a9af-ba4e25326fb2.png)
I used SwitchyOmega before and I used https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt as a rules subscription. It can show which rule is used for current page.
![image](https://user-images.githubusercontent.com/8900942/129463243-0cb4cb50-0af5-4d94-bab1-32574582d210.png)
But SmartProxy doesn't show this.

**Comment by salarcode** [comment]
Fixed in v1.0 by #213
