### ISSUE TITLE
Proxy servers of HTTP type not working in Firefox 92.0

### ISSUE THREAD

**Issue by silverzhaojr** [salarcode/SmartProxy#189]
With the latest version (0.9.10) in Firefox 92.0 on macOS 11.6, when I select the proxy of http type, seems it doesn't take effect, even in "Always Enable" mode. Could you please help verify that?

It does work in MS Edge though, with the same version of SmartProxy. It's also working with proxy of socks5 type.

**Comment by towerbit** [comment]
Same situation, dose not work with ff v92.0 on win10, but OK with Edge v95.0 dev.

**Comment by omnjpa27516** [comment]
same issue.

**Comment by Anakhoret** [comment]
I confirm. Doesn't work in Firefox 92.0. Also does not work in Brave 1.29.81 Chromium: 93.0.4577.82

**Comment by oxcelovel** [comment]
Same issue for me  0.9.10 on Win 10pro  ff 92.0.1 (64-bit)

**Comment by Anakhoret** [comment]
It works for me only with socks5 on firefox 92.0.1. HTTP/HTTPS not working.

**Comment by silverzhaojr** [comment]
I'm using SwitchyOmega temporarily as backup, HTTP proxy can work with it in firefox 92.0 on macOS 11.6.

**Comment by salarcode** [comment]
Hey everyone, there is an unannounced internal change in Firefox 92.0 that causes the proxy to fail.
This affects HTTP, HTTPS and SOCKS4 proxy server types. SOCKS5 proxy servers will function normally.
I have already identified the issue and a fix will be released with version 0.9.11

**Comment by Anakhoret** [comment]
Great. We'll wait for the update.

**Comment by salarcode** [comment]
Version 0.9.11 is already published and is in approval waiting list.

**Comment by salarcode** [comment]
Version 0.9.12 is live
