### ISSUE TITLE
UI issue: sometimes the menu of proxy list selection overflows in Firefox Mac

### ISSUE THREAD

**Issue by silverzhaojr** [salarcode/SmartProxy#190]
I'm using SmartProxy 0.9.10 in Firefox 92.0 on macOS 11.6. When I change the active proxy, sometimes the selection menu flies away, as can be seen in the screenshot:

<img width="740" alt="Screen Shot 2021-09-16 at 14 18 18" src="https://user-images.githubusercontent.com/4557341/133561533-f2135279-8203-458b-8303-31a3a42b8955.png">

**Comment by salarcode** [comment]
It is more of a platform issue that this proxy has no control over it. The drop down is rendered by the browser.
Can't do much about this!

**Comment by silverzhaojr** [comment]
Thanks for the reply. You may close this issue then.

**Comment by salarcode** [comment]
Closing as this is platform issue and can't do much about it
