### ISSUE TITLE
can't use proxy with password

### ISSUE THREAD

**Issue by skyfire000** [salarcode/SmartProxy#191]
How to use socks or HTTPS proxy with pasword?

I can't see there's any option for enter user and pass

**Comment by salarcode** [comment]
You can set them in Add Proxy popup
![image](https://user-images.githubusercontent.com/1272095/134768487-7041ca83-3d6b-4d7b-b88c-a100dc47b038.png)

**Comment by omaidb** [comment]
@salarcode SOCKS5 type proxy service Why can't I enter the account number and password
