### ISSUE TITLE
Proxy rule should not be ignored, I see the white rule of rules list is always preferred

### ISSUE THREAD

**Issue by yfdyh000** [salarcode/SmartProxy#192]
SmartProxy 0.9.10 on MS Edge 94.0.992.23.

Reproduce the steps:
1. Clean config. Adding the https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt to Rules Subscriptions.
2. Open the https://fonts.gstatic.com/ (or loading any of its page or resources). You can see the `gstatic.com` be proxed, and the `fonts.gstatic.com` in the white list from the rules sub, in the extension's popup. 
3. Try adding personal rules, like `MatchPatternHost	fonts.gstatic.com	*.fonts.gstatic.com/*` (By the way, this looks unforeseen automatic result) or `DomainSubdomain	fonts.gstatic.com	fonts.gstatic.com` to proxy server. Reload, the popup show it as a removable rule, but the extension does not lead the request to the proxy server.

**Comment by salarcode** [comment]
Yep was able to replicate, this is because `fonts.gstatic.com` is whitelisted by the subscription. And whitelists have higher priority than other rules and as soon as whitelist found, other rules are ignored.
This is an interesting case...

**Comment by silverzhaojr** [comment]
How about always preferring user's manual rule, like:

user's whitelist > user's proxylist > subscription's whitelist > subscription's proxylist

**Comment by salarcode** [comment]
Rules are combined together for efficient processing so your suggesion is not possible at the moment.
It makes sense though. There is a big change coming for this extension. I might include this in the list of things to do.

**Comment by RouRouX** [comment]
> How about always preferring user's manual rule, like:
> 
> user's whitelist > user's proxylist > subscription's whitelist > subscription's proxylist

I agree. I also found this problem recently because the white list contains translate.googleapis.com. If I want to use Google Translate now, I need to turn off gfwlist or turn on the global.

**Comment by salarcode** [comment]
Fixed in v1.0 by #213
