### ISSUE TITLE
Error loading extension on browser start

### ISSUE THREAD

**Issue by glitsj16** [salarcode/SmartProxy#196]
OS: Arch Linux
Firefox 94.0 / Firefox Nightly 95.0b3-1
SmartProxy 0.9.12

The Firefox browser console logs several instances of the below error on browser start. Not sure if this is a race condition or something else. In fact, as far as I can determine the extension is working fine, just wanted to report and get some opinions/info on what's happening exactly.

FWIW, I've tested this in a fresh Firefox profile (all settings as they come by default) with SmartProxy as the only installed extension.

Relevant `browser console` snippet:
```
addons.webextension.smartproxy@salarcode.com	ERROR	Loading extension 'smartproxy@salarcode.com': proxy-error before extension startup: Error: listener not re-registered Log.jsm:723
	append resource://gre/modules/Log.jsm:723
	log resource://gre/modules/Log.jsm:379
	error resource://gre/modules/Log.jsm:387
	_logMessage resource://gre/modules/Extension.jsm:556
	logError resource://gre/modules/Extension.jsm:552
	applyFilter resource://gre/modules/ProxyChannelFilter.jsm:406
	InterpretGeneratorResume self-hosted:1482
	AsyncFunctionThrow self-hosted:696
```

Thank you for this excellent extension, regards!

**Comment by salarcode** [comment]
weird, this doesn't seem to be extension related, rather browser related

**Comment by glitsj16** [comment]
> weird, this doesn't seem to be extension related, rather browser related

I just checked chromium and I don't see anything related to SmartProxy in that browser (same version, 0.9.12, using the exact same settings). So that looks to confirm your comment.
By now my Firefoxes got updated to 94.0.1/95.0b5-1 but that didn't change the above error, which still show up several times in the console. Weird indeed. Thanks for looking into this. I'll keep doing more extensive testing going over all my rules and will report back if I notice anything odd.

**Comment by salarcode** [comment]
this is pure guess, maybe the extension data got corrupted in local folders, for that remove the extension and then remove the extension folders from FF profile directory ( in both private and shared one, not sure how it is handled in Linux).

**Comment by glitsj16** [comment]
After uninstalling the extension, removing any leftover folders, and re-installing SmartProxy the error still remains. Was worth a shot though. For fun I tested [FoxyProxy Standard](https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/) which has a similar feature set. That too throws the error so I guess it's some kind of race condition or a bug in the Log.jsm Firefox code.

I re-tested _all_ my rules and can re-affirm that SmartProxy works as expected regardless of the above error. Feel free to close this issue, and thanks again for this excellent extension.
