### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by zhengli20** [salarcode/SmartProxy#197]
OS: macOS Big Sur 11.6
Chrome Version 95.0.4638.69 (Official Build) (x86_64)
SmartProxy 0.9.12

I followed the instructions in README to install on Chrome.
One extra step I had to do was to copy `src/pako.min.js` to `build/ui/js/`.

The extension is loaded but all buttons are not clickable.

And I checked the errors. There is an `Uncaught TypeError: Object(...) is not a function` message here:
```
static onDocumentReady(e) {
    Object(o.jQuery)(document).ready(e)
}
```

**Comment by salarcode** [comment]
Yeah, one step not mentioned is to unzip `src/ui/js/libs-unzip-before-build.zip` in the same folder; it may solve your problem.

**Comment by zhengli20** [comment]
@salarcode I did that and I don't need to copy the file `pako.min.js` any more.
But the problem still exists -- all buttons are not clickable and the error message is still the same.

**Comment by lengthmin** [comment]
unzip the libs-unzip-before-build.zip solve this problem, you need to rebuild the project, and webpack will copy them all to the dist folder.
