### ISSUE TITLE
the text of items in the list not aligned

### ISSUE THREAD

**Issue by kohchia** [salarcode/SmartProxy#198]
The size of some of the icons are different from others, which cause the text of the list items or the menu items not aligned.
![sp1](https://user-images.githubusercontent.com/6070257/142806335-0db4395d-0bb9-4d8a-b60b-778aef838c54.png)
![sp2](https://user-images.githubusercontent.com/6070257/142806337-f36f3e56-77f3-48df-9cab-156f045309b9.png)

**Comment by salarcode** [comment]
Fixed in v1.0 by #213
