### ISSUE TITLE
Import rules from other proxy extensions

### ISSUE THREAD

**Issue by salarcode** [salarcode/SmartProxy#2]
Namely:
AutoProxy
FoxyProxy
SwitchySharp/Omega

**Comment by johnmmcgee** [comment]
Hopefull this works for FoxyProxy soon!

**Comment by salarcode** [comment]
@johnmmcgee can you please upload a FoxyProxy backup here? that will help. thanks

**Comment by salarcode** [comment]
SwitchyOmega rules support is added in v0.9.9
