### ISSUE TITLE
Implement 'Bypass' list for "Always Enable" and "System Proxy"

### ISSUE THREAD

**Issue by Rictusempra** [salarcode/SmartProxy#20]
e.g. 192.168.1.1. And make such rules always effective.

**Comment by salarcode** [comment]
Can you be more specific? In which proxy mode you want changes?

**Comment by Rictusempra** [comment]
Of course disable the proxy (also disable IE proxy). When you use any proxy in any internal address, it will definitely timed out.

**Comment by salarcode** [comment]
You mean that when proxy mode is "Always Enable" you want to disable proxy for some addresses?

**Comment by Rictusempra** [comment]
Also in mode "System Proxy", as that case error sometimes.

**Comment by salarcode** [comment]
What you refer to is called 'bypass' list. That can be done.
This makes sense only for "Always Enable".
In "System Proxy" mode I don't see a reason for this feature, since all the configurations are done in the operation system.
