### ISSUE TITLE
Firefox Sync won't 'sync' when SmartProxy is enabled

### ISSUE THREAD

**Issue by samthelion17** [salarcode/SmartProxy#200]
I'm behind a corporate proxy server and I had no issues with this until a couple of months ago. First I was using FoxyProxy, and one day I realized that Firefox wasn't syncing so I started troubleshooting (Troubleshoot mode) and found out that when any proxy addon is enabled Sync fails. Now I moved to SmartProxy (love it! BTW) but things are pretty much the same, I even tried setting up a new profile with a different, new, Firefox Sync account and the outcome is the same. Is this a Firefox bug? Here's the [Sync log](https://pastebin.com/azRHQtdL)

**Comment by salarcode** [comment]
Thanks for the log, this can have very simple reason, the proxy server is also applied to Firefox sync servers and for some reason they are failing; either  DNS issues which I think it's your case or weak or expired ssl certificates and something like.

One way to fix this is whitelist the Firefox servers, maybe all *.mozilla.com and *.firefox.com

**Comment by samthelion17** [comment]
The thing is I think it might be a Firefox issue, because I've whitelisted those hosts you are suggesting me and even tried selecting "Direct (no proxy)" option and it always fail. My DNS is resolved by the parent proxy so, obviously that error in the log only indicates that when a proxy addon is enabled Sync tries to avoid it by going DIRECT. I was hoping someone could help me reproduce this bug to be sure before I submit it to Mozilla, and if I'm correct we can close this issue.

**Comment by salarcode** [comment]
Are you still having issues with Sync ?

**Comment by samthelion17** [comment]
Yep, I'm still enabling/disabling SmartProxy like crazy. I tried filing a bug report to mozilla but they "shaked the blame". I wish someone else could corroborate this issue...

Jan 6, 2022 4:23:40 AM Salar K ***@***.***>:
