### ISSUE TITLE
[HELP] how to add tab-rules for special hosts?

### ISSUE THREAD

**Issue by augustusy** [salarcode/SmartProxy#202]
I want to add host rules kind of like this:

`*.ABC1.com   *.ABC2.com   *.ABC3.com` 
`*.ABC.com   *.ABC.us   *.ABC.ru`

I've tried Host-wildcard `*.ABC*.com` and Url-regex `^http?://*\.ABC*\.com/*`  for first line, `*.ABC.*/*` and `^http?://*\.ABC.*/*` for second line, but it shows “invalid rule” and I can't add. The WIKI and MDN docs doesn't give enough examples.
What I have to do if I want add rules for hosts above?

**Comment by salarcode** [comment]
The rule that might help you is `..*.ABC.*.com` for domain `www.ABC.com` and for the `Host Regex` type.
Try using https://regex101.com/ to test/validate your regex.
