### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by stinger112** [salarcode/SmartProxy#204]
Extension doesn't work for me. Proxy itself works well.

Chrome
Version 96.0.4664.45 (Official Build) (64-bit)
SmartProxy v0.9.12 (October 12, 2021) - installed from Chrome Store
SOCKS5 Proxy (127.0.0.1, active)

Checked on https://whatismyipaddress.com/ with pattern `*.whatismyipaddress.com`.

Should I provide some more information for investigation? If so, where to find it?

**Comment by salarcode** [comment]
What mode you have put the extension?
Try different modes, Always enabled and SmartProxy modes.
