### ISSUE TITLE
Not work on edge

### ISSUE THREAD

**Issue by Mishasama** [salarcode/SmartProxy#205]
It looks weird. Looks like it can't save settings.
![image](https://user-images.githubusercontent.com/54498172/153202726-27bce2da-8c0f-40fb-bef7-9635aad02c35.png)

Microsoft Edge	98.0.1108.43
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43

**Comment by Mishasama** [comment]
After refreshing the settings page.
![image](https://user-images.githubusercontent.com/54498172/153203220-27c9ff20-7af0-42c6-9f9a-b83265afc699.png)

**Comment by Mishasama** [comment]
> Can you open the Console by pressing F12 and copy/past the logs and errors in the console here?

![image](https://user-images.githubusercontent.com/54498172/154862337-906e8ebe-8f49-4bc9-b7d0-c68bce8f05ea.png)

**Comment by salarcode** [comment]
this should be fixed in v1.0
