### ISSUE TITLE
Add support for restoring settings via URL

### ISSUE THREAD

**Issue by niclau** [salarcode/SmartProxy#206]
Just like Proxy SwitchyOmega, it has an option that allow users to restore add-on settings over URL.
Would you plan/like to add this option?
Thanks

**Comment by salarcode** [comment]
Can provide a use case for this? How this is useful?

**Comment by yfdyh000** [comment]
I guess this could be used in a quick guide for proxy software.

**Comment by niclau** [comment]
> Can provide a use case for this? How this is useful?

When I used Proxy swithyomega, I usually used this function to quickly restore settings on different browsers or PCs.
Occaionally those PCs are not owned by myself, I do not prefer to login accounts.

**Comment by salarcode** [comment]
There is backup/restore already, just have the file with you. This doesn't make lots of sense to me.
