### ISSUE TITLE
Bypass list gone when reopen the extension setting

### ISSUE THREAD

**Issue by samurai00** [salarcode/SmartProxy#209]
version: 0.9.10
browser: Edge 100.0.1185.29 (arm64)
os: macOS 12.3.1 (21E258)
cpu: Apple M1 Pro

1. save the bypass list
2. close SmartProxy Settings tab
3. reopen SmartProxy Settings
4. click Bypass List
5. it shows nothing. it's empty
6. the bypass list still works although it shows empty list. But i need to retype every item if I want to add one item.

<img width="774" alt="截屏2022-04-02 11 51 57" src="https://user-images.githubusercontent.com/685874/161365196-d83c457a-23e1-456a-8e50-f7a491433b3d.png">

<img width="616" alt="截屏2022-04-02 11 52 12" src="https://user-images.githubusercontent.com/685874/161365197-14a50359-4882-4a51-a28e-9c7a61e356bc.png">

**Comment by fyhzc** [comment]
在win10上的默认edge中也是这种情况。请作者更新一下。谢谢

**Comment by scalpelx** [comment]
I had same problem.
0.9.12, Chrome 105.0.5195.127, Windows 10 & 11.

**Comment by salarcode** [comment]
Bypass is replaced with rules in version 1.0 please try there and let me know if this is still an issue
