### ISSUE TITLE
Version 1.0 alpha 5 testers wanted 📣

### ISSUE THREAD

**Issue by salarcode** [salarcode/SmartProxy#213]
Hi all, I'm finishing off version V1 and in need of your eyes and brains 🧟🧠 for testing

Current Status: **Alpha version 5**

## Before start testing, here is how to prepare:

- Create a full back-up of your settings of your current SmartProxy
- Disable SmartProxy stable version v0.9.x
- [Download the Zips from here](https://github.com/salarcode/SmartProxy/releases/tag/v1.0.x-alpha) and Unzip it
- Install the new temporary version
  - [For Firefox use this guide](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox)
  - [For Chrome use this one](https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked)
  - [For Thunderbird use this one](https://arndissler.net/supercharge-your-thunderbird-extension-debugging/)
- You can restore old version backups now

### What to test
- Please test the following list of features
- Test whatever other features that are important to you
- Please report the bugs in this thread

## Reported Issues so far

- 🐛 ~~Smart proxy or Always enable does not work~~
- 🐛 ~~Light theme is not working~~
- 🐛 ~~Proxy-per-tab sometimes misses the requests as reported by Proxyable Resources~~

## Shipped Features

1. - [x]  Smart Profiles
4. - [x] Support for Firefox
3. - [x]  Profile for SmartProxy mode.
4. - [x]  Profile for Always Enabled mode.
5. - [x]  Profile for Ignore Failure Rules.
6. - [x]  Different Proxy Server per profile.
7. - [x]  Display the applied rule to the tab in tooltip.
8. - [x]  Theme support.
9. - [x]  Theme auto switch support
10. - [x]  Bootstrap 5 UI
11. - [x]  Seamless migration from v0.9.x
12. - [x]  Back-up/Restore
13. - [x]  Factory Reset option
14. - [x]  Support for Chrome
15. - [x]  Move the help center to [Wiki](https://github.com/salarcode/SmartProxy/wiki)
16. - [x]  Link to relevant help docs from pages
17. - [x] Support for Thunderbird 
18. - [x] Support for Google extensions Manifest V3
19. - [x] Forcing always enabled in Private Browsing #208 
20. - [x] Firefox for Android support
21. - [x] Firefox for Android installation guide docs

## Upcoming Features

1. - [ ]  Complete the help docs

**Comment by salarcode** [comment]
@ameaninglessname I appreciate your time for testing. Unzip step is added to the topic.
Yes, I've mentioned that backup and restore are not working properly.
Proxies are not being applied because perhaps you did a backup restore? Try fresh without restoring, that might be the reason that settings are messed up after a incomplete restore.

I've added your report to the topic, thanks.

**Comment by salarcode** [comment]
@ameaninglessname thanks a lot for testing. Recorded the issues.

**Comment by MarcoR83** [comment]
when is v1 coming out? any ETA?

**Comment by LakeishaKowalczyk** [comment]
> when is v1 coming out? any ETA?

+1

**Comment by LakeishaKowalczyk** [comment]
A gorgeous extension, regretted didn't meet her earlier

I have a few suggestions for proxy-per-tab
1. Allows non-global settings. We can set whether to activate this feature for each URL individually in the rules
2. Make the behavior of whitelisted and matched consistent. When a URL is set to not use proxy, the whole tab will not use proxy, just like when proxy is enabled
3. Allow exceptions. URLs have three states, matched or whitelisted or no rules. proxy-per-tab is only applied to URLs without rules, so that we can set exceptions by rules    
And, temporary rules or rule usage counts. Some sites may only be used once, but their rules will keep piling up in the settings

Feedback a possible bug
proxy-per-tab sometimes misses some URLs, maybe because of switching to another URL in the same tab
![image](https://user-images.githubusercontent.com/14090545/185757264-2f9edba1-33e0-4878-ab9a-a3641773c66e.png)

**Comment by salarcode** [comment]
> when is v1 coming out? any ETA?

If I have free time I'm trying to finish it by end of this year

**Comment by salarcode** [comment]
> I have a few suggestions for proxy-per-tab

Thanks for the suggestion, i'll see what I can do.

> Feedback a possible bug proxy-per-tab sometimes misses some URLs, maybe because of switching to another URL in the same tab ![image](https://user-images.githubusercontent.com/14090545/185757264-2f9edba1-33e0-4878-ab9a-a3641773c66e.png)

Will test this one for sure, thanks.

**Comment by salarcode** [comment]
> In the current, stable version, I was hoping to have a catch-all rule that goes to my default proxy and more specific rules for certain sites that go to other proxies. Is this possible in the alpha?

It is possible with `Always Enable` profile. In there the default behaviour is to apply default proxy and then you can define rules which themselves can have different proxy server.

**Comment by salarcode** [comment]
> In the current, stable version, I was hoping to have a catch-all rule that goes to my default proxy and more specific rules for certain sites that go to other proxies. Is this possible in the alpha?

It can be possible with `Always Enable` profile with a change. In there the default behaviour is to apply default proxy and then you can define rules which themselves can have different proxy server. 
So this is not possible at the moment but I might be able to make it work.

**Comment by salarcode** [comment]
Version Alpha 3 is out with these changes:

- Chrome support
- Proxy server per rule for Always enabled
- Issue fixes for Firefox and Chrome

**Comment by salarcode** [comment]
> In the current, stable version, I was hoping to have a catch-all rule that goes to my default proxy and more specific rules for certain sites that go to other proxies. Is this possible in the alpha?

This is now possible with Always Enabled profile. You can set a proxy server for each rule

**Comment by Hccake** [comment]
![image](https://user-images.githubusercontent.com/20430677/188604643-72f4483b-ee5d-46eb-aee7-838564d02e16.png)

When retrieving a proxyable resource, a warning pops up

**Comment by omnjpa27516** [comment]
Can you support the clash format? switchmeaga format is dead.

https://github.com/Loyalsoldier/clash-rules
https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt

**Comment by salarcode** [comment]
> ![image](https://user-images.githubusercontent.com/20430677/188604643-72f4483b-ee5d-46eb-aee7-838564d02e16.png)
> 
> When retrieving a proxyable resource, a warning pops up

I can't read Chinese, what does it say?
Did you have a clean installation? Maybe try again with Factory Reset option

**Comment by salarcode** [comment]
> Can you support the clash format? switchomega format is dead.
> 
> https://github.com/Loyalsoldier/clash-rules https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt

Please create a separate issue thread, based on upvotes and requests I might add it.

**Comment by omnjpa27516** [comment]
> > Can you support the clash format? switchomega format is dead.
> > https://github.com/Loyalsoldier/clash-rules https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
> 
> Please create a separate issue thread, based on upvotes and requests I might add it.

clash is the only one alive project, all the others are dead

**Comment by salarcode** [comment]
> > > Can you support the clash format? switchomega format is dead.
> > > https://github.com/Loyalsoldier/clash-rules https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
> > 
> > 
> > Please create a separate issue thread, based on upvotes and requests I might add it.
> 
> clash is the only one alive project, all the others are dead

You still need to create an issue here to track it, and you can get people to upvote it

**Comment by Hccake** [comment]
> > ![image](https://user-images.githubusercontent.com/20430677/188604643-72f4483b-ee5d-46eb-aee7-838564d02e16.png)
> > When retrieving a proxyable resource, a warning pops up
> 
> I can't read Chinese, what does it say? Did you have a clean installation? Maybe try again with Factory Reset option

It hasn't reproduced yet, but I found another problem.

When two agents are added, the default agent selects the first one, and when editing the information of the first agent, the default agent switches back to the secend one

**Comment by salarcode** [comment]
> Through no fault of SmartProxy, I've been having frequent HSTS errors ...
You can contact with me with same email as mentioned [in the source files](https://github.com/salarcode/SmartProxy/blob/master/src/lib/environment.ts), lets see what is root of these issues.
Possibly related #216

**Comment by salarcode** [comment]
> When two agents are added, the default agent selects the first one, and when editing the information of the first agent, the 
default agent switches back to the secend one

I'm sorry but I have a hard time understanding you.

**Comment by salarcode** [comment]
Version Alpha 4 is out with these changes:

- [x]  Support for Chrome Manifest V3 
- [x]  Support for Thunderbird
- [x]  Several issue fixes for Firefox and Chrome

**Comment by Hccake** [comment]
> > When two agents are added, the default agent selects the first one, and when editing the information of the first agent, the
> > default agent switches back to the secend one
> 
> I'm sorry but I am having a hard time understanding you.

![issue](https://user-images.githubusercontent.com/20430677/189883867-4da47c0b-f828-4ed9-bfdd-ee84aefb9dd0.gif)

Here is the screen recording, when editing the proxy information, the  default proxy is also changed

**Comment by salarcode** [comment]
> Here is the screen recording, when editing the proxy information, the default proxy is also changed
Thanks, I fixed this issue now

**Comment by salarcode** [comment]
Version Alpha 5 is out with these changes:

- [x]  Private Browsing Profile is added 
- [x]  Firefox for Android support is added with UI tweaks and fixes 
- [x]  Several issue fixes

📣 This is the last alpha. All planned features are implemented. Next phase of beta testing will start in a new thread.
Please test as much as you can. Thanks

**Comment by FSpark** [comment]
On first visit, as shown, the table header column is not the correct width.

![firefox_aYHDFI9qim](https://user-images.githubusercontent.com/20501721/192205718-f2c89ea5-bdcd-41aa-9eb0-77763d05dad9.png)

It will return to normal size after clicking.

Version:1.0 Alpha 5
Firefox 106

**Comment by salarcode** [comment]
> On first visit, as shown, the table header column is not the correct width.
> It will return to normal size after clicking.
> 
> Version:1.0 Alpha 5 Firefox 106

This issue got fixed yesterday, but thanks for reporting 👍

**Comment by nasaboy** [comment]
After adding a proxy server, but after saving it, it will show that the save is successful, and then click to expand the extension to view it, the proxy server inside is missing, and it has been tested on chrome and edge,both have the same problem.

**Comment by salarcode** [comment]
> After adding a proxy server, but after saving it, it will show that the save is successful, and then click to expand the extension to view it, the proxy server inside is missing, and it has been tested on chrome and edge,both have the same problem.

When there is one proxy server it will not show in the popup menu.

**Comment by salarcode** [comment]
This alpha testing thread is closes, lets continue in beta testing thread
#236
