### ISSUE TITLE
No "Enable proxy on" until a page is loaded or failed

### ISSUE THREAD

**Issue by dstd** [salarcode/SmartProxy#218]
If the resource is available only thru the proxy and I'll try to open it, it will take a lot of time until the request will fail by timeout. Before the failure, there's no "Enable proxy on" option at all (and obviously no "Failed Requests"), so I can't simply choose to proxify the request. The only option I see and use is to temporarily switch to "Always Enable", set the checkmark, and switch back to "Smart Proxy". But it's not quite convenient.

Could it be fixed, or it's API shortcoming?

Versions: v0.9.12, 1.0.0-alpha2
Browser: Firefox 101 @ macOS

**Comment by salarcode** [comment]
Extensions need context to work on, if page is not loaded there is no context.
If you want to add rules ahead of the time , you need to use Settings page.
