### ISSUE TITLE
DataTables error after backup and restore

### ISSUE THREAD

**Issue by paulraines68** [salarcode/SmartProxy#219]
I backed up full proxy/rules in Edge on one Win10 box and restored it in Edge on a second Win 10 box. Both are running 0.9.10.  On the second box when I access settings I now keep getting

DataTables warning: table id=grdRules - Requested unknown parameter 'hostName' for row 1, column 1. For more information about this error, please see http://datatables.net/tn/4

**Comment by salarcode** [comment]
It appears that some data is missing, can I have a working example of backup with this issue?

**Comment by paulraines68** [comment]
After restarting Edge the popup error has gone away.  If I restore from the backup again it comes back but goes away again after restarting Edge.  The rules seem to work just fine then.

If you want a copy of the backup JSON file, I would prefer to send it to you privately some way.  Though it may be rules like this one that is the source of the issue since hostname is null?

 {
      "autoGeneratePattern": true,
      "enabled": true,
      "hostName": null,
      "proxy": {
        "host": "localhost",
        "name": "Hound Proxy",
        "password": "",
        "port": "8080",
        "protocol": "HTTP",
        "proxyDNS": false,
        "username": ""
      },
      "ruleExact": "",
      "ruleId": 9765947901002,
      "ruleRegex": "192\\.168\\.[0-5]\\.[0-9][0-9]*",
      "ruleType": 2,
      "whiteList": false
    },

**Comment by salarcode** [comment]
This should be fixed in version 1.0 please try there and let me know if this is still an issue
