### ISSUE TITLE
Manifest V3

### ISSUE THREAD

**Issue by yfdyh000** [salarcode/SmartProxy#220]
Do you have a roadmap?

**Comment by salarcode** [comment]
First priority is to get the v1 out, I'm very these days. don't know when I will be able to.
Manifest is next

**Comment by salarcode** [comment]
Do you have any example a proxy extension that is implemented in MV3 ?

**Comment by salarcode** [comment]
If anyone interest I've got extension working in [Manifest v3 branch](https://github.com/salarcode/SmartProxy/tree/Manifest-v3)

**Comment by salarcode** [comment]
Fixed in v1.0 by #213

**Comment by CCCAUCHY** [comment]
Is the version on chromewebstore ManifestV3?

**Comment by salarcode** [comment]
> Is the version on chromewebstore ManifestV3?

yes
