### ISSUE TITLE
The IP address is incorrectly treated as a subdomain in the extension menu

### ISSUE THREAD

**Issue by tglsf** [salarcode/SmartProxy#224]
The IP address is incorrectly treated as a subdomain in the extension menu
When you access a site with an IP address, click on the extension icon and you will see that the IP address is incorrectly treated as a subdomain in the extension menu, like this:

Enable proxy on
0.1
0.0.1
127.0.0.1

**Comment by asypost** [comment]
Same issue here:
![图片](https://user-images.githubusercontent.com/1658213/187575949-26603640-9cf5-4bee-8ed8-7e1d444fa3ba.png)
