### ISSUE TITLE
Thunderbird support

### ISSUE THREAD

**Issue by erfanara** [salarcode/SmartProxy#226]
Thanks for this very nice extension, I use it every day.
It will be great if you add thunderbird support, since thunderbird lacks a good extension like SmartProxy.

**Comment by salarcode** [comment]
There is not Proxy or VPN extension for Thunderbird at the moment. 
Can you help me understand the use case for a proxy in a mail app?

**Comment by erfanara** [comment]
Thunderbird can be used as client for other things like feeds, chats (IRC, XMPP), ...
But I think the main use of proxy in Thunderbird is good for the feed aggregation. As a result, according to this usage of Thunderbird, there is a great need for something like SmartProxy.

I think Thunderbird is close enough to Firefox, I'll test this soon with `manifest-firefox.json`

**Comment by erfanara** [comment]
But it is completely true that by adding new features, new issues will appear soon :)
So not adding Thunderbird support is not a bad thing at all, but I guess adding it should be easy. (I'll inform you when I'm more sure)

**Comment by erfanara** [comment]
Firefox version just works like a charm.

**Comment by salarcode** [comment]
Thanks for the confirmation.
With minor changes I can push it the addon store
