### ISSUE TITLE
please add the pattern "forbidden proxy"

### ISSUE THREAD

**Issue by yushu280** [salarcode/SmartProxy#227]
As the title showed, I hope that the pattern "forbidden proxy" could be added. Because the pattern "direct link" cannot work well. Usually, when I need not  a proxy and choose the pattern "direct link", however, some websites cannot open and the extension "smart proxy" always ask me to choose a proxy or ignoration. It seemed that  pattern "direct link" is still controlled by the rule we set or it need a rule we must set. So what is the difference between it with the pattern "smart proxy"? It is very troublesome and irritating that disturb my browsing normal web pages. I prefer the autoproxy and autoproxy-ng ,which provided the pattern "forbidden proxy" that is very easy and convenient to use . So I wish the pattern "forbidden proxy" could be added.

**Comment by salarcode** [comment]
What you are asking is possible in version 1.0 which is in alpha version and is work in progress.
In v1.0 alpha you can select Always Enable and define rules to bypass proxy or even change proxy server

**Comment by yushu280** [comment]
Thanks. But my firefox block the installing of  alpha version. Look forward to the Official version 1.0. 
         As a user, I turn on the proxy only when I need it, which is not so frequently. But it is very troublesome to add a rule for every website or domain . My current solution is to disable  the extension usually and just enable it only when I need it, which is also awfully inconvenient。Considering the convenience of switch-pattern compared to the extension turn-off , I hope the version 1.0 could provide the pattern "forbidden proxy" or make the  pattern "direct link" really  keep a direct link .

**Comment by yushu280** [comment]
I have added a subscription. But the direct mode did not work well, saying nothing of the smart mode. During  daily browsing,  the direct mode also block some websites in China, requiring me to add a rule or ignore. Only when I close the extension can I get a normal browsing experience in such cases. Even the smart mode requires more frequently, seriously disturbing my browsing. Why direct mode still block websites ?  please make direct mode really keep  a complete direct link or add  the pattern "forbidden proxy".

**Comment by salarcode** [comment]
Direct mode really is a direct link. Unless you another proxy extension in your browser.
You need to use Smart Proxy mode and add rules from popup menu. Its very easy.

**Comment by salarcode** [comment]
Also I don't understand what you mean forbidden proxy!
