### ISSUE TITLE
VPN Extensions compatibility issue

### ISSUE THREAD

**Issue by ali-exacute** [salarcode/SmartProxy#229]
Hey, so i just recently switched to brave browser (chromium based) from firefox, this addon was working flawless on firefox
but here, on brave, it has compatibility issue with a lot of VPN Extensions

For example , if i wanna use Wroking VPN , i have to disable SmartProxy completely 

![image](https://user-images.githubusercontent.com/16070339/190682250-a9b66b9a-feaf-47be-a71a-683b335be7d5.png)

**Comment by salarcode** [comment]
This is a feature implemented by extensions to prevent competition, they detect other extensions and ask user to stop using them.
I could do the same easily but choose not to.
Sorry can't do anything about it, maybe use another vpn
