### ISSUE TITLE
Question: Does this proxy support pop3/smtp hosts in Thunderbird?

### ISSUE THREAD

**Issue by RuralHunter** [salarcode/SmartProxy#232]
That is, can I retrieve/send mails through a sock5 proxy configured in SmartProxy?

**Comment by RuralHunter** [comment]
Thanks but it does not help. Issue #226 just talks about the general usage in Thunderbird. I already installed SmartProxy in Thunderbird so that's not a problem for me. I wanted to ask the support of specific protocols such as pop3/smtp etc.

**Comment by salarcode** [comment]
@RuralHunter  yes you can.

I was able to only make Socks 5 to work and http proxies didn't work for me some reason in Thunderbird. Since you mentioned Socks 5 you should be good.

**Comment by RuralHunter** [comment]
hmm... I set up a socks5 proxy but I don't see any pop3 network traffic goes through my proxy server. What's wrong?

**Comment by salarcode** [comment]
> hmm... I set up a socks5 proxy but I don't see any pop3 network traffic goes through my proxy server. What's wrong?

Your proxy should support mail protocol eve though it says socks5

**Comment by RuralHunter** [comment]
Ok, I found the problem. I should have disabled the DNS option in my proxy server setting.
