### ISSUE TITLE
Rules can not use ipv6 host/url to bypass ipv6 host in lan

### ISSUE THREAD

**Issue by hingbong** [salarcode/SmartProxy#242]
Rules can not use ipv6 host/url to bypass ipv6 host in lan

version: [v1.0-beta.1](https://github.com/salarcode/SmartProxy/releases/tag/v1.0-beta.x)

**Comment by salarcode** [comment]
Please be specific, what type of rule to do what? also include steps to reproduce if there is any

**Comment by hingbong** [comment]
> Please be specific, what type of rule to do what? also include steps to reproduce if there is any

there are services like `http://[fe80::211:32ff:fe12:3456]:8080/` and `http://[fe80::211:32ff:fe12:1371]:6880/#!`, I want to bypass all request to `fe80::/8` subnets
for now, is there a way to do this?
thanks

**Comment by salarcode** [comment]
Sorry for the late reply,
In your example `[fe80::211:32ff:fe12:3456]:8080` is the `host`. Knowing this you can use `Host Regex` rule type to create a rule.
Use something like this `(\[fe80::).*`
