### ISSUE TITLE
[Bug] Multiple rule subscriptions will only take effect for one

### ISSUE THREAD

**Issue by FSpark** [salarcode/SmartProxy#243]
It seems that because this line will only overwrite the original rule set, is it intentional?

https://github.com/salarcode/SmartProxy/blob/d55fe7df5ed1f41b6edc4a8ae1d329a5af5ef369/src/core/ProfileOperations.ts#L160

**Comment by salarcode** [comment]
Thanks for the report that's indeed a bug, it is fixed now
