### ISSUE TITLE
Keyaboard shortcusts are missing in v1.0

### ISSUE THREAD

**Issue by Impeta** [salarcode/SmartProxy#248]
Title says it all. I can do ctrl + shift + period/comma just fine to switch among my proxies, but nothing happens when I try turning on and off Smart Proxy through shortcuts. Tried modifying to new shortcuts myself, still no luck. Has been happening ever since I upgraded off from 0.9xxx to 1.0.2 directly.

**Comment by salarcode** [comment]
Yep, these were forgotten in upgrade to v1 😅
