### ISSUE TITLE
the rules from the subscriptions did not work on the chrome extension

### ISSUE THREAD

**Issue by zhoufenfens** [salarcode/SmartProxy#249]
hi, thanks for your extension, it worked fine in the firefox and edge, but i found that the rules from the online subscription url did not work in the chrome. 
I downloaded the backup file from the edge extension and recover it from the chrome extension, it still did not worked properly.

**Comment by 288milan** [comment]
+1

**Comment by salarcode** [comment]
Fixed by https://github.com/salarcode/SmartProxy/commit/008ff02d94aa421fed30eb94c6486626bb65f042
Google Chrome Manifest v3 issues
