### ISSUE TITLE
Seems lost all my cloud rules after updated to 1.0.2

### ISSUE THREAD

**Issue by 404neko** [salarcode/SmartProxy#250]
All cloud rules lost, when proxy config is still there
I try to reinstall extension but not work

My chrome version is 109.0.5414.75

**Comment by kiryanov** [comment]
Same on Firefox 109. Not only I've lost all configured proxy list subscriptions, but SmartProxy refuses to work correctly even if I add them back.

**Comment by bhoppi** [comment]
> Same on Firefox 109. Not only I've lost all configured proxy list subscriptions, but SmartProxy refuses to work correctly even if I add them back.

Open the Proxies setting, manually save it again. It becomes available again, at least for me.

**Comment by kiryanov** [comment]
> > Same on Firefox 109. Not only I've lost all configured proxy list subscriptions, but SmartProxy refuses to work correctly even if I add them back.
> 
> Open the Proxies setting, manually save it again. It becomes available again, at least for me.

Nope, doesn't work. Manually added proxies do, but there's something very wrong with the ones from subscriptions. They are only partially shown in the interface and when you try to select one nothing happens.

**Comment by salarcode** [comment]
Backup your settings, do a factory reset from Backup tab and restore backup, see if this fixes it

**Comment by kiryanov** [comment]
> Backup your settings, do a factory reset from Backup tab and restore backup, see if this fixes it. Also is some rare cases browser restart could help.
> 
> Theses issues are because of new config storage format

Still no luck. Nothing works since 1.0.2. I've updated to 1.0.3, made a backup, did a factory reset, restarted the browser and imported back the settings. No matter what I do or select, SmartProxy always uses only the first proxy in the list. Keyboard shortcuts do not work either. Maybe it's specific to Firefox, but on Firefox proxy subscriptions are unusable.

**Comment by 404neko** [comment]
> Backup your settings, do a factory reset from Backup tab and restore backup, see if this fixes it. Also is some rare cases browser restart could help.
> 
> Theses issues are because of new config storage format

Same with [kiryanov](https://github.com/kiryanov)
I try give up build my own rules, turn to some public list, but subscription not work either

**Comment by salarcode** [comment]
I need more info, anyone having these issue could you you save logs and send them to my email `salarcode [at] gmail.com` ?
In Firefox go to `about:debugging` and do as these pictures:


![image](https://user-images.githubusercontent.com/1272095/215066847-11451292-d10f-41eb-bcb7-139b836f327a.png)


![image](https://user-images.githubusercontent.com/1272095/215066550-0700a53f-3e8d-477f-8e85-9ae14254a060.png)

**Comment by 0x7a7a** [comment]
I have the same problem.

**Plugin works fine in Chrome on Windows, but in MacOS there is the above problem.
The main problem is that the url that failed to load cannot be quickly added to the rules in MacOS(It is not actually added successfully after confirming the addition)**

Windows:
- Work: Yes
- Chrome Version: 109.0.5414.120
- Plugin Version: 1.0.3

MacOS:
- Work: No
- Chrome Version: 109.0.5414.119
- Plugin Version: 1.0.3

**Comment by salarcode** [comment]
@kiryanov , @404neko, @sunfos2019 and @0x7a7a 
Saying you have the same issue helps no one. I need to be able to reproduce the issue.
Please send the diagnostics details to my email `salarcode [at] gmail.com`

Follow the instructions here
https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics

**Comment by salarcode** [comment]
@favtony can you create a seperate issue please?

**Comment by salarcode** [comment]
There is not enough information here, this issue will not reopen. 
Please open new issue for each different issue
