### ISSUE TITLE
FF 109 Pinned tabs do not honor smart proxy on browser startup

### ISSUE THREAD

**Issue by ItsOnlyBinary** [salarcode/SmartProxy#253]
When firefox starts up with pinned tabs, the smart proxy is not used for those tabs until refresh. 

I assume the pinned tabs start loading before smart proxy is ready.

I thought I read something about 1.0 fixing my issue, but it does not appear to do so and I've been unable to find where I originally read the comment.

Is there a way to stop those connections from leaking? even if they fail on startup it would be better for me than the connection being attempted.

**Comment by salarcode** [comment]
I did test both Firefox and Chrome and in both cases pinned tabs loaded by calling SmartProxy.
Maybe you are mixing this with cached data on the first load?
In Chrome`s load, Chrome checks for cached data, if found that will be displayed, otherwise it will use cached proxy settings from previous session and load the content based on that. Then extension is loaded and new settings will be applied.
In Firefox load, it waits for extension to load then calls the extension methods and loads websites.

**Comment by ItsOnlyBinary** [comment]
I have smart proxy in smart proxy mode, with a rule for one site my isp blocks, when i load my browser with the pinned tabs I get secure connection failed for the tab with the rule, which is what happens when the connection tries to go through my isp (due to https and their this is blocked page only being http)

I do not have any browser syncing or other things that could slow down rule loading, they are just local rules.

could it be smart proxy is not loading the rules before the tab tries to load?

Thanks for great plugin and speedy response to issues :)

**Comment by salarcode** [comment]
I need more info, can you save logs and send them to my email `salarcode [at] gmail.com` ?
In Firefox go to `about:debugging` and do as these pictures:


![image](https://user-images.githubusercontent.com/1272095/215066847-11451292-d10f-41eb-bcb7-139b836f327a.png)


![image](https://user-images.githubusercontent.com/1272095/215066550-0700a53f-3e8d-477f-8e85-9ae14254a060.png)

**Comment by ItsOnlyBinary** [comment]
email sent, google may have put it into spam due to it coming from my own mailserver

**Comment by salarcode** [comment]
I've got the email, thank you, I have time today and tomorrow will debug the issue

**Comment by salarcode** [comment]
I don't believe this is fixable. There is about 250 milliseconds difference between load of extension and data storage being available to it.  Data storage is essential as all the extension settings are stored there.
Between this time browser makes some requests including the pin tabs which because extension is not initialized with data yet, they are treated as Direct call.

![image](https://user-images.githubusercontent.com/1272095/216767506-d97abd0b-df30-45a7-8fc2-9b08a6fe2d40.png)

**Comment by ItsOnlyBinary** [comment]
Personally i would prefer it to just deny/block all connections in that time frame, but as the config is not even available at that point, I could see how that should be an opt in feature.

Is there a way I can set firefox's proxy to localhost then have smart proxy disable it for direct connections?

**Comment by salarcode** [comment]
It makes sense to block the requests in this window as it could be security concern. But it might affect user experience for not blocked websites which is not pleasant. 

> Is there a way I can set firefox's proxy to localhost then have smart proxy disable it for direct connections?

I haven't tried this but it should work. Disable SmartProxy, set proxy in Firefox within its settings and Save. Enable SmartProxy again. This will be a fallback when there is no proxy extension registered

**Comment by ItsOnlyBinary** [comment]
After a quick test it seems to fallback to manual proxy configuration for direct connections when its set before smart proxy is enabled (enabling smart proxy does disable browser proxy settings), disabling smart proxy again then clears the manual proxy setting (back to no proxy and removes manual entries)

**Comment by salarcode** [comment]
I was able to force Firefox to use its default settings with an unusual way by throwing error at its face in the main method. It seems this stop further process and Firefox falls back to use browser settings.

With this found I'm going to make this change, in this time frame window that settings are not loaded, if `Run in Private Windows` is enabled for the extension, SmartProxy will set the fall back to be system proxy, if `Run in Private Windows` is not enabled then the browser proxy settings will be used.

**Comment by salarcode** [comment]
Verions 1.0.5 is released have a try

**Comment by ItsOnlyBinary** [comment]
As the time difference between the attempted request and config loading is only 250ms, would a better solution not be to return a promise in the [handleProxyRequest](https://github.com/salarcode/SmartProxy/blob/6f796edc1e5974589ab70147513740576e219d00/src/core/ProxyEngineFirefox.ts#L118) function which can then be resolved once the config is loaded, seems it would just need a promise for the settings so you could await

Documentation says this should be possible: 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest#parameters

Sorry I'm only suggesting this now, first chance I've had to clone the repo and dig through the source to try and figure out how it works (without any understanding of how browser plugins work)

**Comment by salarcode** [comment]
Promises I didn't thought of using them here.
It actually worked, I did a quick and dirty delay implementation and it works.

That was brilliant help.
I will implement a proper version of this probably next weekend.

**Comment by salarcode** [comment]
1.0.6 is release with fix regarding this new approach. Please have a look and let me know of any issues

**Comment by ItsOnlyBinary** [comment]
Working perfectly, greatly appreciated :)
