### ISSUE TITLE
Add proxy rule fail on load fail.

### ISSUE THREAD

**Issue by FantaZZ** [salarcode/SmartProxy#254]
This button can not work.

Chome,  Version: 1.0.3

<img width="458" alt="image" src="https://user-images.githubusercontent.com/5322276/215339283-0c9d4b4b-c88f-4283-b3b0-ea8c6cc8e22c.png">

**Comment by minghaoL1** [comment]
Same problem here. All proxy rules were lost after v1.0.3 and it was not able to add new rules on both Chrome and Edge.

**Comment by 288milan** [comment]
*1

**Comment by salarcode** [comment]
`Smart Proxy` or `Always Enabled` needs to be selected otherwise it won't work.
I'll make a change to UI to force this option.
