### ISSUE TITLE
Support for convenient rule addition via different proxy servers

### ISSUE THREAD

**Issue by sylph520** [salarcode/SmartProxy#255]
Hello here!   Suppose I have 2 proxy server , server1 and server2. And when I access website a.com, I want to proxy it via server1. But when I access b.com, I want to proxy it via server2 instead. It seems like there's always one active proxy server in the extension's logic, whenever i add a rule in the extension popup menu, the rule's proxy server targeted at the one and only active server. I have to enter the proxy rule editing page to manually change the targeted server I want to use, is there a easier way to add proxy rules in the extension popup menu?
Hope I made it clear the issue, lol.

**Comment by salarcode** [comment]
Doing anything to popup will add the complexity of the UI which is not the goal of popup.
Popup is just for convenience for everyday user. For advanced users, the settings page is the way to go.

Also active proxy is based on profiles, you can create new profiles and assign a different proxy server for each.
