### ISSUE TITLE
In the latest version v1.0.4.2, the * sign becomes %2A

### ISSUE THREAD

**Issue by sanek184** [salarcode/SmartProxy#256]
This was not the case in previous versions. Vivaldi browser
![screenshot 18376](https://user-images.githubusercontent.com/10418650/215684029-f20432e3-bd68-4807-98b9-280c4822bad7.jpg)

**Comment by salarcode** [comment]
You are entering * in the `Rule Source Domain` that is invalid and was never supported
![image](https://user-images.githubusercontent.com/1272095/215715450-1d25e5f3-83dd-4f0e-b97c-681be70d0e33.png)

**Comment by sanek184** [comment]
This is just an example, in any case the asterisk will change to %2A

**Comment by salarcode** [comment]
yes, * is invalid in Source Domain field. That is to be used in Match Pattern field

**Comment by sanek184** [comment]
![image](https://user-images.githubusercontent.com/10418650/215716456-e39801f0-2458-45c4-92ec-45eb827cd089.png)

**Comment by sanek184** [comment]
Understood. Sorry for disturbing
