### ISSUE TITLE
In Chrome updating a proxy server doesn't have affect on active proxy

### ISSUE THREAD

**Issue by VariatezzZ** [salarcode/SmartProxy#258]
I already have a proxy server config and use Always Enable Profile. but when i modify and save it. It will not apply. I must go to the Always Enable tab and save it. Then it will be really apply. So why not make them update together? Thx.

**Comment by salarcode** [comment]
Sorry I have a hard time understading your issue, please provide steps (1,2,..)  and screenshots if necessary

**Comment by salarcode** [comment]
Mentioning it is Google Chrome you're using would help.
Thanks for the report, the issue is identified and will be solved in the net release

**Comment by salarcode** [comment]
ISSUE_TEMPLATE wasn't there, I've added after this ticket 😁
