### ISSUE TITLE
Can't add rules from Failed Requests popup

### ISSUE THREAD

**Issue by Pakrohk** [salarcode/SmartProxy#260]
**Describe the bug**
I add the proxy profile in the server section but when I put the extension on the smart proxy, no website can be added to it.

**for reproduction**
Stages of behavior reproduction:
1. Go to the server section and add server.
2. Go to a website that you want to add to the list of rules.
3. Put the plugin on the smart proxy and try to add the website.
4. The desired profile is not supported.

**Expected Behavior**
I expected the website to be added to the list of rules.

**screen shot**
![image](https://user-images.githubusercontent.com/27810360/217237739-ad641599-96b4-4691-a5b7-053362727c99.png)

**SmartProxy (please complete the following information):**
   - Last version on firefox and chrome

**Browser (please complete the following information):**
- Firefox 109.0.1
- Brave 1.47.186 Chromium: 109.0.5414.119

**additional field**
The operating system in which these tests were performed is arch linux with plasma desktop.

**Comment by salarcode** [comment]
That is very weird. I'm going to need a backup of settings to identify the problem.

1- Get a backup and either attach it here or send via email to me salarcode [at] gmail.com
2- If you can please enable diagnostics and do the steps you've mentioned
[salarcode/SmartProxy/wiki/Enable-Diagnostics](https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics)

**Comment by Pakrohk** [comment]
[Log&Backup.tar.gz](https://github.com/salarcode/SmartProxy/files/10675375/Log.Backup.tar.gz)
Log (this log was created in the Firefox browser)

**Comment by BallanceHZ** [comment]
Same problem here.

**SmartProxy (please complete the following information):**

- Last version on firefox and chrome

**Browser (please complete the following information):**

- Chrome 109.0.5414.120

**Comment by MerrickZ** [comment]
same issue here, Firefox with latest plugin.
![图片](https://user-images.githubusercontent.com/1021332/217436643-b631e39a-0664-47f7-a0cb-61b8eb7f8137.png)
![图片](https://user-images.githubusercontent.com/1021332/217436679-ad817b1d-47ba-419e-9447-6ec5c30275eb.png)

**Comment by qq17854** [comment]
Same problem here.

SmartProxy (please complete the following information):
-  1.0.5

Browser (please complete the following information):
-  Chrome  109.0.5414.120

**Comment by salarcode** [comment]
@Pakrohk thanks for the backup file, I see your profile has issues. I will issue a fix with next release.

**Comment by salarcode** [comment]
1.0.6 is released including a fix for this bug
