### ISSUE TITLE
In Chrome keyboard shortcut for switching proxies should cycle

### ISSUE THREAD

**Issue by 1208041822** [salarcode/SmartProxy#264]
There is already a Switch to the next proxy server as the active proxy 
but can't switch back

**Comment by 1208041822** [comment]
or press again to cycle back to the first is the best

**Comment by salarcode** [comment]
Please follow issue formats:
https://github.com/salarcode/SmartProxy/issues/new/choose

**Comment by salarcode** [comment]
There is a limitation on number of shortcuts on google chrome. Can't do anything about it.

But pressing again to cycle back is a good idea.

**Comment by Nokic233** [comment]
> There is a limitation on number of shortcuts on google chrome. Can't do anything about it.谷歌浏览器上的快捷方式数量有限制。对此无能为力。
> 
> But pressing again to cycle back is a good idea.但再次按下循环返回是个好主意。

![chrome_IQMSSxXG8V](https://github.com/salarcode/SmartProxy/assets/74362493/e4cc4e42-f2c1-41ec-92a7-054f588e7d65)

I have an idea. Since there may be conflicts with shortcut keys, is it a better implementation to click on the image to cycle and switch? I'm not sure about the technical details here, it's just a simple idea~~~

**Comment by salarcode** [comment]
Related: #363

**Comment by Nokic233** [comment]
> > I have an idea. Since there may be conflicts with shortcut keys, is it a better implementation to click on the image to cycle and switch? I'm not sure about the technical details here, it's just a simple idea~~~
> 
> Click on icon opens the menu, can't do that

Yes, You're right. But if you delete default_popup from manifest.json, Adding some code to background.js should be able to implement it.

```js
chrome.action.onClicked.addListener((tab) => {
  // someCondition need to add a new setting
  if (someCondition) {
    chrome.action.setPopup({ tabId: tab.id, popup: 'popup.html' });
  } else {
    // Quick click switch
  }
});
```

Then add a check option in the right-click icon menu, This way, you can cancel the quick switch settings

```js
chrome.contextMenus.create({
      title: XXX,
      contexts: 'action',
      id: XXX,
      type:'checkbox',
      checked:true
    });
```
such as:
![image](https://github.com/salarcode/SmartProxy/assets/74362493/9c6acf96-5c0c-4030-ae4c-49b7b19cf3e2)

I have tried to look at the project code, but unfortunately, I have not developed a browser plugin. I searched for this information from Google and hope it can be helpful~

**Comment by salarcode** [comment]
This ticket is for enhancing the proxy cycle shortcuts behaviour, for action click events behaviour see https://github.com/salarcode/SmartProxy/issues/363

Also the problem is that I don't have much free time

**Comment by salarcode** [comment]
Shortcuts now will cycle at the end of the list. This is effective for both select next & select previous proxies.
This will be out with the next release
