### ISSUE TITLE
SmartProxy's proxy switching function will not work properly. (Firefox is in "system proxy" mode regardless of the mode selected)

### ISSUE THREAD

**Issue by Nyar233** [salarcode/SmartProxy#265]
**Describe the bug**
Once the windows proxy settings are set, SmartProxy's proxy switching function will not work properly. (Firefox is in "system proxy" mode regardless of the mode selected)

During the actual test, it was found that the proxy mode switch did not work.

It seems that unlike the behavior of previous versions, switching smartproxy's proxy mode does not change firefox's proxy settings (as shown in the GIF image below). If I remember correctly, older versions of smartproxy also changed firefox's settings here when changing its proxy mode. I'm not sure if this is related to the issue mentioned by this issus.

**To Reproduce**

1. Change the system proxy settings of windows
2. Trying to switch the proxy mode of SmartProxy.
3. By monitoring the proxy software, I found that all the domains are captured by the proxy server. (in other words, the rules of SmartProxy mode are not working correctly).
4. Checking the proxy settings of Firefox, found that it is not consistent with the previous version and did not change the proxy settings of Firefox (it has been kept in system proxy mode).

**Expected behavior**

Smartproxy should follow the proxy mode correctly on firefox. (even if the windows system proxy has been set)

**Screenshots**
<img width="874" alt="ApplicationFrameHost_xmT2uiAENQ" src="https://user-images.githubusercontent.com/30363595/219328045-d9ab350d-0097-45b9-bb42-32fe544a86c3.png">

![动画](https://user-images.githubusercontent.com/30363595/219315341-50a9ef9a-e1db-43ad-915c-9f7988aaead4.gif)

**SmartProxy (please complete the following information):**
 - Version [1.0.6]

**Browser (please complete the following information):**
 - Browser Firefox
 - Version 110.0 64 bit

**Additional context**

**Comment by Nyar233** [comment]
By the way, I tested version 1.0.6 of smartproxy on edge and it works fine. (by looking at the logs of the proxy server)

**Comment by elfl0rd** [comment]
Have this issue too, annoying :(

**Comment by salarcode** [comment]
Thanks for the detailed report, it is fixed now and will be in the next release
