### ISSUE TITLE
SmartProxy switches to 'Always Enable' profile on the startup of Firefox Nightly on Windows

### ISSUE THREAD

**Issue by KodamaSakuno** [salarcode/SmartProxy#266]
**Describe the bug**
In recent versions of Firefox Nightly on Windows, SmartProxy switches to 'Always Enable' profile on the startup regardless of the active profile before the last quit. However I test that it never happend on Firefox Nightly on macOS and Firefox 110.0 on Windows.

**To Reproduce**
1. Run Firefox Nightly on Windows
1. Switch to any profile except 'Always Enable'
1. Restart the browser

**Expected behavior**
SmartProxy should keep the active profile unchanged on the startup.

**Screenshots**

**SmartProxy (please complete the following information):**
 - Version 1.0.6

**Browser (please complete the following information):**
 - Firefox Nightly 112.0a1 on Windows

**Additional context**

**Comment by asmwarrior** [comment]
Hi, I see the same issue here, I'm not using the Firefox Nightly, I'm just using the official 110.0 version of Firefox.

**Comment by k9982874** [comment]
same issue on Chrome Version 110.0.5481.177 (Official Build) (x86_64)

**Comment by salarcode** [comment]
Before anything create a full backup. If you could shared it here or email it to me at `salarcode [at] gmail.com`  that would be great.

- This could be a corrupted profile issue which with backup I can tell.
- Check if you have sync enabled for active profile. `Enable syncing active profile` option. Try enable/disable it.
- Try disabling/enabling syncing completely.
- If none of above helped, please create a diagnostics log and send it to me. In this log, change active profile couple of times.
https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics

**Comment by asmwarrior** [comment]
Hi, @salarcode 

In my setting, the default syncing option is: "Enable settings syncing is **disabled**".

Now, I just check on the option "Enable settings syncing"(also the two sub-options are also enabled), and close the Firefox. And reopen Firefox again. Now I see the proxy policy is "Smart Proxy" now, which is the option I used before I close the Firefox.

So, it looks like enable the option "Enable settings syncing" will solve the issue.

**Comment by KodamaSakuno** [comment]
I spent time in debugging and found something strange. It's always "Always Enable" on the initialization, but the extension storage shows that active profile id is the correct one (Both storage tab and the api I call directly). I have disabled all syncing options. Here is a [screenshot](https://github.com/KodamaSakuno/kodamasakuno.github.io/blob/master/images/20230301_101449.png).

I hope that I can find something in my browser profile or try to make a sharable profile.

**Comment by salarcode** [comment]
@asmwarrior so there is an issue storing settings in your local.
* Can you open extension console and look for errors and warning? or just save it to a file and attach here.
* And can you 
	1. Create a backup
	2. Change the active profile 
	3. Create another backup
	4. Compare `activeProfileId` in both backup files, are they what you'd expect?

**Comment by asmwarrior** [comment]
> @asmwarrior so there is an issue storing settings in your local.
> 
>     * Can you open extension console and look for errors and warning? or just save it to a file and attach here.
> 

Hi, I'm not an export on the plugin design. Under Firefox, how can I enable the extension console?  Thanks.

**Comment by salarcode** [comment]
> Hi, I'm not an export on the plugin design. Under Firefox, how can I enable the extension console? Thanks.
Follow the steps in here to get the logs
https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics

**Comment by RouRouX** [comment]
> > Hi, I'm not an export on the plugin design. Under Firefox, how can I enable the extension console? Thanks.
> 
> Follow the steps in here to get the logs https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics

I encountered the same problem. I used this method to collect logs, but the contents of the log file are only null

**Comment by RouRouX** [comment]
I found that state switching is when switching browser tabs

**Comment by salarcode** [comment]
1.0.8 with a fix for this is released
