### ISSUE TITLE
Thunderbird proxy failure

### ISSUE THREAD

**Issue by StrollStars** [salarcode/SmartProxy#267]
**Describe the question**
I add Gmail, but it fails, no matter which mode.
I can't find the failed on the badge.
>Component returned failure code: 0x80550014
[nslMsglncomingServer.verifyLogon]

**Screenshots**
![服务器](https://user-images.githubusercontent.com/10942225/219943223-b9f68587-1302-4817-9e94-f64ba43a82bd.png)
![智能判断](https://user-images.githubusercontent.com/10942225/219943227-de90f979-8903-400a-ab27-e8794e3f4cd1.png)
![总是启用](https://user-images.githubusercontent.com/10942225/219943228-bdc144fe-adcb-418e-a563-555986813916.png)

**SmartProxy (please complete the following information):**
 - Version 1.0.6

**Browser (please complete the following information):**
 - Browser Thunderbird
 - Version 102.8.0 64bit

**Additional context**
If `Smart Proxy` mode doesn't work because the rules aren't right, why doesn't `Always Enable` mode work either? Does it have something to do with the Thunderbird's connection settings?

**Comment by salarcode** [comment]
I did a quick check, SmartProxy works but Thunderbird refuses to obey the rules. Will check more, thanks for the report.

**Comment by salarcode** [comment]
Seems like Thunderbird doesn't repect its own proxy settings in some cases.
Can you please confirm this by

- Disabling SmartProxy
- Use thunderbirds own proxy settings and confirm if it is working

**Comment by StrollStars** [comment]
@salarcode I uninstalled SmartProxy, and Thunderbird's connection is set to the socks host. same as SmartProxy, https://accounts.google.com/ can be opened, but SmartProxy cannot be opened in the always enabled.

BTW, if I enable SmartProxy, how should the Thunderbird connection be set up?

**Comment by salarcode** [comment]
In version 1.0.8 the diagnostics are enabled by default for Thunderbird, can you please attach the logs here 
Using this guide?
https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics

**Comment by StrollStars** [comment]
The configuration file I exported from SmartProxy of firefox is imported into SmartProxy of thunderbird, and it can be accessed normally on firefox, but not on thunderbird.
Considering privacy, the username and password in the file are replaced by user.
[smartproxy-diag-2023-03-24T04-44-41-653Z.zip](https://github.com/salarcode/SmartProxy/files/11058666/smartproxy-diag-2023-03-24T04-44-41-653Z.zip)

After the configuration file is imported from firefox to thunderbird, the rules of RegexHost is lost.

**Comment by salarcode** [comment]
Sorry for very late reply, checking your logs it seems rules are working correctly as expected.

But when I try it myself it seems it can read data from web which Http procotol is used but when actually connecting to servers which is IMAP is being used it doesn't work as it does not go through proxy api.

![image](https://github.com/salarcode/SmartProxy/assets/1272095/1b83ec87-3d0d-4263-ac93-ae9c45214f92)

**Comment by salarcode** [comment]
Does manually setting the proxy work for you from Thunderbird. SmartProxy should be disabled from Add-ons manager page.

**Comment by StrollStars** [comment]
@salarcode If a global proxy is set up, it can work normally, but if it's not global, there are still issues.

**Comment by salarcode** [comment]
Yeah this seems to be Thunderbird limitation on invoking extensions API.
We can't do anything about that

**Comment by StrollStars** [comment]
@salarcode Does Firefox have this problem?

**Comment by salarcode** [comment]
Firefox doesn't support IMAP protocol

**Comment by StrollStars** [comment]
@salarcode Thank you very much.

**Comment by StrollStars** [comment]
@physikerwelt Yes, if it is a PAC file, proxy can be used normally.

**Comment by salarcode** [comment]
Thunderbird doesn't use extension`s Proxy API to handle IMAP and SMTP connections.

For this reason I might discontinue Thunderbird support.

Will do another round of testing but I doubt that I find any workaround...

**Comment by StrollStars** [comment]
@salarcode Can you provide feedback to Mozilla so that Thunderbird can use extension's Proxy API to handle IMAP and SMTP connections?
