### ISSUE TITLE
Failed to save smart profile

### ISSUE THREAD

**Issue by Valen-H** [salarcode/SmartProxy#268]
When saving profiles i get this error "Failed to save smart profile. The message port closed before a response was received."

I think autosave should be implemented on-change because of dataloss.

**Comment by salarcode** [comment]
Please follow the issue format and create a new issue, there is not enough info
https://github.com/salarcode/SmartProxy/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Create a diagnostics if you can
https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics
