### ISSUE TITLE
SmartProxy's Default Proxy Server reverts after closing/reopening browser (possibly Firefox only)

### ISSUE THREAD

**Issue by God-damnit-all** [salarcode/SmartProxy#269]
Default Proxy Server reverts to my previously selected default after restarting the browser. I'm using the latest Firefox ESR.

---

1. Go to Settings
2. Go to Proxy Servers
3. Click on the Default Proxy Servers dropdown and select a server that wasn't selected before
4. Click "Save Changes"
	* Close and reopen Settings > Proxy Servers to make sure the change saved correctly
5. Restart the browser _(Firefox ESR for me)_
* _If the bug occurs for you like it did for me, the Default Proxy Server will now be the previous default._

---

**Expected behavior:**
The Default Proxy Server should not have reverted when the browser was restarted.

**SmartProxy:**
• Version 1.0.6

**Browser:**
• Firefox ESR x64
• 102.8.0esr

**Additional context**
If it matters, I'm using a non-default Firefox profile.

**Comment by salarcode** [comment]
It does not happen to me.

Do you have syncing enabled? try enabling/disabling it. Maybe Firefox service is being blocked by that proxy and sync fails.

**Comment by algoSupport** [comment]
I faced same issue as @ImportTaste.
browser: Google Chrome, OS: windows.
I have two Chrome profiles and one is working fine but other is acting like above.

**Comment by salarcode** [comment]
I need to be able to reproduce the issue,
Without logs I cannot do that

please create a diagnostics log and send it to me. In this log, change active profile couple of times.
https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics

**Comment by niclau** [comment]
The same issue here:
Edge 110.0.1587.63
Win10 21H2

**Comment by salarcode** [comment]
> The same issue here: Edge 110.0.1587.63 Win10 21H2

Not helpful!

**Comment by salarcode** [comment]
@ImportTaste @algoSupport @kylepwarren 
Are you using Proxy Servers subscription by any chance?

**Comment by salarcode** [comment]
1.0.8 with a fix for this is released
