### ISSUE TITLE
Message is not showing about Google Chrome not supporting authentication on SOCKS5

### ISSUE THREAD

**Issue by lazyfai** [salarcode/SmartProxy#272]
In Firefox SmartProxy, we can add a proxy server, for HTTP or SOCKS5, both working well.
But in Chrome version, if we add a SOCKS5 proxy, the login and password box not showing up, so I cannot enter user name and password for SOCKS proxy, is it intentional or a bug?

**Comment by salarcode** [comment]
Google Chrome doesn't support authentication on SOCKS5.
There was message about it, the bug is message is not showing anymore.
