### ISSUE TITLE
SmartProxy is automatically reconnecting recently

### ISSUE THREAD

**Issue by gnarfle** [salarcode/SmartProxy#276]
**Describe the bug**

I use SmartProxy so my personal machine can use my work machine to access VPN protected resources. I have configured it to not sync the connection because I want my personal machine to use SmartProxy and my work machine to not use it. This has worked great for a while. Recently, however, my work machine constantly connects to the proxy. If I click the extension to set SmartProxy to Direct (No Proxy) it will within seconds go back to the proxy.

**To Reproduce**
1. Disable Sync Settings in SmartProxy settings
2. Set SmartProxy to Disable (No Proxy)
3. Visit VPN protected resource
4. Wait some time (seconds to minutes) and Smart Proxy will re-enable itself

**Expected behavior**
SmartProxy should stay disabled

**Screenshots**
Sync settings are all disabled:

<img width="764" alt="Screenshot 2023-03-21 at 12 47 42 PM" src="https://user-images.githubusercontent.com/23989/226724333-dc687101-9b96-45a4-83db-8c7be11de8e5.png">

**SmartProxy (please complete the following information):**
 - Version 1.0.6

**Browser (please complete the following information):**
 - Brave 1.49.120

**Additional context**

**Comment by salarcode** [comment]
This is most likely is related to #266 .
A fix will come with 1.0.8 once gets approved by chrome web store. It is in waiting list.
Let me know if this version doesn't fix the issue
