### ISSUE TITLE
automatically switch to always enabled

### ISSUE THREAD

**Issue by RouRouX** [salarcode/SmartProxy#277]
**Describe the bug**
Updated to the latest version, there are still bugs. will automatically switch to always enabled.

**SmartProxy (please complete the following information):**
 - Version: 1.0.8.1

**Browser (please complete the following information):**
 - Chromium 102.0.5005.167

**Comment by salarcode** [comment]
Thanks for the report, the fix wasn't working on chrome. It will be fixed with 1.0.9
