### ISSUE TITLE
URL wildcard (match pattern)

### ISSUE THREAD

**Issue by qcybb** [salarcode/SmartProxy#278]
First of all, thank you for all your hard work on this extension.

I believe I have found a bug. It doesn't appear that "URL wildcard" feature is working correctly.

I'm trying to have the proxy to only enable for a particular URL (for example) :

Rule type : URL wildcard
Match pattern : *://*.whatsmyip.org/more-info-about-you/*
Action : Apply proxy
Proxy Server : MyServer

When I got to either https://www.whatsmyip.org/ or https://www.whatsmyip.org/more-info-about-you/, the proxy is not enabled.

If I change the match pattern to : *://*.whatsmyip.org/*

The proxy is enabled for the entire domain.

I would like the proxy to only be enabled for https://www.whatsmyip.org/more-info-about-you/

Is this a bug? or is this not possible to do?

**Comment by salarcode** [comment]
Sorry for the late reply, what you are missing here is the `www` and a star
use this pattern: `*://www.whatsmyip.org/more-info-about-you/*`

Here is a incomplete doc about the rules:
https://github.com/salarcode/SmartProxy/wiki/Proxy-Rules

**Comment by qcybb** [comment]
Sorry, it still does not work. The proxy will only kick in if I use `*://www.whatsmyip.org/*`

I tried with the rule source domain as `whatsmyip.org` and `www.whatsmyip.org`.

Does it work for you?

These are my settings :

![proxy](https://github.com/salarcode/SmartProxy/assets/16991734/3435c709-21c6-4adb-b739-5a357571c0c9)

**Comment by salarcode** [comment]
Checking the logs it seems sometimes the request to the domain without `www` so above rule won't work.
For both situations use `*://*.whatsmyip.org/more-info-about-you/*`

**Comment by qcybb** [comment]
Sorry, it's still not working. Feel free to test it yourself and see.

**Comment by salarcode** [comment]
I have tested these before posting, they are working for me.
Maybe the requests are cached for you. Try disabling Cache from developer tools/network tab

**Comment by salarcode** [comment]
> I failed to mention that I was using Microsoft Edge - which for me, it does not work in.

That is very important detail! I need to make the Issue pattern mandatory!

For Chromium browsers the full URL is not provided to proxies. That pattern won't work.

I'll make sure URL rule types are removed from list in Chromium browsers.
