### ISSUE TITLE
"Enable proxy per tab/origin" is not working properly on Firefox

### ISSUE THREAD

**Issue by chrisyue** [salarcode/SmartProxy#279]
**Describe the bug**
This setting is not working on my Firefox until I refresh the page manually. I need to refresh everytime to get it work.

**To Reproduce**
1. turn on smart profile, set "youtube.com" to use proxy.
2. go to youtube.com
3. proxy is working well on youtube.com, however the other resources hosted other than youtube.com (eg. googlevidoe.com) won't be loaded by proxy.
4. Refresh the page manually, every resource is loaded by proxy.
5. click the links(eg. a video link), the target page have the same problem until I refresh the page manually.

**Expected behavior**
According to the description of this setting, all resources on youtube.com should be loaded by proxy if I turn this setting on, no matter if the googlevideo.com is in the smart rules list.

**Screenshots**

**SmartProxy (please complete the following information):**
 - Version [e.g. 1.0.9]

**Browser (please complete the following information):**
 - Browser Firefox
 - Version 111.0.1

**Additional context**
No

**Comment by salarcode** [comment]
Thank you for your report, this was an important fix that I have missed.
This will be release with the next release.

**Comment by salarcode** [comment]
> @salarcode Still not working.

@E021ntox Open a ticket please otherwise your comment is ignored here
