### ISSUE TITLE
Display proxy details for active tab origin in toolbar button tooltip

### ISSUE THREAD

**Issue by yfdyh000** [salarcode/SmartProxy#28]
Display used proxy server / direct for the current page.

**Comment by salarcode** [comment]
This is not possible in tool-tip or popup, because several proxies maybe applied to the resource in the page.

**Comment by yfdyh000** [comment]
SwitchyOmega looks show the current page only.

**Comment by salarcode** [comment]
Currently in popup, you'll see a check mark beside domain name indicating that proxy is applied to current domain.

**Comment by yfdyh000** [comment]
Yes, but providing this information to tooltip may be more convenient, without find it in domains list, and see the used proxy and rule.
