### ISSUE TITLE
displaying a wrong url

### ISSUE THREAD

**Issue by zxsun2022** [salarcode/SmartProxy#280]
**Describe the bug**
in smart proxy mode, when visit any website, the plugin prompts me with a fixed domain name.
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/61731705/234284401-8a167ba4-78bd-444b-a216-0b91d2a0c3e7.png">

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/61731705/234284299-15a0ed98-366a-427d-ad8b-a02c25635e59.png">

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/61731705/234284232-d4b1a756-a366-4c8d-b0bc-5119122f8738.png">

**SmartProxy :**
 - Version: 1.0.9

**Browser (please complete the following information):**
 - Browser  Chrome
 - Version 112

**Comment by salarcode** [comment]
Sorry for the late reply, if this still is happening please attach your back up of settings for further investigation, thanks.
