### ISSUE TITLE
Sync will break up subscription auto refresh

### ISSUE THREAD

**Issue by wydy** [salarcode/SmartProxy#281]
**Describe the bug**
When sync is disabled, the auto refresh of subscription is working perfectly. But when the sync is enabled. The auto refresh of subscription will always fail.

**To Reproduce**
1. Enable sync
2. Enable auto refresh of the subscription
3. Save settings
4. Refresh the setting page
5. See error

**Screenshots**
![1](https://user-images.githubusercontent.com/1937986/235315786-0119e6cf-ebe7-4121-ab74-91aca0b38b30.gif)

**SmartProxy (please complete the following information):**
 - Version 1.0.9

**Browser (please complete the following information):**
 - Browser Chrome
 - Version 112.0.5615.138

**Comment by salarcode** [comment]
Thank you for the report, it will be fixed with the next release
