### ISSUE TITLE
[Feature] Add importing Swithy proxy list

### ISSUE THREAD

**Issue by zzzgit** [salarcode/SmartProxy#286]
Hi, I am from Swithy. 

I am using smartProxy now. The only problem for me is importing the Swithy proxy list. Currently, there's only importing support for Autoproxy.

**Comment by salarcode** [comment]
Where I really need help is to fix the parser if there is any issues. I have very little free time and can't go through specs and the existing parser to iron out the bugs.

So if you want to work on this please hold off until I finish the work on Import Rules popup and its back-end. When that is finished I would appreciate your help fixing the parser itself.

**Comment by salarcode** [comment]
To track the further work on SwitchyOmega rules I've created #345

**Comment by salarcode** [comment]
This option is added the popup.
@jackyzy823 the backend work of the importer is sorta finished but there seems to be bugs in the switchy rules parser. Feel free to jump in the code :)
