### ISSUE TITLE
add a 'default' rule 

### ISSUE THREAD

**Issue by zzzgit** [salarcode/SmartProxy#288]
<img width="868" alt="image" src="https://github.com/salarcode/SmartProxy/assets/1060733/70f402aa-92ec-4722-8469-1c814b51a8af">

Just as SwithyOmega did, we should add a category `default`. All the URLs dis-match the blacklist and the whitelist will fall into `default`.

**Comment by salarcode** [comment]
This does not work well with SmartProxy profile and Always Enabled profile as they have different behaviour and expectations.
Please let me what these profiles are missing that you think this feature is needed?
