### ISSUE TITLE
white list is unnecessary

### ISSUE THREAD

**Issue by zzzgit** [salarcode/SmartProxy#289]
<img width="491" alt="image" src="https://github.com/salarcode/SmartProxy/assets/1060733/913c13f0-4083-4f9e-91d5-fff4d38d633e">

`whitelist(no proxy)` in `action` is unnecessary. We can just leave all the rules `apply proxy`, and then let users choose `direct` in the `proxy server` list instead.

**Comment by salarcode** [comment]
Whitelist has higher priority to Proxy, it can be used to create exceptions to general rules.
Like apply proxy to all `*.google.com` except `img.google.com`
Here `img.google.com` will be a white list
