### ISSUE TITLE
Use Active Proxy is wrong after saving a rule.

### ISSUE THREAD

**Issue by zzzgit** [salarcode/SmartProxy#290]
<img width="491" alt="image" src="https://github.com/salarcode/SmartProxy/assets/1060733/430074ad-b04c-4034-9520-a012366db27e">

Add a rule which will `use profile proxy`. After saving it, I get this:

<img width="348" alt="image" src="https://github.com/salarcode/SmartProxy/assets/1060733/961aacf3-e9cd-4200-a66a-43c31f31bd56">

It becomes to `Use Active Proxy`.

**Comment by salarcode** [comment]
Thank you for the report, it will be fixed with the next release
