### ISSUE TITLE
[bug]unable to use shadowsocks in clash via smartproxy only on firefox

### ISSUE THREAD

**Issue by IcyCathedral** [salarcode/SmartProxy#292]
if the node is  vmess it would be ok, 
but if shadowsocks, only the fire fox will show:
PR_END_OF_FILE_ERROR

At first, all sites will show this with shadowsocks, but I just found that, in ver 1.1.1 only google.com will show.

but, with the system proxy(in smart proxy), it won't happen;

with edge chromium same settings(auto proxy), it won't happen.

 only firefox and in auto switch mode/global mode.

I reported this bug first to clash, but clash's author recommand me to issue here

======
proxy switchyomega dotsn't has this bug in auto switch mode on firefox ,but i don't like that extension

I have used smartproxy for many years and this is the bug recently I found(about half year)

**Comment by salarcode** [comment]
What you are describing is not something that an extension has control of. So this extension is just a switch to enable/disable proxy based on rules.

Please check this list
* Are you sure you have configured the proxy server correctly? Type of Socks4 or 5 ?
* Are there any other proxy extensions? Disable them all. Always keep one only.
* Have you tried disabling all proxy extensions and use browser settings directly?
* You have not mentioned what browser you have problem with? Firefox or Chrome?

**Comment by IcyCathedral** [comment]
> 

I am sure I configured the proxy correctly, Socks5. I have been used SmartProxy and Clash for many years. 
And the bug is still here. I use the same settings of smartproxy in both chrome and firefox. 
My firefox version is 16.0b2 (firefox developer edition) and Edge is the 114.0.1823.51 but I think the is not about the version because I am sure the latest version will still have the bug.
I have used proxy via extension for over 10 years and won't make such basic mistake I guess... so I think this is very likely a bug, not deadly, but wierd.


If you are interested in this bug, I can send you everything you need: my smartproxy settings.json; my clash subscriber link and my clash program folder; and firefox full package of my profile. This may be cost a lot of time( I need to seperate the cookies and the passwords) so make sure you really are interested in it....

For now I can just only avoid the shadowsocks nodes and using the Vmess node since I insist to use Smartproxy though it has such "bug".

**Comment by IcyCathedral** [comment]
> What you are describing is not something that an extension has control of. So this extension is just a switch to enable/disable proxy based on rules.
> 
> Please check this list
> 
>     * Are you sure you have configured the proxy server correctly? Type of Socks4 or 5 ?
> 
>     * Are there any other proxy extensions? Disable them all. Always keep one only.
> 
>     * Have you tried disabling all proxy extensions and use browser settings directly?
> 
>     * You have not mentioned what browser you have problem with? Firefox or Chrome?

I am not sure you can see my reply so I quote again

**Comment by salarcode** [comment]
These issues are very hard to identify. And SmartProxy does not manipulate connection and the issue you are describing seems to be cause of a interruption. 

Good thing you are a pro user, to investigate further:
1- I will need to have your backup. Either attach it here or send it via email salarcode@gmail.com
2- If you can please enable diagnostics and then try to reproduce the issue while diagnostics are enabled
[salarcode/SmartProxy/wiki/Enable-Diagnostics](https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics)

Let`s see if these will give me a clue

**Comment by IcyCathedral** [comment]
> These issues are very hard to identify. And SmartProxy does not manipulate connection and the issue you are describing seems to be cause of a interruption.
> 
> Good thing you are a pro user, to investigate further: 1- I will need to have your backup. Either attach it here or send it via email [salarcode@gmail.com](mailto:salarcode@gmail.com) 2- If you can please enable diagnostics and then try to reproduce the issue while diagnostics are enabled [salarcode/SmartProxy/wiki/Enable-Diagnostics](https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics)
> 
> Let`s see if these will give me a clue

sent, if you need any thing more reply here because i dont usually check mailbox

**Comment by salarcode** [comment]
Thank you I've got your email. I see no problem in your profile or in your logs. They all are fine.

>     * Have you tried disabling all proxy extensions and use browser settings directly?

I have disabled SmarProxy and using your Clash account I can see the Firefox itself has problem connecting to some servers.
Investigating more I can see that connection are dropped from Clash side. (Check Connections tab)

Now I think the problem is in your proxy server that somehow is not compatible with Firefox, this should not be possible somehow it is!
Maybe your ISP is intercepting?

To try the theory try all links in this search, alll of them had this issue using Firefox proxy settings
https://www.google.com/search?client=firefox-b-d&q=what+is+my+ip#ip=1

**Comment by salarcode** [comment]
> use the "system proxy" in smart proxy and now it works fine...
> 
> You may also try omegaSwitch which I mentioned works fine as well as expected on firefox so I don't think it is the compatibility issue
I does not work for me.
![image](https://github.com/salarcode/SmartProxy/assets/1272095/42e5531c-48a4-48f1-8475-ed32a06b4350)


### As I said before, disable SmartProxy and use Firefox settings and try again
As you can see in both cases, `Github.com` works but `whatismyipaddress.com` doesn't.

![image](https://github.com/salarcode/SmartProxy/assets/1272095/c9fcef88-8b97-421a-830d-d4501b7f0e0e)

**Comment by salarcode** [comment]
Also the ways SmartProxy and other extensions work is that they use browser extension apis and they do not modify the connection properties. So it won't be an issue from extension side
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy

**Comment by salarcode** [comment]
Same result with Chrome, `Github.com` works but `whatismyipaddress.com` doesn't.
![image](https://github.com/salarcode/SmartProxy/assets/1272095/24cf9432-d74c-4f9e-a54b-0efe0eb5f01f)
