### ISSUE TITLE
[Firefox] Selecting 'No Proxy' for "Pass through proxy" doesn't presist after saving

### ISSUE THREAD

**Issue by spphinslove** [salarcode/SmartProxy#294]
I try set “direct” subscribe rules,and save the setting.But it still using "proxy" to subscribe rules.

**Comment by salarcode** [comment]
I do not understand your issue.

Please do not remove the issue template while opening an issue:
https://github.com/salarcode/SmartProxy/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Please fill the form and explain a little more.

**Comment by salarcode** [comment]
Feel free to reopen with more details

**Comment by spphinslove** [comment]
![图片](https://github.com/salarcode/SmartProxy/assets/11383988/f6806625-888d-4d2a-ab00-eecde772ecc2)
I cant save this setting it to "direct",It always being via proxy
