### ISSUE TITLE
[Feature] Save changes alert

### ISSUE THREAD

**Issue by amirrh6** [salarcode/SmartProxy#296]
**Is your feature request related to a problem? Please describe.**
It happens frequently that I forget to press 'Save changes' and close settings tab, so every edit is missed.

**Describe the solution you'd like**
Show an alert once the user attempts to close the settings tab and ask the user if they want to save the changes.

**Describe alternatives you've considered**

**Additional context**

**Comment by salarcode** [comment]
This will be out with the next release
