### ISSUE TITLE
[Chrome] Sites using custom port are not detected by Smart rules.

### ISSUE THREAD

**Issue by Nyar233** [salarcode/SmartProxy#298]
**Describe the bug**

The plugin seems to be unable to proxy websites that use non-standard ports like https://example.com:2345

This issue is observed on Chrome browser

**To Reproduce**
Open the extension menu, then check the websites that need to be proxied under “Manually enable proxy”, then refresh

**Expected behavior**
The website should be proxied normally

**SmartProxy (please complete the following information):**
 - Version: 1.1.1

**Browser (please complete the following information):**
 - Browser Chrome
 - Version 114.0.5735.199

**Additional context**
If you use this extension on Firefox browser, it seems to work fine

**Comment by salarcode** [comment]
Thanks for the report, the issue is very bizarre and should not have happened or maybe it is happened after version 1.0

The issue is fixed and will be out with next release

**Comment by salarcode** [comment]
Yeah that`s a regression, will be fixed by 1.3.1
