### ISSUE TITLE
Rule Subscriptions should store loaded data in local storage

### ISSUE THREAD

**Issue by salarcode** [salarcode/SmartProxy#299]
Subscriptions (Rules and Proxy Servers) should store loaded data in local storage.
Last successful fetch should be stored locally so that in the next run or next browsers startup in case of any failures fetching subscription from network, they should use locally stored data.

**Comment by salarcode** [comment]
> Smart Proxy Subscriptions are completely broken in 1.2.0

Open a ticket please

**Comment by yhlnac** [comment]
the problem still exists.

**Comment by salarcode** [comment]
> the problem still exists.

What problem? This ticket is not for a problem! Open a new issue please
