### ISSUE TITLE
Detect network failures and suggest adding them

### ISSUE THREAD

**Issue by yfdyh000** [salarcode/SmartProxy#30]
SwitchyOmega have this feature. https://github.com/FelisCatus/SwitchyOmega/blob/master/omega-target-chromium-extension/src/module/web_request_monitor.coffee

Remind (list domains and allow to adding from popup) even record (adding later) or automatically try/adding.

**Comment by salarcode** [comment]
> Remind (list domains and allow to adding from popup) even record (adding later) or automatically try/adding.

Sorry, I can't understand what you mean

**Comment by yfdyh000** [comment]
Display a number for load failed resources, and the list of domain in popup for adding domain to rules.

Ideas: Allow logging (like log) the load failed domain / address in Settings, and automatically try to use one or more proxies to connect, remind or automatically adding if successful.

**Comment by salarcode** [comment]
> Display a number for load failed resources
This can be done but not this way.

> list of domain in popup for adding domain to rules.
There is 'Proxyable Resource' already

> Ideas: Allow logging (like log) the load failed domain / address in Settings, and automatically try to use one or more proxies to connect, remind or automatically adding if successful.
I fail to see any usecase for this.

**Comment by salarcode** [comment]
Ok this can be actually useful.
This is what I'm going to implement. This is for further reference.

* Detect network failures over urls that proxy is not applied to
* Display number of failures for each tab as a badge
* Display number of failures in popup
* Clicking the popup menu should display a UI with failed domains and a suggestion to add them to the rules

**Comment by salarcode** [comment]
> Ideas: Allow logging (like log) the load failed domain / address in Settings, and automatically try to use one or more proxies to connect, remind or automatically adding if successful.

This is far more complex scenario which should be implemented widely throughout the addon and requires a lot of time, which I don't have currently.
This should be implemented as "Proxy server quality check" which should work both on proxy servers and subscriptions.

**Comment by salarcode** [comment]
@yfdyh000 can you please test for bugs. Thanks 👍
