### ISSUE TITLE
Question on how to use the extension

### ISSUE THREAD

**Issue by sixgodfan** [salarcode/SmartProxy#300]
我一般用的Proxy SwitchyOmega的auto switch模式，不同的网站走不通的代理，现在换成SmartProxy
怎么界面中英文混合??？自动模式和智能方案没看懂
1.因 cf真人验证 无限循环，想把cf相关的连接直接访问或者其他代理端口访问，该怎么写，谢谢
比如连接(路径)  turnstile/v0/g/19b997cb/api.js?onload=或者/cdn-cgi/challenge-platform/h/g/flow/ov1
或者 /947fdac1-eaed-30b3-acd2-5365a9f5a7r3  等
2.怎么匹配 js/css/jpg等文件

谢谢

**Comment by salarcode** [comment]
In English please

**Comment by salarcode** [comment]
I don't understand your Chinese and English interface question.
Other answers:
In Firefox only add a rule with Rule Type `Url Regex` and regex values like this 
for `turnfile/v0/g/19b997cb/api.js?` enter `.*turnfile\/v0\/g\/19b997cb\/api.js?.*` 
for `/cdn-cgi/challenge-platform/h/g/flow/ov1` enter `.*cdn-cgi\/challenge-platform\/h\/g\/flow\/ov1.*`
and to match a file
for `.js` enter `.*\.js.*`
for `.jpg` enter `.*\.jpg.*`
