### ISSUE TITLE
[Feature] Add option to relad the page after enabling/disabling proxy on that page

### ISSUE THREAD

**Issue by minshifu** [salarcode/SmartProxy#301]
### Description

**Thank you for your great extension. 

Could auto reloading be realized after proxy is enabled on a certain webpage as shown by the picture below?

That would save a lot of trouble. 
 Best regards!

![image](https://github.com/salarcode/SmartProxy/assets/5119952/56235f0a-5fa3-41b9-b125-11e836fc11ed)

**Comment by salarcode** [comment]
Is the new title what you were asking?

**Comment by minshifu** [comment]
> Is the new title was what you were asking?

yes, exactly!
