### ISSUE TITLE
Chrome built-in translator isn't proxied

### ISSUE THREAD

**Issue by uenokatsura** [salarcode/SmartProxy#303]
### Description

I want to use Chrome built-in translator(not the extension one) to translate ruTracker for example.
But it seems that it leaks out.

### Steps to Reproduce

1. Go to any web that trigger the translator(ruTracker for example)
2. Right click - Translate to English
3. Proxifier indicates that it is leaked out

### Which browsers did you test this on?

Chrome

### Affected browser versions

Chrome 114.0.5735.199

### Affected SmartProxy versions

SmartProxy 1.1.1

### Screenshots of the problems or steps to reproduce

<img width="660" alt="image" src="https://github.com/salarcode/SmartProxy/assets/45501123/1ef0bc46-d1fb-4f5e-a393-0b7e5c0abf8d">

<img width="660" alt="image" src="https://github.com/salarcode/SmartProxy/assets/45501123/dfd31c7d-b2e4-4053-9c76-905e164facfe">

### Any additional context

<img width="330" alt="image" src="https://github.com/salarcode/SmartProxy/assets/45501123/53b29748-590a-4ad5-89fe-55585dbbc69d">

**Comment by salarcode** [comment]
Please provide more details.
* Is `translate.google.com` added to rules list? How? Using rules or a Subscription?
* What is proxy mode? Smart or Always enabled?

**Comment by uenokatsura** [comment]
> * Is `translate.google.com` added to rules list? How? Using rules or a Subscription?
> * What is proxy mode? Smart or Always enabled?

Using Always enabled with socks5 server, no bypass rule added. I believe it's not about the rule.

**Comment by salarcode** [comment]
Works for me just fine.

Please provide screenshot of your always enabled tab in SmartProxy settings.

**Comment by salarcode** [comment]
Also this is how chrome works, once it has made a connection it keeps it alive and it will not make new connections.
So if you change smartproxy mode it will not have any effect because Chrome is not making any new request.

Try restarting Chrome

**Comment by uenokatsura** [comment]
> Please provide screenshot of your always enabled tab in SmartProxy settings.

<img width="200" alt="image" src="https://github.com/salarcode/SmartProxy/assets/45501123/53b29748-590a-4ad5-89fe-55585dbbc69d">

> Also this is how chrome works, once it has made a connection it keeps it alive and it will not make new connections.
> So if you change smartproxy mode it will not have any effect because Chrome is not making any new connection.
>
> Try restarting Chrome

Same result after restart.
<img width="779" alt="image" src="https://github.com/salarcode/SmartProxy/assets/45501123/1d291bfb-4a10-4ec3-b229-8854dcabf9bf">

**Comment by salarcode** [comment]
Sorry it doen't happen to me and it works fine

**Comment by salarcode** [comment]
> Same result after restart. <img alt="image" width="779" src="https://user-images.githubusercontent.com/45501123/253571464-1d291bfb-4a10-4ec3-b229-8854dcabf9bf.png">

What is this program?

**Comment by uenokatsura** [comment]
> > Same result after restart. <img alt="image" width="779" src="https://user-images.githubusercontent.com/45501123/253571464-1d291bfb-4a10-4ec3-b229-8854dcabf9bf.png">
> 
> What is this program?

It's Proxifier, i use this to monitor the connection of chrome. you can use wireshark or other tools to check chrome's connection.
<img width="687" alt="image" src="https://github.com/salarcode/SmartProxy/assets/45501123/4c69865a-42a5-46b0-880b-3389641b976f">




> Sorry it doen't happen to me and it works fine

Google Translate works in "most" regions, but I'll need proxy to use it.
I'll get "The page couldn't be translated" while most users won't notice the leak out.

**Comment by salarcode** [comment]
Tried with Proxifier, works fine for me, also logs in Proxyable Resource show it also matches and works fine.
I can't put any more time on this, sorry
