### ISSUE TITLE
Rules from subscriptions won't match URL contains port

### ISSUE THREAD

**Issue by uenokatsura** [salarcode/SmartProxy#304]
### Description

```
[AutoProxy 0.1.0]

||douyu.com
```

won't match `wss://wsproxy.douyu.com:6675/`

### Steps to Reproduce

1. Subcribe to a ruleset.
2. Visit any site in the rule that will connect to non-standard port.
3. Check Proxyable Resources

### Which browsers did you test this on?

Chrome

### Affected browser versions

Chrome 114

### Affected SmartProxy versions

SmarProxy 1.2.0

### Any additional context

I find #238 in the issues.
The same thing happens to `DomainSubdomain` though I can change to `Host regex` there.
You can't do that with Rules Subscriptions

**Comment by salarcode** [comment]
>     2. Visit any site in the rule that will connect to non-standard port.

Can you provide such list here?

**Comment by uenokatsura** [comment]
> > ```
> > 2. Visit any site in the rule that will connect to non-standard port.
> > ```
> 
> Can you provide such list here?

[My Rule](https://raw.githubusercontent.com/uenokatsura/RuleSets/main/backCN.txt) and [an example douyu live streaming](https://douyu.com/74751)
Btw, SmartProxy will stop responding if too many connections on Proxyable Resources page.

**Comment by salarcode** [comment]
these rules you mean?
```
# Douyu 斗鱼
||douyu.com
||douyu.tv
||douyuscdn.com
||douyutv.com
||edgesrv.com
```
These are defined for default port 80 and 443 because port is not mentioned in them.
Custom ports must be defined in the rules otherwise default port will be used.

More info: https://github.com/gfwlist/gfwlist/wiki/Syntax

**Comment by salarcode** [comment]
>  Btw, SmartProxy will stop responding if too many requests on Proxyable Resources page.

That is because of the table plugin, nothing I can do about it, clean the table constantly to keep the flow going

**Comment by uenokatsura** [comment]
> > Btw, SmartProxy will stop responding if too many requests on Proxyable Resources page.
> 
> That is because of the table plugin, nothing I can do about it, clean the table constantly to keep the flow going

But both gfwlist syntax and ABP filters mentions no port, I believe **ALL Port** should be included even not announced with the single rule of `||douyu.com`.
And that's ABP, Adguard and SwitchyOmega's default behavior.

**Comment by salarcode** [comment]
The implementation of SwitchyOmega rules and AutoProxy rules are imported from their libraries so we have currently what they have ! Same logic

**Comment by uenokatsura** [comment]
> The implementation of SwitchyOmega rules and AutoProxy rules are imported from their libraries so we have currently what they have ! Same logic

With SwitchyOmega
<img width="800" alt="image" src="https://github.com/salarcode/SmartProxy/assets/45501123/8091a9c5-f839-444b-853b-48a1b02bccbc">

With SmarProxy
<img width="800" alt="image" src="https://github.com/salarcode/SmartProxy/assets/45501123/a3710e3c-a279-45b0-8671-d89c1409b250">

It doesn't seems we have the same behavior here.

**Comment by salarcode** [comment]
I have not written the rules parser code, so it must some misunderstanding between deployments!

SwitchyOmega is not working in Chrome anymore, are you using something custom ?

**Comment by uenokatsura** [comment]
> SwitchyOmega is not working in Chrome anymore, are you using something custom ?

No, I'm on official Google Chrome v114.0.5735.199.

**Comment by salarcode** [comment]
I found that this issue is caused by the fix for #298 I'm putting a release to patch this

**Comment by salarcode** [comment]
> > SwitchyOmega is not working in Chrome anymore, are you using something custom ?
> 
> No, I'm on official Google Chrome v114.0.5735.199.
I mean custom version of SwitchyOmega , it is not working for me

**Comment by uenokatsura** [comment]
> I mean are you using custom version of SwitchyOmega? it is not working for me

I think I'm using the [official](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif)  one.

**Comment by salarcode** [comment]
Verion 1.2.1 is release to Chrome, you can check if it is working fine.

**Comment by uenokatsura** [comment]
> Verion 1.2.1 is release to Chrome, you can check if it is working fine.

<img width="897" alt="image" src="https://github.com/salarcode/SmartProxy/assets/45501123/82a135ca-c55a-4159-946e-3723ac84b618">
😿

**Comment by salarcode** [comment]
The issues is fixed, but the fix is not applied to Proxyable Resources page, in Chrome browsers this page can't use same engine as the Proxy engine. Its browser limitations.
Use Firefox, SmartProxy has more features there and don't have these limitations.
