### ISSUE TITLE
May I ask how to set up proxy through IP segments

### ISSUE THREAD

**Issue by CangShanc** [salarcode/SmartProxy#306]
### Description

My English is not very good, I communicate with you through translation software

I want to set up a proxy through the IP segment range
For example, I want to access the IP address of 10.10.10.1/16 through a proxy
<img width="501" alt="image" src="https://github.com/salarcode/SmartProxy/assets/138548164/4a46ef74-3580-408d-8fc3-5ac798dcc53a">

May I know how to set proxy rules
Is there such a function? If not, would you consider supporting it

### Which browsers

Edge

### Browser versions

Edge  114.0.1823.82 (x86_64) 

### SmartProxy versions

SmartProxy 1.1.1

### Screenshots

<img width="501" alt="image" src="https://github.com/salarcode/SmartProxy/assets/138548164/a0c8e479-35a6-4ec4-b147-4d4e907647c6">

**Comment by salarcode** [comment]
For that select rule type as "Host Regex" and enter this Regex:
`10\.10\.10\.\d+`

**Comment by CangShanc** [comment]
Thank you.
Perfectly solved the problem
