### ISSUE TITLE
MatchPatternUrl and UrlRegex are not working correctly

### ISSUE THREAD

**Issue by sik0vny** [salarcode/SmartProxy#311]
### Description

**I want to catch all URLs with "MapServer" string in them.**

Here is an example: 
https://ags.cuzk.cz/arcgis1/rest/services/ZTM/MapServer/tile/4/2126/2012?blankTile=false

  Both MatchPatternUrl and RegexUrl are not catching it.
  I tried:
-   MatchPatternUrl: `*://*/*MapServer*`
-   MatchPatternUrl: `*://*MapServer*`
-   RegexUrl: `.*MapServer.*`

Or am I doing something wrong?

To be sure I have everything else configured correctly, I tried: MatchPatternUrl: `*://*/*` , and it catches all URLs correctly ( I can see them logged in my Proxy server)

### Steps to Reproduce

Set SmartProxy option with any of the above examples
Start your proxy server

Go to https://ags.cuzk.cz/geoprohlizec/
Start zooming into the map
Many urls https://ags.cuzk.cz/arcgis1/rest/services/ZTM/MapServer/tile* will be requested

None of them is being redirected to the proxy

### Which browsers did you test this on?

Firefox 114.0.2 (64-bit)

### Affected SmartProxy versions

1.3.0

**Comment by salarcode** [comment]
Sorry for the late reply, I tried this just now.
There is a bug in using lowercase urls for regex and patterns that causes this. It will be fixed with next version.

For now you can use the lowercase of your rules:

MatchPatternUrl: `*://*/*mapserver*`
RegexUrl: `.*mapserver.*`
