### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by DOXUU** [salarcode/SmartProxy#315]
### Description

这个怎么加入扩展里面啊  找不到CRX文件 改能ZIP 又加入不了 提示清单文件缺失或不可读取怎么解决

### Which browsers

Chrome

### Screenshots

![QQ截图20230821213501](https://github.com/salarcode/SmartProxy/assets/121757073/d5671d62-5c30-401d-8a84-e7610396a1db)

**Comment by salarcode** [comment]
Write tickets in English please?
