### ISSUE TITLE
I hope to support importing file rules for SwitchOmega

### ISSUE THREAD

**Issue by yanchenyuvip** [salarcode/SmartProxy#318]
### Description

I hope to support importing file rules for switchomega, migration is really troublesome.
The rules it exports are usually as follows：
*.qt.io +proxy
*.live.com +proxy
*.bing.* +proxy
*google* +proxy
*microsoft* +proxy
*.microsofttranslator.* +proxy
*.windows.* +proxy

### Is your feature request related to a problem? Please describe.

Directly importing rules will result in an error

### Describe alternatives you've considered

Formatting rules is also possible

**Comment by salarcode** [comment]
Duplicate of #318

**Comment by jackyzy823** [comment]
(Should be dulipcation of #286)
