### ISSUE TITLE
Improve jsGrid method of editing Proxy Server and Rule in grid.

### ISSUE THREAD

**Issue by yfdyh000** [salarcode/SmartProxy#32]
Edit proxy server without clocked the Update" button in Settings, click the save changes button, it says "Proxy servers saved successfully.".
This seems is not a good UI, the user should not need to confirm the editing, the user can Reject change as a decent revocation.

**Comment by salarcode** [comment]
Yes, that behaviour is because of jsGrid. I should look into it.

**Comment by salarcode** [comment]
Editing Proxy Server is done by modal now.
Only Rules remaines.
