### ISSUE TITLE
Release MV2 build for chromium forks

### ISSUE THREAD

**Issue by ImportTaste** [salarcode/SmartProxy#320]
### Description

Please include a `npm run build-ch-mv2` routine for your release builds. I ended up having to compile my own version for a Chromium fork I use that plans on keeping MV2 intact for the foreseeable future.

### Is your feature request related to a problem? Please describe.

I needed to add a proxy that required authentication and I learned that the version on the Chrome Web Store doesn't have it because MV3 intentionally excluded the necessary API (for some moronic reason).

**Comment by salarcode** [comment]
Would including a built zip file be enough for you?
