### ISSUE TITLE
Conflict with IDM Integration Module addon

### ISSUE THREAD

**Issue by roldymacdoggy** [salarcode/SmartProxy#321]
### Description

When i start the browser on "Always Enable" mode, the IDM Integration Module addon is corrupted. 

The temporary fix is switch to "System Proxy" or "No Proxy" mode and then switch back to "Always Enable" mode but eventually gets corrupted again

I have installed FoxyProxy before and didn't encounter this kind of bug

### Steps to Reproduce

![Untitled 2](https://github.com/salarcode/SmartProxy/assets/146641046/4485fef6-8a68-4227-b91e-1b6188aa3f99)

### Which browsers did you test this on?

Firefox

### Affected browser versions

Firefox 118

### Affected SmartProxy versions

SmartProxy 1.3.0

**Comment by salarcode** [comment]
Sorry for the late reply, perhaps you need to whitelist the IDM related websites, to do that just add websites to 'Always Enable' profile.
You need to find what those sites are and that might not be easy! Maybe just try with IDM main website as a general rule there.

**Comment by roldymacdoggy** [comment]
No problem. Thanks for replying. My bad that i found out that same happens with FoxyProxy. the bug could be on IDM's end or it happens with specific IDM version. 

But no sweat, this bug doesn't annoy me. 

Thanks you for this wonderful addon. Keep it up!

**Comment by salarcode** [comment]
Thanks for confirming, as I said above try whitelisting IDM domains and it might help
