### ISSUE TITLE
Export "proxyDNS"

### ISSUE THREAD

**Issue by MarisKori** [salarcode/SmartProxy#323]
### Description

"proxyDNS": true,
isn't imported from SmartProxy-FullBackup.json

### Steps to Reproduce

1. Use Firefox
2. Create a SOCKS5 proxy with proxyDNS=true, save config
3. Export config to a file
4. Reinstall SmartProxy
5. Import config from the file
6. See: proxyDNS==false

### Which browsers did you test this on?

Firefox

### Affected browser versions

Firefox 119.0.1 x64

### Affected SmartProxy versions

Version: 1.3.0

**Comment by salarcode** [comment]
Sorry can't reproduce, 
Open the backup file, you should find `"proxyDNS":true` in there where your proxy config is. This means it is as expected.
If it is `false` then change it to `true`

**Comment by salarcode** [comment]
Also you might have sync On before or after that can affect the results
