### ISSUE TITLE
Dropdown menu not working properly in Arc browser

### ISSUE THREAD

**Issue by Mrs4s** [salarcode/SmartProxy#324]
### Description

I've encountered an issue with the Smartproxy extension when using it in [Arc Browser](https://arc.net/). Arc Browser features a distinct design for its extensions dropdown menu, where each menu transforms into an independent window. However, this seems to be causing functionality problems with Smartproxy.

### Steps to Reproduce

1. Open Arc Browser and access the extensions dropdown menu.
2. Click on the Smartproxy extension to open its menu.
3. Try clicking any button within the Smartproxy menu.
4. Observe that the menu closes immediately, and the clicked feature does not work.

### Which browsers did you test this on?

Other (Chromium based)

### Affected browser versions

Arc browser 1.17.2

### Affected SmartProxy versions

SmartProxy 1.3.1

**Comment by salarcode** [comment]
Also a screenshot would help but this is not a released browser.
I'm sure this is browser issue and with little to no user base I'm not supporting it.
