### ISSUE TITLE
Abnormal CPU usage

### ISSUE THREAD

**Issue by zlkent** [salarcode/SmartProxy#325]
### Description

My CPU is AMD 5600X. Recently I found that Chrome CPU usage has been around 20%. After checking for a long time, I found that it was caused by this extension. After closing the extension, Chrome's CPU usage dropped to about 5%. Chrome permanent windows are around 50
The system is Win11 23H2

### Steps to Reproduce

none

### Which browsers did you test this on?

Chrome

### Affected browser versions

119.0.6045.200

### Affected SmartProxy versions

1.3.1

### Screenshots of the problems or steps to reproduce

![image](https://github.com/salarcode/SmartProxy/assets/8839493/0ef3c817-52b4-4e7c-92da-1a24fa076ff9)

**Comment by salarcode** [comment]
It is possible that you have lots of rules, try disabling your subscriptions that might help

**Comment by zlkent** [comment]
I subscribed to about 4,000 rules, and then I tried to change a subscription rule (more than 7,000 rules), and it became normal.
