### ISSUE TITLE
Extension don't work in Chrome v120

### ISSUE THREAD

**Issue by Set27** [salarcode/SmartProxy#326]
### Description

I use the extension on PC (chrome v120) and on Laptop (chrome v119).
On PC, extension don't work in any mode, on any server.

### Steps to Reproduce

Update to v120

### Which browsers did you test this on?

Chrome

### Affected browser versions

Chrome 120

### Affected SmartProxy versions

1.3.1

**Comment by salarcode** [comment]
Can't reproduce
