### ISSUE TITLE
Active Proxy is not updated after corresponding proxy gets updated

### ISSUE THREAD

**Issue by yfdyh000** [salarcode/SmartProxy#33]
Using a working proxy, update it to another setting, try visit and you will see the old settings is still exist until you switching the used proxy.

**Comment by salarcode** [comment]
Sorry, I really can't understand much

**Comment by yfdyh000** [comment]
Steps to reproduce:
1. New a proxy with 127.0.0.1:1080 and make sure it works.
2. Modify the proxy to 127.0.0.1:1081 (Incorrect or new settings).
3. Visit a page with this proxy, you will see still using 1080, until you switch to another proxy from popup and then switch back to this proxy.
