### ISSUE TITLE
Sometimes can not change SmartProxy Activation with mouse click but only restart browser

### ISSUE THREAD

**Issue by CCCAUCHY** [salarcode/SmartProxy#331]
### Description

Sometimes can not change SmartProxy Activation with mouse click but only restart browser.

### Steps to Reproduce

https://github.com/salarcode/SmartProxy/assets/55306290/a848c427-3547-4078-add3-993bef7152e5

### Which browsers did you test this on?

Other (Chromium based)

### Affected browser versions

[Version 117.0.5938.157 (Official Build) (64-bit)](https://github.com/Alex313031/Thorium-Win-AVX2/releases/download/M117.0.5938.157/thorium_AVX2_mini_installer.exe)

### Affected SmartProxy versions

1.3.1

**Comment by salarcode** [comment]
Use Firefox!
It is possible that Chrome pausing the SmartProxy engine (due it forced to be a service worker)
Let me if this keeps happening

**Comment by salarcode** [comment]
What is this thorium_AVX2_mini_installer you have linked?

**Comment by CCCAUCHY** [comment]
> Use Firefox! It is possible that Chrome pausing the SmartProxy engine (due it forced to be a service worker) Let me if this keeps happening

It's been long time. [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega) also has this bug so I try SmartProxy.

**Comment by CCCAUCHY** [comment]
> What is this thorium_AVX2_mini_installer you have linked?

[Thorium-Win-AVX2](https://github.com/Alex313031/Thorium-Win-AVX2)

**Comment by salarcode** [comment]
Please verify this with Chrome as Thorium-Win-AVX2 is not supported

**Comment by CCCAUCHY** [comment]
> Please verify this with Chrome as Thorium-Win-AVX2 is not supported

OK. I can't reproduce it on edge. I will report to the Thorium project.

**Comment by CCCAUCHY** [comment]
> Please verify this with Chrome as Thorium-Win-AVX2 is not supported

And yes, I can indeed reproduce it on chrome.

**Comment by salarcode** [comment]
I will try to reproduce in my end.

**Comment by CCCAUCHY** [comment]
FYI, this problem seems to almost disappear after I use the version downloaded from GitHub release

**Comment by salarcode** [comment]
Any update with new versions of browsers and the extension?
