### ISSUE TITLE
Settings are missing

### ISSUE THREAD

**Issue by berbunda** [salarcode/SmartProxy#332]
### Description

Proxy and smart proxy settings are missing

### Steps to Reproduce

1. I have added the settings of my proxy and smart proxy for websites
2. Saved it
3. I checked the proxy (everything worked)
4. The next time you start, the settings are gone

### Which browsers did you test this on?

Other (Chromium based)

### Affected browser versions

Vivaldi 6.5.3206.55

### Affected SmartProxy versions

SmartProxy 1.3.1

### Screenshots of the problems or steps to reproduce

![image](https://github.com/salarcode/SmartProxy/assets/67286954/4651a359-c2bb-4469-8b0a-0fe35cd29516)

**Comment by salarcode** [comment]
Please check disable sync options.
Also Vivaldi is not supported, please Chrome if you have still the problem
