### ISSUE TITLE
Matching all .onion URLs in Smart Rules

### ISSUE THREAD

**Issue by ImportTaste** [salarcode/SmartProxy#333]
### Description

I want to match all .onion URLs to my Tor proxy server (127.0.0.1 port 9050). This should be possible according to the wiki, which lists "Url regex" and "Url wildcard" as options:

![image](https://github.com/salarcode/SmartProxy/assets/53661808/844bb534-25a9-4398-b87c-e34e2d0dcf53)

However, I only have these options:

![image](https://github.com/salarcode/SmartProxy/assets/53661808/60d969c8-0efa-492d-b129-5db491c038c7)

What am I missing?

Also, I would like to point out I'm using the ManifestV2 version of this extension, which is compatible with my browser (Vivaldi).

### Which browsers

Other (Chromium based)

### Browser versions

Vivaldi 6.5.3206.57 (Stable channel) (64-bit) 

### SmartProxy versions

SmartProxy 1.3.1 (ManifestV2)

**Comment by salarcode** [comment]
Duplicate of #154
