### ISSUE TITLE
Hello, how to set user and password in Socks5 proxy server

### ISSUE THREAD

**Issue by Shuai-S** [salarcode/SmartProxy#334]
### Description

I need to set the user and password in the socks5 agent。
Please support me. Thank you.

**Comment by salarcode** [comment]
Hi
Sounds like you are using Chrome?
Username/password is not supported by Chrome
You can use Firefox for that which supports it

**Comment by Shuai-S** [comment]
I'm using edge, and I don't support it either?

**Comment by salarcode** [comment]
No it doesn't, Edge is using Chrome engine
Only Firefox supports it

**Comment by Shuai-S** [comment]
I understand. Thank you for your answer.
