### ISSUE TITLE
Implement SwitchyOmega features

### ISSUE THREAD

**Issue by adoin** [salarcode/SmartProxy#339]
### Description

SwitchyOmega will become unusable in June as manifest2 becomes outdated, but many people appreciate its interaction and logic. Is it possible to come as close as possible to SwitchyOmega? This question may not be very polite, but currently。But SmartProxy is the closest alternative to it.

**Comment by salarcode** [comment]
The UI, interaction and etc will not be the same.
But what features is important for you that you think are missing?
* List them like this please if any.

**Comment by tuwulin365** [comment]
Dynamically change the color of the icon, indicate that different agent servers or configurations.

**Comment by salarcode** [comment]
> Dynamically change the color of the icon

Not possible for chrome, but for Firefox it is being tracked here#127



> indicate that different agent servers or configurations.

More details please

**Comment by tuwulin365** [comment]
![image](https://github.com/salarcode/SmartProxy/assets/33275750/e3f80509-25cd-4bf8-bc12-1b0aed7ca3ac)
Like Switchyomega, inner circle indicator profile, outer circle indicator server

**Comment by salarcode** [comment]
> Like Switchyomega, inner circle indicator profile, outer circle indicator server

As I said that is tracked via #127

**Comment by salarcode** [comment]
anything else?

**Comment by adoin** [comment]
Can I implement

> anything else?

Maybe it's implement but it's hard for me to config a rule like *.abc.* sothat I can filter abc.net ，me.abc.com abc.else.
How can I do this? when I try to do that it says abc.* it seems to need a completely regex.

**Comment by salarcode** [comment]
> Maybe it's implement but it's hard for me to config a rule like _.abc._ sothat I can filter abc.net ，me.abc.com abc.else. How can I do this? when I try to do that it says abc.* it seems to need a completely regex.

Select "Host Regex" rule type and enter this as pattern
`.*\.?abc\..+`

**Comment by salarcode** [comment]
Seems there is no important feature is missing, 
If any please open another issue for that specific feature
