### ISSUE TITLE
Conflict with macOS screenshot keyboard shortcut

### ISSUE THREAD

**Issue by dem0ns** [salarcode/SmartProxy#342]
### Description

In macOS there have a shortcut to take a screenshot: Shift + Command + 3, which confilct with SmartProxy

### Steps to Reproduce

<img width="460" alt="image" src="https://github.com/salarcode/SmartProxy/assets/28812134/99a0a285-f5c0-4ce4-a2f6-9f7bf8390da4">
<img width="1000" alt="image" src="https://github.com/salarcode/SmartProxy/assets/28812134/101d7586-cd46-4cf0-831c-378bc174dcc8">

https://support.apple.com/en-us/102646

### Which browsers did you test this on?

Chrome

**Comment by salarcode** [comment]
Thanks for the report, that's unfortunate!
For now you can change the shortcut from here:
chrome://extensions/shortcuts

**Comment by salarcode** [comment]
Sorry to forgetting about this, will `Shift + Command + 0` be Ok in macOS world?

**Comment by dem0ns** [comment]
I think it's too far from 1 and 2, I use/recommend Shift + Command + A instead, of course the choice is yours

**Comment by salarcode** [comment]
How is `Shift + Command + A`  working for you? In Firefox that brings Addons page and in Chrome it brings search in tabs feature

**Comment by dem0ns** [comment]
Oh sorry, i didn't test it before set to `Shift + Command + A`

**Comment by salarcode** [comment]
Thanks for confirming then `Shift + Command + 0` it is

**Comment by dem0ns** [comment]
<img width="876" alt="image" src="https://github.com/salarcode/SmartProxy/assets/28812134/dd96f631-5685-4c4b-b42b-dadb5834b8de">
https://support.apple.com/en-us/102646

It's also a screenshot shortcut

**Comment by salarcode** [comment]
https://support.apple.com/en-au/HT201236
