### ISSUE TITLE
Unable to subscribe rule

### ISSUE THREAD

**Issue by Littleweisheit** [salarcode/SmartProxy#353]
### Description

Show “Unable to get proxy”
![图片](https://github.com/salarcode/SmartProxy/assets/11383988/74851054-08b2-44b7-96aa-007c5a88002b)

### Steps to Reproduce

just subscribe GFW list

### Which browsers did you test this on?

Firefox

### Affected browser versions

Firefox 123.0.1

### Affected SmartProxy versions

1.4

**Comment by Littleweisheit** [comment]
Also on firefox android

**Comment by salarcode** [comment]
Thanks a fix will be out with next release
