### ISSUE TITLE
Sometimes the icon disappears; the domain name is always "undefined"

### ISSUE THREAD

**Issue by Littleweisheit** [salarcode/SmartProxy#354]
### Description

![图片](https://github.com/salarcode/SmartProxy/assets/11383988/4f7da034-01dc-4232-9f84-4a6680a7b121)

### Steps to Reproduce

just open github. github is in GFW list

### Which browsers did you test this on?

Firefox

### Affected browser versions

Firefox 123.0.1

### Affected SmartProxy versions

1.4 and 1.4.1

**Comment by Littleweisheit** [comment]
if disable this option, The icon doesn't seem to disappear
![图片](https://github.com/salarcode/SmartProxy/assets/11383988/cb195b89-f03f-4145-bcb6-25e4b751989a)

**Comment by salarcode** [comment]
Thanks for the report a fix is released for this
