### ISSUE TITLE
chrome？

### ISSUE THREAD

**Issue by star2k** [salarcode/SmartProxy#356]
### Description

chrome商店不知道什么时候上架？手动导入，会显示2个吧？

### Is your feature request related to a problem? Please describe.

chrome商店不知道什么时候上架？手动导入，会显示2个吧？

### Which browsers

Chrome

**Comment by salarcode** [comment]
Please write in English

**Comment by salarcode** [comment]
Chrome extension validations takes longer usually a week

**Comment by star2k** [comment]
> Please write in English

Yes, the chrome store is so slow that it hasn't been updated yet.

**Comment by salarcode** [comment]
It takes 1~3 days but we had issue fixes and didn't release the ones with issues
