### ISSUE TITLE
Impossible to edit patterns in Proxy rules with Firefox 57

### ISSUE THREAD

**Issue by milipili** [salarcode/SmartProxy#36]
Hi,

It seems we can not edit patterns with the latest Firefox version :)

<img width="866" alt="bug-smart-proxy-patterns" src="https://user-images.githubusercontent.com/5516919/31362765-331e6fa4-ad95-11e7-863b-3c3198b9ed17.png">

**Comment by salarcode** [comment]
Patters are not editable. They are generated from the 'source'

**Comment by milipili** [comment]
Euh... Would not it be possible to simply specify a pattern directly instead of using some dark magic? How can I specify the port for example?

**Comment by salarcode** [comment]
You can still enter anything in the 'source' box (including port number e.g. example.com:8080), the pattern will be generated accordingly. This is good for most people.
