### ISSUE TITLE
Version 1.4.6 Bug: Subscriptions rules don't match subdomains [Firefox Only] 

### ISSUE THREAD

**Issue by lindongbin** [salarcode/SmartProxy#368]
### Description

Expected behaviour

all Subdomain not using proxy

Actual behaviour

all Subdomain using proxy

### Steps to Reproduce

add Subscriptions
[AutoProxy]
@@||ip138.com

working on version 1.4.5

### Which browsers did you test this on?

Firefox

### Affected SmartProxy versions

1.4.6

**Comment by salarcode** [comment]
Try version 1.4.6

**Comment by salarcode** [comment]
Try refresh/reload the subscription. Is it helping?

**Comment by lindongbin** [comment]
> Try refresh/reload the subscription. Is it helping?

I reinstall from https://github.com/salarcode/SmartProxy/releases/download/v1.4/SmartProxy-v1.4.6-firefox-unlisted.xpi
it works now

**Comment by salarcode** [comment]
That doesn't make sense. Your rules got refreshed by reinstalling so probably a single refresh of subscription should've been enough.

**Comment by lindongbin** [comment]
> That doesn't make sense. Your rules got refreshed by reinstalling so probably a single refresh of subscription should've been enough.

Because I deleted 1.4.6 and was going to reinstall it from AMO, I found that there was only version 1.3.0. I upgraded from 1.4.5 to 1.4.6 before the problem occurred. Then I overinstalled 1.4.5, and it also normal

**Comment by lindongbin** [comment]
AMO please re-list version 1.4.6, maybe it’s just a problem on my side

**Comment by salarcode** [comment]
1.4.6 It has other issues that i'm working on.

**Comment by salarcode** [comment]
Version 1.4.7 is released for Firefox
