### ISSUE TITLE
自动切换模式下无法使用代理

### ISSUE THREAD

**Issue by BenkyouMDKS** [salarcode/SmartProxy#370]
### Description

（始终开启模式下可以）

### Which browsers

Chrome

### Browser versions

122.0.6261.129

### SmartProxy versions

1.4.5

**Comment by salarcode** [comment]
Write in English please

**Comment by salarcode** [comment]
There is an update update your extension,

**Comment by BenkyouMDKS** [comment]
Proxy cannot be used in autoswitch mode

**Comment by BenkyouMDKS** [comment]
> There is an update update your extension,

Thanks, it works again.
