### ISSUE TITLE
Chrome doesn't work with proxy rule subscription, would like to add this feature, thanks a lot!

### ISSUE THREAD

**Issue by leeaikong** [salarcode/SmartProxy#371]
### Description

Chrome doesn't work with proxy rule subscription, would like to add this feature, thanks a lot!

### Which browsers

Chrome

### Browser versions

118

### SmartProxy versions

1.4.5.1

**Comment by leeaikong** [comment]
If you add a subscription rule, you can only choose direct connection, can you let the subscription rule use proxy mode?

**Comment by salarcode** [comment]
As the description says "Unfortunately this feature is not available in Chrome." meaning it is limited by Chrome.

I have a solution for you, use Firefox!
