### ISSUE TITLE
claude3 ，You can't access normally without "global mode",why？ 

### ISSUE THREAD

**Issue by star2k** [salarcode/SmartProxy#372]
### Description

Why can't I use "automatic switching" to access the claude3 webpage? I proxy all the relevant "proxy resources", but I still get an error when accessing through proxy. Prompt:
Unfortunately, Claude is only available in certain regions right now. Please contact support if you believe you are receiving this message in error.
Only when it is switched to "global on" can it be accessed normally. Why is this?
![PixPin_2024-03-18_06-34-28](https://github.com/salarcode/SmartProxy/assets/9582078/7f0bde03-5c01-4941-9a29-4fd16e802c79)
![22](https://github.com/salarcode/SmartProxy/assets/9582078/e84cba02-0e45-41a5-8b9c-355d62c32bec)

### Which browsers

Chrome  v122.0.6261.129

**Comment by salarcode** [comment]
That image you are showing is for Github, in the site`s open Proxyable Resources feature to show you the resources and you can figure out which one is leaking.
Or use Firefox to apply proxy to whole tab!
