### ISSUE TITLE
'Smart Proxy' activation not work in new version

### ISSUE THREAD

**Issue by UnknowViewer** [salarcode/SmartProxy#373]
### Description

**Web browser**: Chromium Version 121.0.6133.0 (Developer Build) (x86_64)
**OS**: macOS 12.6
**Chipset**: Intel

Everything works good in previous version, after extension auto updated to the new version (I notice the icon has been changed), the '**Smart Proxy**' activation cannot work, but '**Always Enable**' works good.

The new version in Firefox also works good, and this issue occurred on both Intel macOS and M1 Pro macOS, did I miss something to update?

### Steps to Reproduce

Please refer to the description.

### Which browsers did you test this on?

Other (Chromium based)

### Affected browser versions

Chromium 121.0.6133.0

### Affected SmartProxy versions

1.4.5

### Screenshots of the problems or steps to reproduce

![smartproxy](https://github.com/salarcode/SmartProxy/assets/14183726/c5b5e274-5fab-465f-9442-834fd1e2d2e9)
![alwaysenable](https://github.com/salarcode/SmartProxy/assets/14183726/00ac8874-d99e-4ea2-a31c-a200a33e3c9f)

**Comment by salarcode** [comment]
You are using old version, update your extension, the last version is 1.4.5.1

**Comment by UnknowViewer** [comment]
> You are using old version, update your extension, the last version is 1.4.5.1

Thanks! It works again after the version update
