### ISSUE TITLE
How do I delete smart profile?

### ISSUE THREAD

**Issue by MiracleLau** [salarcode/SmartProxy#374]
### Description

I created a new smart profile and now I want to delete it, but I can't find the delete button. How should I proceed? 

### Which browsers

Firefox

**Comment by salarcode** [comment]
Delete button is at the bottom profile page:

![image](https://github.com/salarcode/SmartProxy/assets/1272095/3a64846e-adfd-4158-9ac2-e18a4ce3efcb)

**Comment by salarcode** [comment]
Only user defined profiles can be deleted
