### ISSUE TITLE
The plugin on Microsoft Edge Addons still not updated

### ISSUE THREAD

**Issue by JedSunCN** [salarcode/SmartProxy#375]
### Description

The plugin on Microsoft Edge Addons still hasn't been updated until now, when will it be available/not available?

### Which browsers

Edge

### SmartProxy versions

1.3.1

### Screenshots

https://microsoftedge.microsoft.com/addons/detail/smartproxy/canbjhbbhfggbdfgpddpnckdjgfcbnpb

**Comment by salarcode** [comment]
It is in review since 4 days ago. It is up to them to review.
