### ISSUE TITLE
Ignore failure detection check boxes are missing

### ISSUE THREAD

**Issue by Littleweisheit** [salarcode/SmartProxy#377]
### Description

the checkbox on left was missing.
Maybe the new firefox cause this problem.
![图片](https://github.com/salarcode/SmartProxy/assets/11383988/12d90fb9-d0cf-4bae-93dd-a733d13fed96)

### Steps to Reproduce

just open a web.

### Which browsers did you test this on?

Firefox

### Affected browser versions

firefox 124

### Affected SmartProxy versions

1.4.7

**Comment by salarcode** [comment]
Yes I can see they are visible in Firefox v120

**Comment by Littleweisheit** [comment]
> Yes I can see they are visible in Firefox v120

Do we have to wait for the plug-in to adapt to Firefox 124 now? Or is this a Firefox bug?

**Comment by salarcode** [comment]
Clicking on the url text will select the item then you can proceed to add them to ignore list

**Comment by Littleweisheit** [comment]
> Clicking on the url text will select the item then you can proceed to add them to ignore list This should help you for now

Why not fix this BUG？

**Comment by Littleweisheit** [comment]
> The fix will be our with the next release

It seems you're very busy.
