### ISSUE TITLE
When opening link that uses proxy from bookmarks - proxy ignored

### ISSUE THREAD

**Issue by Leviann** [salarcode/SmartProxy#378]
### Description

I have put some website under proxy using your extension. I use "Smart Proxy" option.
I have this website in bookmarks tab. When I open it from bookmarks tab - proxy is ignored and I access this website directly.
If I open website by writing it in URL bar - it opens under proxy with no issues.

### Steps to Reproduce

1. Add specific website (torrents, not sure that I'm allowed to paste it here) to use under proxy
2. Add the same website to bookmarks bar
3. Open website from bookmarks bar

### Which browsers did you test this on?

Chrome

### Affected browser versions

Version 123.0.6312.87 (Official Build) (arm64)

### Affected SmartProxy versions

1.4.7

**Comment by salarcode** [comment]
In my testing that only happens when you have just added the rule for the page/domain.
After restarting the browser it works for me with no issues!
