### ISSUE TITLE
How to set proxy rules to exclude IP segments?

### ISSUE THREAD

**Issue by cloudkylin** [salarcode/SmartProxy#379]
### Description

I want to set proxy rules to exclude some LAN IPs to ensure that certain LAN services can be accessed normally when it is in "always enable" mode, such as 172.16.0.0/16, 192.168.0.0/24 or [:: 1].
But I tried using some general rules and it didn't work.
I found this document: [Proxy Rules](https://github.com/salarcode/SmartProxy/wiki/Proxy-Rules), but it has too many "TBC..." and I can't get useful information from it.
Can you provide me some examples to solve this problem? Thanks.

### Which browsers

Chrome, Firefox, Edge

**Comment by crypticviper** [comment]
I too am struggling with the same. It doesn't seem to be possible with URL or Host based regex. It either says host is invalid or host doesn't match the regex. Any info on this would be very helpful.

**Comment by salarcode** [comment]
You can use Host Regex for IP addresses it can handle all sort of situations.
For example to block IP ranges like 10.0.0.* use this regex:
`10\.0\.0\..+`
For 172.16.0.0 use `172\.16\..+\..+`

You can test your RegEx here: https://regex101.com/

**Comment by karinaardos** [comment]
RegexUrl | 192.168.0.0 | 192.168.0./*

I found this option for myself
