### ISSUE TITLE
Customized icons in toolbar

### ISSUE THREAD

**Issue by thefujunjie** [salarcode/SmartProxy#380]
### Description

![image](https://github.com/salarcode/SmartProxy/assets/32631087/99954d1f-e827-4d7d-bbc7-8bd567e0fd63)
It would be great if these icons can be customized.

**Comment by salarcode** [comment]
The icons are newly designed and further customization is not planned

**Comment by chopin1998** [comment]
true, the current icons don't provide very good visual hints.
