### ISSUE TITLE
chrome's http proxy supports password authentication

### ISSUE THREAD

**Issue by coulsontl** [salarcode/SmartProxy#384]
### Description

Chrome's http proxy supports password authentication, only Socks5 does not support password authentication; could you support password authentication for HTTP proxy?

### Steps to Reproduce

<img width="488" alt="image" src="https://github.com/salarcode/SmartProxy/assets/149155411/bcc5037e-2fad-41c2-bfce-ff5727d5b548">

### Which browsers did you test this on?

Chrome

**Comment by mdsnalw** [comment]
I am still encountering the same issue. Does this mean that the Proxy Plugin for Chrome is no longer available?

**Comment by salarcode** [comment]
Thanks for heads up, passwords supported is added and will be released with a next release
