### ISSUE TITLE
Wish it was possible to remove useless buttons

### ISSUE THREAD

**Issue by NianBroken** [salarcode/SmartProxy#385]
### Description

I would like to remove the buttons “System proxies”, “Proxy servers for this program”, “Manually skip domains”, “Proxy-able resources “ buttons.

![image](https://github.com/salarcode/SmartProxy/assets/57057288/046f1f4e-86af-4a04-89f1-5fdebf3ecf4b)

**Comment by salarcode** [comment]
They might be useless for you but not for others they serve a purpose
