### ISSUE TITLE
Error when add multiple rules: Host null invalid

### ISSUE THREAD

**Issue by wildtang** [salarcode/SmartProxy#397]
### Description

In auto switch try to add multiple rules for white list, shows error: Host null invalid
![图片](https://github.com/user-attachments/assets/84c54b93-40a8-45b1-b283-143715a938ab)

### Steps to Reproduce

In auto switch try to add multiple rules for white list.
1. add rules below for white list
```
localhost
127.0.0.1
localaddress
.localdomain.com
192.168.*.*
```

### Which browsers did you test this on?

Firefox

### Affected browser versions

129.0.2 (64 bit)

### Affected SmartProxy versions

1.5

**Comment by salarcode** [comment]
The `192.168.*.*` is not valid, in Chrome this works because browser formats it like `192.168.%2A.%2A` but not in Firefox.
I've updated the message to display correct error, thanks
