### ISSUE TITLE
Firefox: PopUp Width bug in Overflow menu

### ISSUE THREAD

**Issue by Acid-Crash** [salarcode/SmartProxy#40]
When placing SmartProxy icon inside Overflow menu ant then opening it a graphical bug appears.
![smartproxy](https://user-images.githubusercontent.com/32600318/32918190-3d13a314-cb2a-11e7-982a-76cdecd0428b.png)
It looks like this is happening because the title of current proxy state is too long.

Happens on FF57, latest Nightly on Win10x64 with SmartProxy 0.6.2.

**Comment by salarcode** [comment]
This seems to be a bug from Firefox side.
Any help to workaround it is appreciated.

**Comment by yfdyh000** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1373490

**Comment by salarcode** [comment]
This seems to be fixed for most part from Firefox, nothing we can here so closing..
![image](https://user-images.githubusercontent.com/1272095/126864188-5442841b-bfc6-4d0d-8284-371f54af0b24.png)

![image](https://user-images.githubusercontent.com/1272095/126864178-3027e423-dffa-48b9-8a24-928e0f71911d.png)
