### ISSUE TITLE
The feature called "Use proxy for tab/source" does not work.

### ISSUE THREAD

**Issue by roman90sv** [salarcode/SmartProxy#403]
### Description

The settings say that if the rule matches the tab URL, then all network requests will be forwarded to the proxy (for this active tab). However, this is not true.

I added the domain "youtube.com" to the rules using the add-on button on the browser panel. But the browser continued to make unsuccessful attempts to directly connect to other YouTube video hosting domains. For example: ggpht.com, ytimg.com, etc. These domains are displayed in the list of failed requests. And also, images in the "communities" of YouTube channels are not displayed.
If you change the proxy profile to "Always on", then there are no errors accessing the mentioned domains and the images are displayed in the communities. This means that the "Use proxy for tab/source" function really does not work in Firefox.

ps: If I have to create rules with all YouTube related domains, then it will be more logical to go back to using PAC file.

[Video](https://youtu.be/8qeDakxahHQ)

### Steps to Reproduce

1) Visited youtube.
2) Added domain "youtube.com" to the rules using the add-on button on the browser panel.
3) Browser continued to make unsuccessful attempts to directly connect to other YouTube video hosting domains (which are blocked by the censor). Despite the fact that function "Use proxy for tab/source"  is active.

### Which browsers did you test this on?

Firefox

### Affected browser versions

130.0.1

### Affected SmartProxy versions

1.6

**Comment by salarcode** [comment]
What you see there is list of failed requests, which indicates the request has failed or will be failed if no response comes back.
That does not mean that requests requests are not going through proxy. 
It means something wrong with the request, could be bad proxy problem too being slow.


To check whether requests are going through proxy or not use "Proxyable Resources" and what the results

![image](https://github.com/user-attachments/assets/250d8402-9f05-462b-812a-69adbb2faccf)

**Comment by brawaru** [comment]
@salarcode I'm using Proxyable Resources, and opening `x.com`, only everything to `x.com` domain gets matched and proxied, all other requests, like ones to `abs.twimg.com`, report ➖ No Proxy, ➖ No Match. And on https://www.ipify.org/, adding `www.ipify.org` domain rule, request to API on the tab is fetched without proxy, giving you a non-proxy IP.

**Comment by roman90sv** [comment]
As you can see in the screenshots, the add-on does not proxy i.ytimg.com on YouTube pages.
The video shows that in YouTube communities images are not loading. This is clear evidence that the add-on does not route YouTube related domains.

When I use PAC with all YouTube related domains I have no problems. 
I have a personal proxy server. It is fast. And My proxy works through trojan protocol, which is invulnerable to DPI.

![Снимок экрана от 2024-09-29 17-30-07](https://github.com/user-attachments/assets/460aed29-800f-42a1-b1b9-0ec80f5b4047)
![Снимок экрана от 2024-09-29 17-31-02](https://github.com/user-attachments/assets/8bbcf126-8e19-4c57-8133-f656544b071f)

**Comment by roman90sv** [comment]
![1](https://github.com/user-attachments/assets/9f3b63e7-cc76-47eb-9bcd-2f15f2e4a760)
![Снимок экрана от 2024-09-29 17-55-04](https://github.com/user-attachments/assets/5ec08620-2615-4687-bfa3-44fdc9c3fe06)
![Снимок экрана от 2024-09-29 17-31-02](https://github.com/user-attachments/assets/54e00f68-506a-4299-a871-81e5bb4b7e0b)

**Comment by roman90sv** [comment]
![1](https://github.com/user-attachments/assets/8293b0e2-c3c7-427a-9a6d-72b985895be5)
![Снимок экрана от 2024-09-29 17-55-04](https://github.com/user-attachments/assets/9af98ef9-597a-4da1-8cfd-1388ef9989da)
![Снимок экрана от 2024-09-29 17-31-02](https://github.com/user-attachments/assets/af0dbda2-e666-445b-8f66-0c47b8eb2aee)

**Comment by salarcode** [comment]
Confirming the issue thanks to @brawaru  a fix will come out soon

**Comment by roman90sv** [comment]
The bug has been fixed in version 1.6.1.
