### ISSUE TITLE
Agent switching problem

### ISSUE THREAD

**Issue by dotaqi** [salarcode/SmartProxy#404]
### Description

Is it possible to modify the hit rule list and manually switch websites that do not use proxies?

### Steps to Reproduce

Is it possible to modify the hit rule list and manually switch websites that do not use proxies?

### Which browsers did you test this on?

Firefox

### Affected browser versions

130..0.1

### Affected SmartProxy versions

1.6

**Comment by salarcode** [comment]
What are asking is already there from popup menu on the icon. Not sure what else you mean.
