### ISSUE TITLE
how to write IP CIDR block rules?

### ISSUE THREAD

**Issue by CCCAUCHY** [salarcode/SmartProxy#405]
### Description

how to write IP CIDR block rules? I need to access the IPs in 192.168.0.0/16

### Which browsers

Other (Chromium based)

### Browser versions

126.0.6478.231

### SmartProxy versions

1.6

**Comment by salarcode** [comment]
Answered here:
https://github.com/salarcode/SmartProxy/issues/379#issuecomment-2097642779
