### ISSUE TITLE
How to proxy 127.0.0.1?

### ISSUE THREAD

**Issue by CCCAUCHY** [salarcode/SmartProxy#407]
### Description

I'm tring to access a service which is listening 127.0.0.1 on the proxy server

### Which browsers

Other (Chromium based)

### Browser versions

126.0.6478.231

### SmartProxy versions

1.6

**Comment by salarcode** [comment]
Answered here:
https://github.com/salarcode/SmartProxy/issues/379#issuecomment-2097642779

**Comment by CCCAUCHY** [comment]
> Answered here: [#379 (comment)](https://github.com/salarcode/SmartProxy/issues/379#issuecomment-2097642779)

No it does not work. And it can not proxy 127.0.0.1 by **Always Enable** mode.
