### ISSUE TITLE
Proxy Server Subscriptions

### ISSUE THREAD

**Issue by LLKoder** [salarcode/SmartProxy#409]
### Description

Unfortunately chapter Proxy Server Subscriptions is not in wiki. How can I use it? Where can I find lists?

Thanks in advance.

**Comment by salarcode** [comment]
You need to have access to third party lists for proxies, I don't provide those.
The way it works is very similar to Proxy Rules subscription mentioned here: https://github.com/salarcode/SmartProxy/wiki/GFWList 
No free time to update the wiki, sorry
