### ISSUE TITLE
Cannot use subscription proxies only

### ISSUE THREAD

**Issue by RTechSn** [salarcode/SmartProxy#410]
### Description

Hi and thank you for your great work.
But I've encountered a problem with the extension.
When your proxy list contains only proxies provided by a subscription list, you cannot switch it on.

### Steps to Reproduce

1. Subscribe to a proxy list. Have no other proxies specified.
2. Try turning on "Smart Proxy" or "Always Enabled".
3. Settings page is opened instead.

### Which browsers did you test this on?

Chrome, Firefox

**Comment by salarcode** [comment]
Thank you for your report, this is just annoyance and should not affect how proxy profiles work.
The fix for this will be out with the next release
