### ISSUE TITLE
Not able to create rule with Host Wildcard

### ISSUE THREAD

**Issue by t7ko** [salarcode/SmartProxy#414]
### Description

I am trying to create rule for client*.google.com -- and I keep getting error "host name client*.google.com is invalid".

### Steps to Reproduce

1. go to smartproxy settings
2. hit "add multiple rules"
3. select rule type = "host wildcard"
4. in host/rule list enter `client*.google.com`
5. hit Save

result: error message toast with text `host name client*.google.com is invalid`

### Which browsers did you test this on?

Firefox

### Affected browser versions

Firefox 132.0.2

### Affected SmartProxy versions

latest in mozilla store as of 11/15/2024

### Screenshots of the problems or steps to reproduce

![image](https://github.com/user-attachments/assets/6bc14220-9bbe-4a38-b58f-b4e0da586216)

### Any additional context

I also tried to add individual rule -- it fails similarly:

![image](https://github.com/user-attachments/assets/39f508de-18cd-444f-aa64-7e349c9c6af6)

**Comment by salarcode** [comment]
`client*.google.com` is not a valid wildcard pattern for SmartProxy, please see the documents around the correct syntax:
https://github.com/salarcode/SmartProxy/wiki/Proxy-Rules
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns

Perhaps what are you looking for is Regex pattern?

**Comment by t7ko** [comment]
@salarcode -- oh, I see now, you're right.  I actually wanted to use regex but there's no docs or "hello world" examples, so I did not even try it, as there are so many flavors of regexp support.

**Comment by lufog** [comment]
@salarcode, to avoid opening a new issue over a trivial matter, I'll ask here. Am I correct in understanding that JS regexp is being used? Is something like `github.(?:com|io)$` valid? And if so, are there any plans to add regexp usage examples to the wiki?
