### ISSUE TITLE
can not restore proxy server

### ISSUE THREAD

**Issue by CCCAUCHY** [salarcode/SmartProxy#416]
### Description

![image](https://github.com/user-attachments/assets/80de3050-e9b4-4223-9e05-464e766cade0)
this information, proxy server, will all be [Use Active Proxy] after restore backup

### Steps to Reproduce

1. create full backup
2. restore backup

### Which browsers did you test this on?

Other (Chromium based)

### Affected browser versions

128.0.6613.189

### Affected SmartProxy versions

1.6

### Screenshots of the problems or steps to reproduce

![image](https://github.com/user-attachments/assets/c3adeb1a-3c91-42fc-a85f-b8f2dd47ef82)

**Comment by salarcode** [comment]
Thanks, reported and fixed in here #418
