### ISSUE TITLE
rule using given proxy server lost after backup and restore

### ISSUE THREAD

**Issue by zbutfly** [salarcode/SmartProxy#418]
### Description

Define custom proxy server for some rules in one profile, then backup full to a json file. after restoring from the file, the proxy server for those rules always change back to [Use Active Proxy].

### Steps to Reproduce

1. Define custom proxy server for some rules in one profile.
2. Backup full to a json file. 
3. Restoring from the file.
4. The proxy server for those rules always change back to [Use Active Proxy].

### Which browsers did you test this on?

Chrome, Firefox

### Affected browser versions

Chrome Version 131.0.6778.86 (Official Build) (64-bit), Firefox 128.5.1 esr (64-bit)

### Affected SmartProxy versions

Version: 1.6.1

**Comment by salarcode** [comment]
Thanks for the report, the issue is fix and will be out with the next release

**Comment by Francewhoa** [comment]
This is to confirm this challenge

Thanks @salarcode for fixing this. We are looking forward to the next release.

For those facing this challenge, we found this temporary workaround:

Steps:
1. Before restoring a full backup, on the destination SmartProxy, delete all rule(s) that are already present into the full backup. Or, if appropriate, on the destination SmartProxy, simply delete all rules. 
2. On the destination SmartProxy, restore your full backup
3. No data lost. Joy :)

Details at https://github.com/salarcode/SmartProxy/issues/421 Under **Any additional context**.
