### ISSUE TITLE
HTTP basic auth broken in version 0.7 (Firefox)

### ISSUE THREAD

**Issue by fcrespel** [salarcode/SmartProxy#42]
When SmartProxy version 0.7 is installed in Firefox, HTTP basic auth prompts do not show up anymore. I had to temporarily revert to version 0.6.2.

You may use the following link to reproduce: https://httpbin.org/basic-auth/user/passwd
Expected behavior: HTTP auth prompt appears.
Actual behavior: nothing happens, as if the site didn't even try to load.

**Comment by salarcode** [comment]
Thanks for the report
