### ISSUE TITLE
Is it possible to update the extension offline by overwriting it directly?

### ISSUE THREAD

**Issue by DOSforever** [salarcode/SmartProxy#422]
### Description

Due to internet connection, it is not possible to update the extension from chrome web store in online way, so if I download the new version of SmartProxy extension zip file, unzip it with the browser closed and overwrite the previous extension's directory directly,  will the version update be realized? Will the previous SmartProxy settings be overwritten?

### Which browsers

Other (Chromium based)

### Browser versions

Vivaldi 5.6

### SmartProxy versions

1.5

**Comment by salarcode** [comment]
There is no easy way, you might be able to find it through third-party websites which are not safe.
I've uploaded the current version in the release page and you can download it from here:

https://github.com/salarcode/SmartProxy/releases/download/v1.6.2/SmartProxy-v1.6.2-Chrome-ManifestV3.crx
