### ISSUE TITLE
Add option to exclude activation status/active proxy from syncing

### ISSUE THREAD

**Issue by fcrespel** [salarcode/SmartProxy#43]
I use different computers which may need different proxies at different times (e.g. home, work place 1, work place 2, travel, ...). I like the fact that settings are synced across devices, but I don't want the activation status ("Direct", "Smart Proxy", "Always Enable") and the selected proxy to be synced (my proxy at work obviously doesn't function at home).

Could you please provide an option to exclude those settings from syncing? (I still want the proxy lists to be synced).

**Comment by salarcode** [comment]
This will be included in v0.8 next beta
