### ISSUE TITLE
Cannot use Website with HTTP-Auth-Dialog anymore

### ISSUE THREAD

**Issue by jowi24** [salarcode/SmartProxy#45]
I have a page that requests a user/password using http-auth. After activating this addon, the password input dialog does no longer appear. Instead the page returns directly a 401 error. If I choose "Direct (No proxy)", the authentication dialog appears and authentication works. 

Hint: I configured a proxy that uses authentication with user/password. If I use a proxy without authentication, everything works as expected.

**Comment by salarcode** [comment]
Can you please test a special version of smartproxy to see if recent patches work for you? that would be great help.

1- First, disable SmartProxy existing in you browser
2 - Go to releases page and download and install the "unlisted" version of the extension.
	https://github.com/salarcode/SmartProxy/releases/download/v0.7.3/smartproxy_unlisted-firefox-0.7.3-an.fx-windows.xpi
3- Apply your servers/rules and configuration by entering them or restoring settings backup.
4- Test your issues if they are fixed

Thanks

**Comment by odo125** [comment]
Sorry to jump in here. user/password using http-auth works for me with your new version 0.7.3. Password dialog appears now even if you use a proxy with auth. 
Thanks

**Comment by salarcode** [comment]
This is fixed in 0.7.3
