### ISSUE TITLE
Bypass List not working with "Always Enabled" 

### ISSUE THREAD

**Issue by br0wnie** [salarcode/SmartProxy#46]
I have the "Enable for 'Always Enable' mode" option selected, but it still isn't working. To test, I added:

google.com
*google.com*
*://*.google.com/*

I wasn't sure if having entries with/without wildcards would make a difference, I couldn't find documentation for the Bypass List feature. Does the host get an auto-created rule like the regular "Add Rule" page does? 

Either way, when going to https://www.google.com the SmartProxy icon is still green, hovering over it says:

"SmartProxy: Always Enable"
"In effect rule:none"
"Proxy server: xxxxxx : xxxx"

Searching "ip" on Google still shows my proxy IP address. Using the "SmartProxy" mode works, but it seems that I would have to go to each site once without a proxy in order to add it to the rules.

I've tried with both Firefox and Waterfox. I've tried with and without "Proxy DNS when using SOCKS v5" and it didn't make a difference.

Is there something I'm missing?

**Comment by salarcode** [comment]
It is possible that there is a bug, let me check.

**Comment by salarcode** [comment]
You have to enter the full domain name e.g:
www.google.com

Notice that "www.google.com" and "google.com" are different and can point to different sites (which in this case redirects to the one with www prefix)
just like "blog.sample.com" and "www.sample.com" are different domain names.

**Comment by Rictusempra** [comment]
@salarcode could you re-open this?
Because I found it not work for localhost, one test way is to use KeePass + KeePassHTTP

**Comment by salarcode** [comment]
According to my tests it works with localhost, can you specify port number to see if it works? e.g. localhost:8080

**Comment by Rictusempra** [comment]
@salarcode my SOCKS5 proxy is on 127.0.0.1:1080, KeePassHTTP window does not popup.

**Comment by salarcode** [comment]
Smartproxy checks for full domain:port name which shouldn't and that causes the issue you have.
Not directly related to this bug but i will look into it.

**Comment by salarcode** [comment]
I have tested localhost in different situations and it works.
@Rictusempra I cannot reproduce your case

**Comment by zerobikappa** [comment]
I also encountered this issue. I am using linux system and firefox.

proxy server: protocol=socks5, sever=127.0.0.1, port=20170;

white list as below:
127.0.0.1
localhost
::1
192.168.1.*

Failed to load these pages under "always enable" mode.

**Comment by salarcode** [comment]
re-open for later investigation.
