### ISSUE TITLE
Bypass list for local addresses fail at each new session until "Save Changes" is pressed again

### ISSUE THREAD

**Issue by br0wnie** [salarcode/SmartProxy#48]
I have been able to reproduce this bug consistently with a SOCKS5 proxy, even after reinstalling Firefox/Waterfox completely:

------

**1.** Select "Always Enable" mode.

**2.** Select "Enable for 'Always Enable' mode" in the "Bypass List" tab.

**3.** Add local address (not sure if correct term) exceptions - in my case for 192.168.0.2 (Pihole) I simply added 192.168.0.2

**4.** Click "Save Changes".

**5.** Close Firefox/Waterfox completely, then open it back up.

**6.** Go to the local address (192.168.0.2 in my case), it will fail to load because the proxy is running despite the bypass rules.

**7.** Go to the "Bypass List" in the SmartProxy settings and hit "Save Changes".

**8.** Reload the local address tab, and it loads instantly.

------

This is a very strange bug, which only seems to occur with local addresses. This doesn't happen with regular websites. **Steps 5-8 are the actual bug that can be repeated, steps 1-4 are just the initial setup.**

**Comment by salarcode** [comment]
Thank you. The bug was at step 5.

**Comment by F10CH** [comment]
I confirm the bug.

What is the format of each address ? Must we put the port like this:
`domain:8080`
or is it useless ?

Is there a wildcard to accept many hosts ?
`
host.domain.com
host.domain.org
domain.com
`
gives `*.domain.*`
