### ISSUE TITLE
The ability to use automatic proxy service settings - url.cap

### ISSUE THREAD

**Issue by YuriiBar** [salarcode/SmartProxy#49]
Add please the opportunity to use automatic proxy service settings, e.g. https://antizapret.prostovpn.org/proxy.pac

**Comment by salarcode** [comment]
There is no point on using another script decide proxy when the sole job of SmartProxy is that.

**Comment by loveqianool** [comment]
I use the PAC provided by https://github.com/txthinking/bypass by default
But I cannot easily add a whitelist to it.
If SmartProxy can match custom rules first
Or for some sites I want to use other proxy servers, for example .Onion uses TOR.

**Comment by wfleischer** [comment]
There is a valid use case for this. Unfortunately, macOS does not support locally stored PAC files. As a result, I use SwitchyOmega, which is no longer maintained. I believe I am not alone in this situation. SmartProxy would be an ideal alternative.
