### ISSUE TITLE
Add  support for port number in rules

### ISSUE THREAD

**Issue by YihaoPeng** [salarcode/SmartProxy#50]
When add a url with port such as `https://hu60.net:4443/`, the partten is not corrent and the proxy will not be applied.

![screenshot](https://user-images.githubusercontent.com/26923506/35746777-e8dc7302-0882-11e8-84bd-ab656ce37ace.png)

> Brought to you by Salar Khalilzadeh , Version: 0.7.2
> Firefox 58.0.1 (64 bits)

**Comment by dayfuaim** [comment]
Dear dev!

I have the same story as @YihaoPeng : I need `http://*.consultant.ru:8882/` to be proxied. Rule `*://*.consultant.ru/*` doesn't work.

It _is_ really needed.
Please, do it.

**Comment by salarcode** [comment]
The fix will be included in next v0.8 beta
