### ISSUE TITLE
YouTube TLS handshake error

### ISSUE THREAD

**Issue by hghofraniha** [salarcode/SmartProxy#55]
hi,
   After working well for a while, suddenly SmartProxy stop loading (TLS handshake problem) YouTube (just youtube, works well for all other sites).

**Comment by mehran5801** [comment]
i have same problem
load every site except youtube.com

**Comment by salarcode** [comment]
This could be proxy server issue.
If not can you try the beta?

**Comment by salarcode** [comment]
If this issue is still valid please open it with the issue details.
