### ISSUE TITLE
Add support for regular expressions

### ISSUE THREAD

**Issue by sn260591** [salarcode/SmartProxy#59]

**Comment by moji1873** [comment]
Hi 
Any update on this one?
It's a very excellent feature missing from SmartProxy but needed as it's very useful in foxyproxy.

Thanks

**Comment by salarcode** [comment]
Similar to #41

**Comment by salarcode** [comment]
Implementation is done in v0.8

**Comment by salarcode** [comment]
Beta 0.8 is out, please test if you can. Thanks :+1:
https://github.com/salarcode/SmartProxy/releases/tag/v0.8-beta1
