### ISSUE TITLE
import base64-encoded gfwlist.txt

### ISSUE THREAD

**Issue by dxg-aceinna** [salarcode/SmartProxy#63]
The file https://github.com/gfwlist/gfwlist/blob/master/gfwlist.txt is base64-encoded. When import it in smartproxy in Firefox, rules in the file are not decoded correctly. Could you add support for this? Periodically update rules from a user-defined URL (gfwlist for example) is better. 
Thank you.

**Comment by KrasnayaPloshchad** [comment]
@salarcode If you want to accept it, you can try to integrate a JS based library, here are some nice libraries you can use:
https://github.com/dankogai/js-base64
https://github.com/mathiasbynens/base64
https://github.com/beatgammit/base64-js

**Comment by salarcode** [comment]
Base64 is builtin Javascript feature.

**Comment by salarcode** [comment]
DUP: https://github.com/salarcode/SmartProxy/issues/34
