### ISSUE TITLE
Import not working correctly

### ISSUE THREAD

**Issue by berkut0** [salarcode/SmartProxy#64]
Tried to add a server, text was generated:
> [SmartProxy Servers]
> nl-84-91-1.friproxy0.eu:443 [HTTPS] [Server 1]

but after import this text zero proxies was imported. Works fine with ip adresses, but it seems like a bug.

**Comment by peckrob** [comment]
Same, affected by this issue as well.

**Comment by salarcode** [comment]
Beta 0.8 is out, please test if you can. Thanks :+1:
https://github.com/salarcode/SmartProxy/releases/tag/v0.8-beta1

**Comment by VoinNochi** [comment]
Frigate import works now, but with issue - all HTTPS detects as HTTP.
Example:
https://uk-170-185-1.fri-gate0.org:443 [UK]
![изображение](https://user-images.githubusercontent.com/39955225/69934473-cdc3ef80-14f3-11ea-8b1a-ab3c25453454.png)
