### ISSUE TITLE
[Feature Request] Proxy API Support

### ISSUE THREAD

**Issue by zero77** [salarcode/SmartProxy#67]
Can you please add support for gimme proxys and/or get proxy list free, they both have a free apt that provides socks4, socks5, http and https all from the APIs.
So users can add a new proxy within the add-on without having to go and find one, unless users want to, in that case they can as normal.

Thanks

https://gimmeproxy.com/api/getProxy
https://gimmeproxy.com

https://api.getproxylist.com/proxy
https://getproxylist.com

**Comment by salarcode** [comment]
Looks interesting, but i'm not sure if they are popular enough to be implemented.
Any other sample?

**Comment by zero77** [comment]
Sadly not that i know of although, i am not saying these are the only ones.

I think they may scrape some of the more popular websites because every now and then when googling a proxy i have found it on a popular websites.

**Comment by salarcode** [comment]
Ok, what I can do and I think is the easiest solution without much change is to implement it as part of "Proxy Server Subscriptions" which should accept data-type of JSON.
That will do.
But first I have to finish the overhaul, so this is a future plan.

**Comment by zero77** [comment]
Thanks
