### ISSUE TITLE
WebSocket not proxied

### ISSUE THREAD

**Issue by simmel** [salarcode/SmartProxy#69]
`wss://` isn't proxied even though scheme is set to `*` in the rules, e.g: `*://*.domain.tld/*`

Even using a specific URL such as `wss://service.domain.tld/*` won't proxy wss.

When using `/ui/proxyable.html` it sees that `wss://` isn't proxied and clicking Enable adds a wildcard URL for that hostname but it still doesn't work.

Anything I can do to help troubleshoot this further?

**Comment by simmel** [comment]
Oh, this is using `Smart Proxy`. If using `Always Enable` it works.

**Comment by salarcode** [comment]
I will look into in this issue in upcoming overhaul

**Comment by simmel** [comment]
Any news?

**Comment by salarcode** [comment]
Having `*` works now. I'm fixing wss schema in the rule.

**Comment by salarcode** [comment]
The fix will be in the next beta

**Comment by simmel** [comment]
Dunno if you want to support non-SSL WebSocket too, but if you want to change the regex to `wss?` so it supports both `ws://` and SSL'd `wss://`.

Thanks!

**Comment by salarcode** [comment]
Thanks for the suggestion it is added now.
