### ISSUE TITLE
feature request: ignoring domains for conenction errors.

### ISSUE THREAD

**Issue by rezad1393** [salarcode/SmartProxy#71]
I use this addon to proxy domains that fail with Iran national filtering system.
but I also block tracking and ad domains with addons and other methods.
the domains include but not limited to :google-ads, amazon-ads and so on.
so this addon sees those domains as fails and shows a number for the connection failures for them, but I intented to block those domains.
can a ignore list be added to this addon for domains like that so when I see the connection failure number on addon I know it is not those?

**Comment by salarcode** [comment]
I think the way you block the urls is not really efficient. What you do is you're blocking responses, which still wastes bandwidth and browser is expecting a response and it won't get it and the browser will keep waiting.
The best option is to block requests.

Any way two new options seem to be helpful for these kind of scenarios:
* Disable monitor connections error
* Ignore connection errors for these domains: [..]

**Comment by salarcode** [comment]
The actual reason for this behavior was an issue in handling the redirect requests being detected as failures.
It is fixed along with these features being added.

**Comment by salarcode** [comment]
Beta 0.8 is out, please test if you can. Thanks :+1:
https://github.com/salarcode/SmartProxy/releases/tag/v0.8-beta1

**Comment by rezad1393** [comment]
when I try to install it, firefox creates a new addon.
should Iimport from stable and test the beta? or can the both be run together?

**Comment by salarcode** [comment]
Create a settings backup from original one, then remove it.
Then restore the back in the beta version and you're good to go.

**Comment by rezad1393** [comment]
I just disabled the addon and are now testing.
btw the new gui makes a change that when a rule that user sets gets applied to subdomains too, the tick behind the rule is not in gray (like the old version) and is the same as the upper rule set manually and this is confusing.

btw I found this out by testing for this bug https://github.com/salarcode/SmartProxy/issues/72#issue-394408743
which is still not fixed and is trivial to fix (I think)

**Comment by salarcode** [comment]
Is this what you're referring to? Because it is grey
![image](https://user-images.githubusercontent.com/1272095/53009449-a5e92b00-348f-11e9-87e7-769453f11a7d.png)
Thanks for testing

**Comment by rezad1393** [comment]
no.
add go.com to your proxy list.
then go to duckduckgo.com 
it will get proxied (a bug I reported) 
and the colour is blue.

**Comment by salarcode** [comment]
Yeah that issue is not fixed yet. I'm aware of that and I'll look into it.

**Comment by rezad1393** [comment]
any progress on that? ty for update.
