### ISSUE TITLE
.go.com and duckduckgo.com

### ISSUE THREAD

**Issue by rezad1393** [salarcode/SmartProxy#72]
if I add the doamin "go.com" to the rules then "duckduckgo.com" gets added two because your addon confuse that with .go.com.
this is a bug please fix it. so that other domains dont get proxy-ied too.
this is a bug in your domain matching implementation. I used to get that in my pac file too until i fixed it.

**Comment by salarcode** [comment]
Thank you for the report. This will be released in the next beta.

**Comment by salarcode** [comment]
Beta 2 is released
