### ISSUE TITLE
Allow the use of empty password field when filling user field

### ISSUE THREAD

**Issue by ylmrx** [salarcode/SmartProxy#73]
Some proxy providers (such as Crawlera) will use the proxy's "username" as some sort of api key... and ask for an empty password. Smartproxy shouldn't consider `(ui/settings.js:1010)`

```js
(serverInputInfo.username && !serverInputInfo.password)
```

as an error case.

**Comment by ylmrx** [comment]
Thanks a bunch for considering the issue, I wanted to send a patch, but I lack the language skills for all the new translations it would need :neutral_face:

**Comment by salarcode** [comment]
No need to worry, it will be included in next version. And the if condition for both Typescript and Javascript is same

**Comment by salarcode** [comment]
Beta 0.8 is out, please test if you can. Thanks :+1:
https://github.com/salarcode/SmartProxy/releases/tag/v0.8-beta1
