### ISSUE TITLE
Chrome paused Sync by SmartProxy

### ISSUE THREAD

**Issue by bobbyholla** [salarcode/SmartProxy#74]
Hi, SmartProxy cause Google Chrome to pause Sync every time I open chrome. This issue is affecting my work terrible because it keeps asking me to sign in again all the time. please fix this

**Comment by salarcode** [comment]
How many rules + servers you have defined?
Can I have a backup of the settings?

**Comment by salarcode** [comment]
I haven't faced any issues so far. Feel free to open again with more clarifications.
