### ISSUE TITLE
Import proxy rules from 0.7.3 to current beta

### ISSUE THREAD

**Issue by oldhasu** [salarcode/SmartProxy#76]
Proxy rules import from 0.7.3 currently not working for me in v0.8 Beta 1. Im trying to transfer all rules via backup, seems SmartProxy-RulesBackup.json has a different format now.

**Comment by salarcode** [comment]
What is not working exactly?
Yes the format is changed but the import process is compatible with old versions.

**Comment by oldhasu** [comment]
Thank you! I finally imported all the rules via restore backup as you suggested. But had to restart plugin for them to show up, so that made me think its not working the first time I did it (unlike server list import that showed up immediately).
