### ISSUE TITLE
[Feature Request] Proxy For Third Party Domains Only

### ISSUE THREAD

**Issue by zero77** [salarcode/SmartProxy#77]
I don't know if this is possible but.
Can you please add an option to use a proxy for third party domains only.
Either on a single page or for all third party domains and ideally a separate proxy for each domain.
Thanks

**Comment by salarcode** [comment]
I'm not sure how this is gonna help. If you want to enable proxy for specific domain just them in rules tab in settings. So whenever that domain hits, it will have proxy enabled whether the request is in a top level window or as a request inside a page.

**Comment by zero77** [comment]
@salarcode 
I was thinking of privacy, to stop third party domains getting your ip and building a profile on you.

**Comment by salarcode** [comment]
That is not how privacy works. They store information everywhere including cookies and browser storage.
You need to block them in ad-blocking extensions. Changing ip won't help especially this way.
Closing this for now.
