### ISSUE TITLE
Settings not fully migrated after upgrading to v0.8

### ISSUE THREAD

**Issue by glitsj16** [salarcode/SmartProxy#78]
Hi, after upgrading this excellent extension to v0.8 (which otherwise looks very nice) it seems as if the `Bypass List` settings are no longer working. Receiving access denied errors from my configured proxies for localhost. Haven't much more detailed info to provide here right now, don't see anything in Firefox's browser console. I'm on Arch Linux and Firefox is currently at version 66.0.2. The below settings work as expected with SmartProxy v0.7.3:

```
Bypass List
- Enable for 'Always Enable' mode [checked]
- Enable for 'System Proxy' mode (Firefox only) []

Bypass List
127.0.0.1
lab16
localhost
::1
```
Downgrading to 0.7.3 brings back sanity and these settings are respected again. If there's a way to provide more debug info, please advise.

Regards.

**Comment by salarcode** [comment]
I've tested the Bypass again and it iw working fine.
Is always enable mode on?
Are you using any other proxy extensions?

**Comment by glitsj16** [comment]
@salarcode Yes, 'Always enable' mode is on. And SmartProxy is the only proxy extension that's installed. I've thought about removing `localhost` from the Bypass list and making a proxy rule for it that uses a `direct connection`, but that doesn't seem to be possible. At least I couldn't find a way to achieve that. I'll do some more testing in a fresh Firefox profile with only SmartProxy installed. Thanks for looking into this.

**Comment by glitsj16** [comment]
@salarcode Update: I've done some extensive testing of `v0.8` in a fresh Firefox profile (the only installed extension):
- the Bypass List does indeed work as expected;
My original issue was caused by SmartProxy being in 'Always Enabled' mode instead of in 'Smart Proxy' mode, which was what I had set before upgrading. The upgrade must have reset that, which I missed somehow...
- settings for 'Syncing' are giving me another issue: when I uncheck the 'Enable settings syncing' under 'General Options', save settings and restart Firefox, this always resets to being checked. The sub-options are respected. For me this isn't a problem, as I never use Sync anyway. Just thought I'd throw this in, other people might use the syncing facility.

Thanks again for all your work on this wonderful extension.

**Comment by salarcode** [comment]
Thank you for investigation. The first issue is because of upgrade which old options are not migrated correctly to the new format.
I'm currently fixing the Syncing issue and will release both fixes soon.

**Comment by glitsj16** [comment]
@salarcode That's indeed what I'm seeing, the same thing happens with the chromium extension. I've changed the issue description to assist users skimming through the issues list here. Thank you for looking into this, very much appreciated.

**Comment by salarcode** [comment]
0.8.1 is released hope that fixes the issues.
Thanks for reporting them.

**Comment by glitsj16** [comment]
@salarcode I can confirm v0.8.1 fixes the issues on Firefox. That was super-fast, thanks. I guess things should be fine on chromium too, awaiting upgrade from v0.8 to v0.8.1 there. Cheers!
