### ISSUE TITLE
Cannot create proxy rules using servers with authentication

### ISSUE THREAD

**Issue by DeronLJ** [salarcode/SmartProxy#79]
Firefox 66.0.2 64-bit Windows, SmartProxy 0.8.1
Navigate to Proxy Rules -> Add Rule
In the Rule Details screen, under Proxy Server, the message is displayed "(Servers with authentication not supported)". This is the case no matter which Rule Type is selected.
Servers with authentication worked before version 0.8 .

Overall I am very happy with the additions in version 0.8.x, but it would be really helpful if servers with authentication worked again.

**Comment by salarcode** [comment]
In the previous versions authentication wasn't working correctly in this way.
There is no actual solution for that or if any that would be very difficult get it right.

**Comment by DeronLJ** [comment]
It actually did seem to work for me in the previous version, but I understand that it might not have always been reliable. On balance the more flexible proxy rules are worth the trade off.

**Comment by salarcode** [comment]
It was never working before and it was a bug.
I will try to have look for a solution, until then there is no plan to implement them.

**Comment by salarcode** [comment]
Turns out Socks authentication is supported and only HTTP/S authentication has issues.
I will allow the socks proxies with authentication in next release.
