### ISSUE TITLE
imcompatible with Kee addon

### ISSUE THREAD

**Issue by Riajyuu** [salarcode/SmartProxy#80]
https://www.kee.pm/

It seems to be bypass list things and happening before. It is just here once again.

**Comment by salarcode** [comment]
I'll have a look

**Comment by Riajyuu** [comment]
@salarcode when you are in always enable mode, the kee addon can't connect to your keepass database anymore unless switching to direct mode.

**Comment by rezad1393** [comment]
have you added the url and port for kee connections?
you have to add port too.

**Comment by Riajyuu** [comment]
> you have to add port too.

Any example?

**Comment by rezad1393** [comment]
like 127.0.0.1:8880 ?
find the listening port on kee and add it.

**Comment by salarcode** [comment]
@Riajyuu Does the addon work in SmartMode?
Try adding the port number to "Bypass list", something like 127.0.0.1:8880.

**Comment by Riajyuu** [comment]
@salarcode 
>Does the addon work in SmartMode

seems yes

>something like 127.0.0.1:8880

seems works.

but why localhost does not include this?

**Comment by rezad1393** [comment]
> @salarcode
> 
> > Does the addon work in SmartMode
> 
> seems yes
> 
> > something like 127.0.0.1:8880
> 
> seems works.
> 
> but why localhost does not include this?

because localhost means 127.0.0.1 and that seems to mean in this addon as 127.0.0.1:80
so you have to add other ports individually.

**Comment by salarcode** [comment]
I assume the issue is fixed by user by now
