### ISSUE TITLE
Regex rules for ignoring domains and/or subdomains when detecting conenction failures

### ISSUE THREAD

**Issue by rezad1393** [salarcode/SmartProxy#83]
this feature was added in version 0.8 if I recall correctly.
but it only works with specific subdomain that the user has to specify.
So it doesn't include subdomains of the domain specified.
so fo example if I add googlesyndication.com it doesn't include the subdomains and I have to add them one by one.
Can you add an option to either include all the subdomains of the domains specified or add support for wildcard for adding all the subdomains?

**Comment by salarcode** [comment]
Fixed in v1.0 by #213
