### ISSUE TITLE
"Smart proxy" mode not working with tinyproxy from the start

### ISSUE THREAD

**Issue by Dvvarf** [salarcode/SmartProxy#85]
Hello,
First of all, great extension.

I have a bit of a problem though: the extension is not working for me "from the start". For "Smart Proxy" mode to work with HTTPS websites I have to perform the following steps:

1. Switch to "Always enable" mode.
2. Open some HTTPS website.
3. Now I can switch back to "Smart Proxy" mode and it would work great until I either restart the browser or proxy server.

If I try to open an HTTPS site without performing these steps first, it'll be accessed through direct connection.

I'm using Opera 60 (latest) on Windows 10 as my browser and tinyproxy 1.8.4 as my proxy server. Tinyproxy is set as HTTP server in configuration (it doesn't work as HTTPS). Tinyproxy is an HTTP server, but it supports outgoing HTTPS connections and it works for HTTPS websites when it's asked to do so. It doesn't support incoming HTTPS connections though. Is there a way to make SmartProxy to work in this configuration without going through the steps I listed every time?

Thanks!

**Comment by salarcode** [comment]
SmartProxy doesn't care about your proxy server at all.
All I can see here is that your rules are not defined correctly, can you double check them?

**Comment by salarcode** [comment]
If possible upload the rules backup here

**Comment by Dvvarf** [comment]
I'm not sure about that... I deleted all my rules and made only one. And all of this is reproducible with this only rule. I've added the site ping.eu to the rulelist, because it's easy to see whether the request is being proxied or not. I've attached the backup, but it's really just this one rule. One thing I've noticed: if you modify the list of rules and click "Save" or just export the rules, the proxy starts working.

[SmartProxy-RulesBackup.zip](https://github.com/salarcode/SmartProxy/files/3179379/SmartProxy-RulesBackup.zip)

**Comment by salarcode** [comment]
Did you say Opera 60? I do not support Opera just yet. Is that the problem?

**Comment by Dvvarf** [comment]
I've installed the extension on Chrome 73 (that's what I had on hand) and the issue persists there as well.

It is also mentioned in an issue #81.

**Comment by salarcode** [comment]
Finally found the issue. It happens in Chrome based browsers only.
The fix will be in 0.8.5
