### ISSUE TITLE
Add I18n support

### ISSUE THREAD

**Issue by salarcode** [salarcode/SmartProxy#9]

**Comment by salarcode** [comment]
A workaround to internationalize the Html files: https://stackoverflow.com/a/39810769/322446

**Comment by EMLVIRUS** [comment]
Maybe you should enable wiki for this for adding guidelines

**Comment by Rictusempra** [comment]
@salarcode I'm now translating to zh-CN, maybe you can expect PR in few hours :-)

**Comment by Rictusempra** [comment]
@salarcode if you would like to have amo descriptions localized, you shall implement on your side (github readme is easy)

**Comment by salarcode** [comment]
It has to be html, since it is shared in settings page as well.
