### ISSUE TITLE
SmartProxy does not work with firefox 67 and higher.

### ISSUE THREAD

**Issue by hapur** [salarcode/SmartProxy#90]
SmartProxy does not work with Firefox 67 and higher. After updating Firefox, all proxies and rules disappeared. Downloading a backup did not help. Added rules and rules manually without any result. Proxy and rules appeared but they did not work in any of the modes. After closing firefox in the open again all the proxies and rules disappeared again. After reinstalling the extension, everything worked until firefox was closed. Then everything was gone again. Works with Firefox 66.0.5.

sorry for bad english Goggle Translate

**Comment by salarcode** [comment]
Check the allow in Incognito and try again.

![image](https://user-images.githubusercontent.com/1272095/59137647-1a5ac200-89cc-11e9-963d-fa4d089d5020.png)

**Comment by hapur** [comment]
allowed

**Comment by salarcode** [comment]
I cannot reproduce your issue.
Can try and uncheck the **Syncing** options

**Comment by hapur** [comment]
completely removed and installed firefox ... after that smartproxy started working.

**Comment by salarcode** [comment]
glad it worked
